import {categories} from './model.ts';
import {randomUUID} from 'node:crypto';
import {InformantService} from './informants.ts';
import {isOrganic} from './seeded-policy.ts';
import {isGtaVI} from './gta-vi-staging.ts';
import {DeterministicSemanticSupport,evaluateFeedQuality} from './feed-quality.ts';
export type ChallengeStatus='DRAFT'|'OPEN'|'JUDGING'|'CLOSED'|'CANCELLED';
export type Challenge={id:string;title:string;description:string;category:string;startDate:string|null;endDate:string|null;eligibility:string;submissionRequirements:string;status:ChallengeStatus;rewardType:'PROPOSED_GIFT_CARD'|'RECOGNITION'|'NONE';rewardDescription:string;verificationRequirements:string;winner:string|null;entries:string[];fulfillmentEnabled:false};
export const challengeTemplates=['SNITCH OF THE WEEK','VEHICLE HUNTER','MAP HUNTER','BUG HUNTER','FIRST WEEK DISCOVERY','THE BIG SCORE'];
export const stagingChallenge:Challenge={id:'snitch_of_the_week',title:'SNITCH OF THE WEEK',description:'Bring The Wire the best verified intel.',category:'all',startDate:null,endDate:null,eligibility:'Authenticated organic Informants with their own active, source-backed GTA VI contribution. Seeded accounts and staff are ineligible.',submissionRequirements:'Submit an existing eligible intel contribution. One entry per contribution; no new evidence is created by entering.',status:'DRAFT',rewardType:'PROPOSED_GIFT_CARD',rewardDescription:"Proposed $25 McDonald's gift card. Staging preview only; no funded offer or prize fulfillment is active.",verificationRequirements:'Current VERIFIED, PUBLISHABLE GTA VI intel, at least two independent supporting sources and grounded supporting evidence from the entrant. A moderator judges usefulness, specificity, freshness and evidence quality. Votes cannot establish truth.',winner:null,entries:[],fulfillmentEnabled:false};
export class ChallengeService {
 service:InformantService;constructor(service:InformantService){this.service=service;}
 moderator(actor:string){this.service.moderator(actor);const p=this.service.account(actor);if(!isOrganic(p)||p.suspended)throw Error('Active organic moderator required');}
 create(actor:string,template:string,category='all'){this.moderator(actor);if(!challengeTemplates.includes(template)||!['all',...categories].includes(category))throw Error('Supported challenge template and category required');const id=template.toLowerCase().replaceAll(' ','_');if(this.list().some(c=>c.id===id))throw Error('Challenge already exists');const c:Challenge={...structuredClone(stagingChallenge),id,title:template,category,rewardType:'RECOGNITION',rewardDescription:'Editorial recognition only. No funded prize or fulfillment.',description:'Find a specific, useful GTA VI observation and bring source-backed evidence to the editorial desk.'};this.service.save('challenges',c);this.service.audit(actor,'CHALLENGE_CREATE',id,{template,category});return c;}
 rows(){return this.service.rows('challenges') as Challenge[];}
 list(){const rows=this.rows();return rows.some(c=>c.id===stagingChallenge.id)?rows:[structuredClone(stagingChallenge),...rows];}
 get(id:string){const c=this.list().find(c=>c.id===id);if(!c)throw Error('Challenge not found');return c;}
 eligible(actor:string,submissionId:string,challengeId:string){const p=this.service.account(actor);if(!isOrganic(p)||p.role!=='informant'||p.suspended)return false;const s=this.service.rows('submissions').find(s=>s.id===submissionId&&s.informantId===actor&&s.state==='active');if(!s)return false;const challenge=this.get(challengeId),repo=this.service.repo,checker=new DeterministicSemanticSupport();return repo.claims().some(c=>isGtaVI(c)&&c.status==='VERIFIED'&&c.publication?.state==='PUBLISHABLE'&&evaluateFeedQuality(c,repo.evidence(),repo.sources()).state==='PUBLISHABLE'&&Number(c.breakdown.independentSupporting??0)>=2&&(challenge.category==='all'||c.category===challenge.category)&&repo.evidence().some(e=>{const source=repo.sources().find(x=>x.id===e.sourceId);return e.claimId===c.id&&e.sourceId===s.sourceId&&e.stance==='supports'&&source&&!source.raw.synthetic&&!source.raw.informantSuppressed&&checker.check(c,e,source).result==='supported';}));}
 candidates(actor:string,id:string){return this.service.rows('submissions').filter(s=>this.eligible(actor,s.id,id));}
 enter(actor:string,id:string,submissionId:string,at=new Date().toISOString()){const c=this.get(id);if(c.status!=='OPEN'||!c.startDate||!c.endDate||!Number.isFinite(Date.parse(at))||Date.parse(at)<Date.parse(c.startDate)||Date.parse(at)>Date.parse(c.endDate))throw Error('Challenge is not open for entries');if(!this.eligible(actor,submissionId,id))throw Error('An eligible verified organic GTA VI contribution is required');if(this.service.rows('challengeEntries').some(e=>e.challengeId===id&&e.submissionId===submissionId))throw Error('Contribution already entered');const e={id:randomUUID(),challengeId:id,informantId:actor,submissionId,at};this.service.save('challengeEntries',e);this.service.save('challenges',{...c,entries:[...c.entries,e.id]});this.service.audit(actor,'CHALLENGE_ENTER',e.id,{challengeId:id,submissionId});return e;}
 configure(actor:string,id:string,input:any){this.moderator(actor);const c=this.get(id);if(!['DRAFT','OPEN','JUDGING','CLOSED','CANCELLED'].includes(input.status))throw Error('Invalid challenge status');const transitions:Record<string,string[]>={DRAFT:['DRAFT','OPEN','CANCELLED'],OPEN:['OPEN','JUDGING','CANCELLED'],JUDGING:['JUDGING','CANCELLED'],CLOSED:['CLOSED'],CANCELLED:['CANCELLED']};if(!transitions[c.status].includes(input.status))throw Error('Invalid challenge transition; use manual award to close judging');const start=input.startDate??c.startDate,end=input.endDate??c.endDate;if(input.status==='OPEN'&&(!start||!end||!Number.isFinite(Date.parse(start))||!Number.isFinite(Date.parse(end))||Date.parse(start)>=Date.parse(end)))throw Error('Valid start and end dates required');const next={...c,status:input.status,startDate:start,endDate:end,fulfillmentEnabled:false as const};this.service.save('challenges',next);this.service.audit(actor,'CHALLENGE_CONFIGURE',id,{status:next.status,startDate:start,endDate:end});return next;}
 award(actor:string,id:string,entryId:string,note:string){this.moderator(actor);const c=this.get(id),entry=this.service.rows('challengeEntries').find(e=>e.id===entryId&&e.challengeId===id);if(c.status!=='JUDGING'||!entry||!this.eligible(entry.informantId,entry.submissionId,id))throw Error('An eligible organic entry in judging is required');if(typeof note!=='string'||note.trim().length<10||note.length>2000)throw Error('Manual judging rationale required');this.service.save('challengeJudgments',{id:randomUUID(),challengeId:id,entryId,actor,note,at:new Date().toISOString()});const next={...c,status:'CLOSED' as const,winner:entryId,fulfillmentEnabled:false as const};this.service.save('challenges',next);this.service.audit(actor,'CHALLENGE_MANUAL_AWARD',id,{entryId,note,fulfillmentEnabled:false});return next;}
}
