import {createHash} from 'node:crypto';
import type {SourceItem,Evidence,Claim} from './model.ts';
import {robotsDecision} from './web.ts';
import {claimFingerprint} from './proposition.ts';
export const communityLimits={maxItems:100,maxPerCommunity:30,maxPages:12,maxRequests:30,maxBytes:3000000};
export type CommunityPolicy={domain:string;decision:'allow'|'skip';reason:string;reviewedAt:string;termsUrl:string;delayMs:number;excerptWords:number};
export type ForumPost={id:string;parentId:string|null;text:string;author:string|null;timestamp:string;editedAt:string|null;reactions:number;staff:boolean};
export type ForumThread={community:string;id:string;title:string;url:string;pageUrl:string;posts:ForumPost[]};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export function plain(html:string){return html.replace(/<blockquote[\s\S]*?<\/blockquote>/gi,' ').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();}
function post(p:any):ForumPost{return {id:p.id,parentId:p.parentId??null,text:plain(p.bodyHtml??p.bodyText??''),author:p.profile?.usernameSlug??p.profile?.displayName??null,timestamp:p.createdAt??'1970-01-01T00:00:00.000Z',editedAt:p.updatedAt??null,reactions:Number(p.voteScore??p.helpfulCount??0),staff:!!(p.isStaffAnswer||p.isStaffComment)};}
export function parseBoomCommunity(html:string,url:string):ForumThread[]{
 const chunks=[...html.matchAll(/self\.__next_f\.push\((\[[\s\S]*?\])\)<\/script>/g)].flatMap(m=>{try{return JSON.parse(m[1]).filter((x:any)=>typeof x==='string');}catch{return [];}}).join('\n');
 const out:ForumThread[]=[],seen=new Set<string>();
 const visit=(x:any)=>{if(!x||typeof x!=='object')return;if(x.state?.canonicalUrl===url){const s=x.state;for(const t of s.threads??[]){if(seen.has(t.id))continue;seen.add(t.id);out.push({community:'GTA BOOM',id:t.id,title:t.title,url:new URL(t.permalink,url).href,pageUrl:url,posts:[post(t.question),...(t.answers??[]).map(post)]});}
 if(s.comments&&!seen.has(s.threadId)){seen.add(s.threadId);const flatten=(ps:any[]):ForumPost[]=>ps.flatMap(p=>p.isRemoved?[]:[post(p),...flatten(p.replies??[])]);out.push({community:'GTA BOOM',id:s.threadId,title:x.articleTitle??'Article discussion',url,pageUrl:url,posts:flatten(s.comments)});}}
 for(const v of Object.values(x))if(typeof v==='object')visit(v);};
 for(const line of chunks.split('\n')){const p=line.indexOf(':');if(p<0)continue;try{visit(JSON.parse(line.slice(p+1)));}catch{}}
 return out;
}
export function ownExperiment(p:ForumPost){return !p.staff&&/\bI (?:tested|tried|reproduced|completed|sold|earned|fixed|found)\b/i.test(p.text)&&/\b(?:got|earned|paid|worked|failed|fixed|no longer|did not|doesn't|result|after|today|yesterday|update|patch)\b/i.test(p.text)&&!/^\s*(?:same|thanks|yes|agreed)\b/i.test(p.text);}
export function forumItems(threads:ForumThread[],now:string,words=180):SourceItem[]{const items:SourceItem[]=[],seen=new Set<string>();for(const t of threads){const roots=t.posts.filter(p=>!p.parentId),root=roots[0];for(const p of t.posts){if(seen.has(p.id)||!p.text)continue;seen.add(p.id);const excerpt=p.text.split(/\s+/).slice(0,words).join(' '),parent=t.posts.find(q=>q.id===p.parentId),author=p.author?hash(t.community+':'+p.author).slice(0,24):null;const contextMissing=!!p.parentId&&!parent;
 items.push({id:'community:'+hash(t.community+':'+p.id).slice(0,24),platform:'community',sourceId:p.id,url:t.url+'#comment-'+p.id,title:t.title,text:excerpt,author,timestamp:p.timestamp,ingestedAt:now,engagement:{score:p.reactions},itemType:p.parentId?'comment':'post',pilotId:'community-v0',independenceKey:'community:thread:'+t.id,context:{subreddit:t.community,postId:root?.id??p.id,postTitle:t.title,postBody:root?.text.split(/\s+/).slice(0,words).join(' ')??'',parentId:p.parentId??'',parentText:parent?.text.split(/\s+/).slice(0,words).join(' '),threadId:t.id,discovery:['public_html'],coverage:contextMissing?'MISSING_PARENT':'public initial page entries only'},raw:{community:t.community,threadUrl:t.url,pageUrl:t.pageUrl,postId:p.id,parentId:p.parentId,publishedAt:p.timestamp,updatedAt:p.editedAt,contextMissing,ownExperiment:ownExperiment(p),staff:p.staff,publicationNetwork:p.staff?'GTA BOOM':null,contentDigest:hash(p.text.toLowerCase().replace(/\W/g,'')),storage:'bounded public UGC excerpt; no profile, avatar, email or IP; no public reuse licence assumed',excerptTruncated:excerpt!==p.text}});}}
 // Copied bodies cannot become distinct experiments, even with different authors/threads.
 const bodies=new Map<string,string>();for(const s of items){const k=String(s.raw.contentDigest);if(bodies.has(k))s.copiedFrom=bodies.get(k);else bodies.set(k,s.id);}return items;}
export function communityFamily(s:SourceItem){if(s.platform!=='community')return null;if(s.raw.contextMissing||s.copiedFrom||!s.author||!s.raw.ownExperiment||s.raw.staff)return s.independenceKey;return 'community:experiment:'+s.raw.community+':'+s.author;}
export function communityConsensus(c:Claim,evidence:Evidence[],sources:SourceItem[]){const supporters=new Set<string>(),against=new Set<string>(),unresolved=new Set<string>();for(const e of evidence.filter(e=>e.claimId===c.id)){const s=sources.find(s=>s.id===e.sourceId);if(!s||s.platform!=='community')continue;const person=s.author??s.id;
 const aligned=claimFingerprint({...c,...e.candidate})===claimFingerprint(c);if(!s.raw.ownExperiment||s.copiedFrom||s.raw.contextMissing||!aligned||e.stance==='uncertain')unresolved.add(person);else(e.stance==='supports'?supporters:against).add(person);}
 for(const p of supporters)if(against.has(p)){supporters.delete(p);against.delete(p);unresolved.add(p);}return {independent_supporters:supporters.size,independent_contradictors:against.size,unresolved_participants:unresolved.size,popularityUsedAsTruth:false};}
export class PendingRedditCommunityAdapter {name:string;constructor(subreddit:'gtaonline'|'GTA'){this.name='pending-reddit:'+subreddit;}async fetchItems():Promise<SourceItem[]>{throw Error('Official Reddit API approval pending; scraping forbidden');}}
export class PublicCommunityAdapter {
 name='community-v0';requests=0;skips:{url:string;reason:string}[]=[];policies:CommunityPolicy[];urls:string[];fetcher:typeof fetch;private robots=new Map<string,string>();private last=new Map<string,number>();
 constructor(urls:string[],policies:CommunityPolicy[],fetcher:typeof fetch=fetch){this.urls=urls;this.policies=policies;this.fetcher=fetcher;}
 async request(url:string){if(++this.requests>communityLimits.maxRequests)throw Error('request limit');const r=await this.fetcher(url,{redirect:'manual',signal:AbortSignal.timeout(15000),headers:{'User-Agent':'ViceWireResearch/0.1 (bounded AI research; respects AI restrictions)'}});if(!r.ok)throw Error('HTTP '+r.status+'; FOUND BUT NOT ACCESSIBLE; no redirect/challenge bypass');if(/noai/i.test(r.headers.get('x-robots-tag')??''))throw Error('AI opt-out');const reader=r.body!.getReader(),parts:Uint8Array[]=[];let n=0;while(true){const {done,value}=await reader.read();if(done)break;n+=value.length;if(n>communityLimits.maxBytes){await reader.cancel();throw Error('byte limit');}parts.push(value);}const text=Buffer.concat(parts).toString('utf8');if(/cf-chl-|verify you are human|captcha|just a moment|<meta[^>]+noai/i.test(text.slice(0,20000)))throw Error('challenge/AI opt-out');return text;}
 async fetchItems(){const items:SourceItem[]=[];for(const url of [...new Set(this.urls)].slice(0,communityLimits.maxPages)){try{const u=new URL(url),p=this.policies.find(p=>p.domain===u.hostname);if(u.protocol!=='https:'||u.username||u.password||!p||p.decision!=='allow')throw Error(p?.reason??'unreviewed domain');if(!this.robots.has(u.origin))this.robots.set(u.origin,await this.request(u.origin+'/robots.txt'));const d=robotsDecision(this.robots.get(u.origin)!,u.pathname+u.search);if(!d.allowed)throw Error(d.reason);const delay=Math.max(p.delayMs,d.delayMs)-(Date.now()-(this.last.get(u.origin)??0));if(delay>0)await new Promise(r=>setTimeout(r,delay));this.last.set(u.origin,Date.now());const html=await this.request(url);const parsed=forumItems(parseBoomCommunity(html,url),new Date().toISOString(),p.excerptWords);for(const s of parsed){if(items.some(i=>i.id===s.id))continue;if(items.filter(i=>i.raw.community===s.raw.community).length>=communityLimits.maxPerCommunity)break;items.push(s);if(items.length>=communityLimits.maxItems)break;}if(!parsed.length)this.skips.push({url,reason:'No public thread entries; no API fallback'});}catch(e){this.skips.push({url,reason:e instanceof Error?e.message:'access failed'});}}const bodies=new Map<string,string>();for(const s of items){const key=String(s.raw.contentDigest);if(bodies.has(key))s.copiedFrom=bodies.get(key);else bodies.set(key,s.id);}return items;}
}
