import {bindDiscoveryPropositions} from './discovery-binding.ts';
import {numericRoles} from './discovery-numeric.ts';
import {semanticAction,entityRoleValid,projectQualifiedProposition} from './discovery-projection.ts';
import {semanticTimes,reportOutcome,qualifyWholeReport,semanticEntity,semanticRewards,attachFieldSupport,supportedSpan,discoveryPrimarySignal} from './discovery-semantics.ts';
import type {Candidate,SourceItem} from './model.ts';
import type {DiscoveryDraft,DiscoveryLocation,DiscoveryReward,DiscoveryType} from './discovery-model.ts';
import {validateDiscoveryDraft,discoveryCategory,discoveryTypes} from './discovery-model.ts';
import {valueSemantics} from './semantics.ts';
import {locateQuote} from './provenance.ts';
const clean=(s:string)=>s.trim().replace(/[.;]$/,'');
// Model paraphrases and metadata never strengthen primary discovery evidence.
export function groundedDiscoveryCandidate(c:Candidate):Candidate{
 const q=c.quote;const literal=(v:string)=>q.toLowerCase().includes(v.toLowerCase());
 const ledger=numericRoles(q,c.conditions.game??'UNKNOWN');
 const moneyUnits=['GTA$','USD','EUR','GBP'];
 const values=c.values.filter(v=>ledger.some(n=>n.value===v.value&&(moneyUnits.includes(v.currency??v.unit??'')?n.role==='MONEY'&&n.currency===(v.currency??v.unit):n.role!=='MONEY'&&n.role!=='UNKNOWN'||n.role==='MONEY'&&v.currency==='unknown')));

 return {...c,claim:locateQuote(q,c.claim)?c.claim:q,conditions:Object.fromEntries(Object.entries(c.conditions).filter(([k,v])=>k==='game'||literal(v))),values};
}
export function extractDiscovery(c:Candidate,s:SourceItem):DiscoveryDraft|null{
 c=groundedDiscoveryCandidate(qualifyWholeReport(c,s));const q=c.quote;if(!locateQuote(s.itemType==='comment'?s.text:s.title+'\n'+s.text,q))throw Error('Discovery quote is not primary evidence');
 // Reference facts, questions and empty hype never become gameplay discoveries.
 if(/^(?:I wish|It would be|If only|I'd like|I would like)\b/i.test(q.trim())&&!/\b(?:I|we) (?:found|tested|entered|used)\b/i.test(q))return null;
 if(/\b(?:gallery names|scheduled for|launch platform|character biography|previously scheduled)\b/i.test(c.claim)||q.trim().endsWith('?')&&!discoveryPrimarySignal(q))return null;
 if(!/\b(?:safe|loot|found|spawn(?:s|ed)?|drops?|drop|enter(?:ed|ing)?|reboot(?:ed)?|restart(?:ed)?|entrance|interior|collectible|collect|bypass|route|rob|cooldown|stopped working|no longer works|patched|workaround|freeze|crash|unlock|secret|easter egg|business|payout|worked|money method|mission|heist|earn(?:s|ed)?|reward|bonus|revolver|noclip|room|doors?|clues?|appeared|attacked|error)\b/i.test(q))return null;
 const declared=(key:string)=>{const v=c.conditions[key]??(s.raw.declaredConditions as any)?.[key];return typeof v==='string'&&q.toLowerCase().includes(v.toLowerCase())?clean(v):undefined;};
 const label=(key:string)=>q.match(new RegExp('(?:^|\\n)'+key+':\\s*([^\\n]+)','i'))?.[1]?.trim();
 let type:DiscoveryType=(Object.entries(discoveryCategory).find(([k,v])=>k===c.category.toUpperCase())?.[0]??'OTHER') as DiscoveryType;
 const declaredType=label('Discovery type')??declared('discovery_type');if(declaredType&&discoveryTypes.includes(declaredType.toUpperCase() as any))type=declaredType.toUpperCase() as DiscoveryType;
 const refinements:[RegExp,DiscoveryType][]=[[/workaround|resolved.*crash/i,'WORKAROUND'],[/\bglitch\b|exploit/i,'GLITCH'],[/\bbug\b|freeze|crash/i,'BUG'],[/easter egg/i,'EASTER_EGG'],[/collectible/i,'COLLECTIBLE'],[/hidden interior|accessible interior|enter.*interior/i,'INTERIOR'],[/\broute\b|shortcut/i,'ROUTE'],[/\bheist\b/i,'HEIST'],[/\bnpc\b/i,'NPC'],[/world event/i,'WORLD_EVENT'],[/\bsecret\b/i,'SECRET']];
 if(type==='OTHER'||['bug','mission','strategy','discovery'].includes(c.category))for(const [re,t] of refinements)if(re.test(q)){type=t;break;}
 if(type==='LOCATION'&&/\bspawn(?:s|ed)?\b/i.test(q))type='SPAWN';
 if(['LOCATION','OTHER'].includes(type)&&/\b(?:interior|room|apartment|garage|building)\b/i.test(q)&&/\b(?:enter|entrance|noclip|accessible|access|door)\b/i.test(q))type='INTERIOR';
 if(type==='OTHER'){if(/safe|loot|\$|payout/i.test(q))type='MONEY';else if(/\bcar\b|vehicle|motorcycle/i.test(q))type='VEHICLE';else if(/weapon|pistol|rifle/i.test(q))type='WEAPON';else if(/\bspawn/i.test(q))type='SPAWN';else if(/mission/i.test(q))type='MISSION';else if(/\bstore\b/i.test(q))type='STORE';else if(/interior|room|noclip/i.test(q))type='INTERIOR';else type='LOCATION';}
 const loc:DiscoveryLocation={precision:'UNKNOWN'};
 const explicitLocation=declared('location')??label('Location')??(typeof s.raw.location==='string'&&q.includes(s.raw.location)?s.raw.location:undefined);
 const natural=q.match(/\b(?:supermarket|store|shop|hotel|warehouse|business)\s+(?:on|at|called|named)\s+([A-Z][\w'-]*(?:\s+[A-Z][\w'-]*){0,4})/)?.[0]??q.match(/\bbehind\s+(?:the\s+)?[A-Z][\w'-]*(?:\s+[A-Z][\w'-]*){0,4}\s+hotel/i)?.[0];
 loc.namedLocation=explicitLocation??natural;
 const street=declared('street')??q.match(/\b([A-Z][\w'-]*(?:\s+[A-Z][\w'-]*){0,2}\s+(?:Drive|Street|Road|Avenue|Boulevard))\b/)?.[1];if(street)loc.street=street;
 for(const k of ['business','district','region','landmark','interior','relativeDescription','identity','mapEntity'] as const){const v=declared(k);if(v)loc[k]=v;}
 if(!loc.business&&/\bsupermarket\b/i.test(q))loc.business=q.match(/supermarket/i)![0];
 if(!loc.interior)loc.interior=q.match(/\b(stockroom|back room|basement)\b/i)?.[1]??q.match(/\b(?:at|behind|inside|under) (?:the )?(counter)\b/i)?.[1];
 if(!loc.relativeDescription)loc.relativeDescription=q.match(/\b(?:behind|inside|under|next to)\s+(?:the\s+)?[^.!?\n,]{2,60}/i)?.[0];
 const coords=q.match(/\bCoordinates:\s*(\d+(?:\.\d+)?|-\d+(?:\.\d+)?)\s*,\s*(\d+(?:\.\d+)?|-\d+(?:\.\d+)?);\s*system:\s*([A-Z0-9_]+);\s*units:\s*(map_units|meters|degrees)/i);
 if(coords){loc.coordinates=coords[3]==='WGS84'?{coordinateSystem:coords[3],units:coords[4] as any,latitude:Number(coords[1]),longitude:Number(coords[2])}:{coordinateSystem:coords[3],units:coords[4] as any,x:Number(coords[1]),y:Number(coords[2])};}
 loc.precision=loc.coordinates||loc.identity?'EXACT':loc.street?'STREET':loc.district?'DISTRICT':loc.region?'REGION':loc.namedLocation?(/\bcounty\b/i.test(loc.namedLocation)?'REGION':/\b(?:around|near|somewhere)\b/i.test(q)&&!label('Location')?'APPROXIMATE':label('Location')||natural||/\b(?:bank|hotel|store|tower|building|club|room|garage|house|office)\b/i.test(loc.namedLocation)?'BUILDING':'APPROXIMATE'):loc.relativeDescription?'APPROXIMATE':'UNKNOWN';
 const action=declared('action')??label('Action')??q.match(/\b(?:open|loot|collect|enter|disable|rob|use|take|follow|kill|restart|buy)\s+(?:the\s+)?[^.!?\n,]{2,65}/i)?.[0]??q.match(/\b(?:found|got|spawn(?:s|ed)?|drops?|stopped working|no longer works)\b/i)?.[0];
 const game=c.conditions.game??(s.raw.game as string)??(/GTA\s*(?:VI|6)\b/i.test(s.title+' '+q)?'GTA VI':/GTA\s*(?:V|5|Online)\b/i.test(s.title+' '+q)?'GTA V':'UNKNOWN');
 const rewards=semanticRewards(q,game);
 const primaryReward=(rs:DiscoveryReward[])=>rs.find(r=>['RECEIVED','SALE_PRICE','PROFIT','BONUS'].includes(r.receipt??''))??rs.find(r=>['EXPECTED','MISSING','UNKNOWN'].includes(r.receipt??''));
 let reward:DiscoveryReward|undefined=primaryReward(rewards);
 if(!reward){const rp=q.match(/\b(\d[\d,]*)\s*RP\b/i);const item=declared('reward')??label('Reward');if(rp)reward={rewardType:'RP',amount:Number(rp[1].replaceAll(',','')),amountKind:'EXACT',currency:'non_currency',measurement:'quantity'};else if(item&&type!=='MONEY')reward={rewardType:type==='WEAPON'?'WEAPON':type==='VEHICLE'?'VEHICLE':type==='COLLECTIBLE'?'COLLECTIBLE':/unlock|access/i.test(q)?'ACCESS':'OTHER',itemReward:clean(item),amountKind:'UNKNOWN'};}
 const conditions:DiscoveryDraft['conditions']={};const names:Record<string,string>={timeOfDay:'time',weather:'weather',missionState:'mission',storyProgression:'progression',character:'character',playerCount:'players',platform:'platform',gameVersion:'version',requiredItem:'required_item',requiredVehicle:'required_vehicle',wantedLevel:'wanted_level',previousAction:'previous_action',cooldown:'cooldown',other:'context',requirements:'requirements'};
 for(const [key,name] of Object.entries(names)){const v=declared(name)??declared(key);if(v&&(key!=='timeOfDay'||/\b(?:night|day|dawn|noon|morning|evening|am|pm)\b|\d{1,2}:\d{2}/i.test(v)&&!/\b(?:january|february|march|april|may|june|july|august|september|october|november|december|20\d{2})\b/i.test(v)))conditions[key]=v;}
 conditions.requirements??=label('Requirements');conditions.platform??=label('Platform');conditions.gameVersion??=label('Version');conditions.platform??=q.match(/\b(PS5|Xbox Series X|Xbox Series S|PC)\b/i)?.[1];conditions.gameVersion??=q.match(/\b(?:version|patch|update)\s+(\d+(?:\.\d+)+)\b/i)?.[1];conditions.timeOfDay??=q.match(/\b(at noon|at night|at dawn|between \d{1,2}(?::\d{2})?\s*(?:am|pm)?\s*(?:and|–|-)\s*\d{1,2}(?::\d{2})?\s*(?:am|pm)?|at \d{1,2}:\d{2})\b/i)?.[1];
 conditions.weather??=q.match(/\b(?:during|in) (rain|fog|a storm|clear weather)\b/i)?.[1];
 const time=q.match(/\bbetween\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*(?:and|–|-)\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);let timeConditions:DiscoveryDraft['timeConditions'];
 if(time){const clock=(h:string,m:string|undefined,ap:string|undefined)=>String(ap?Number(h)%12+(ap.toLowerCase()==='pm'?12:0):Number(h)).padStart(2,'0')+':'+(m??'00');const start=clock(time[1],time[2],time[3]??time[6]),end=clock(time[4],time[5],time[6]);timeConditions={start,end,clock:/in.game/i.test(q)?'IN_GAME':/real.world|real time/i.test(q)?'REAL_WORLD':'UNKNOWN',wrapsMidnight:start>end};}
 const steps=[...q.matchAll(/(?:^|\n)\s*\d+[.)]\s*([^\n]+)/g)].map(m=>clean(m[1]));const requirements=(declared('requirements')??label('Requirements'))?.split(';').map(clean).filter(Boolean)??[];
 const repeat=q.match(/(?:^|\n)Repeatability:\s*(UNKNOWN|ONE_TIME|REPEATABLE|CONDITIONAL|PATCHED|INCONSISTENT)/i)?.[1]?.toUpperCase() as any;
 const patchReport=/no longer works|stopped working|(?:was|is|been) patched|patch removed|fixed after/i.test(q)&&!/might|maybe|could|possibly/i.test(q);
 const d:DiscoveryDraft={discoveryType:type,primaryEntity:declared('entity')??label('Entity')??c.entities.find(e=>q.toLowerCase().includes(e.toLowerCase())&&!/^(?:PS[345]|PC|Xbox.*)$/i.test(e)&&!(type==='SPAWN'&&Object.values(loc).some(v=>typeof v==='string'&&v.toLowerCase()===e.toLowerCase())))??q.match(/\b(?:stockroom safe|safe|car|vehicle|pistol|rifle|collectible|NPC)\b/i)?.[0],location:loc,action:action?clean(action):undefined,reward,conditions,requirements,timeConditions,weatherConditions:conditions.weather,missionConditions:conditions.missionState,playerCount:conditions.playerCount,platform:conditions.platform,gameVersion:conditions.gameVersion,method:declared('method')??label('Method'),steps,resetCondition:declared('reset')??label('Reset'),respawnCondition:declared('respawn')??label('Respawn'),cooldown:conditions.cooldown,risk:declared('risk')??label('Risk'),repeatable:'UNKNOWN',reportedRepeatability:repeat,reportedOccurrences:/three (?:nights|times)|3 (?:nights|times)/i.test(q)?3:undefined,patchReport,assertionKind:s.raw.observationOnly===true||s.platform==='informant'||/\b(?:I|my|we|our|found|got|observed|tested|reports?)\b/i.test(q)?'OBSERVATION':'GENERALIZED',grounding:{quote:q,method:'DETERMINISTIC_QUOTE'},game:c.conditions.game??(s.raw.game as string)??(/GTA\s*(?:VI|6)\b/i.test(s.title+' '+q)?'GTA VI':/GTA\s*(?:V|5|Online)\b/i.test(s.title+' '+q)?'GTA V':'UNKNOWN')};d.conditions=Object.fromEntries(Object.entries(d.conditions).filter(([,v])=>v!==undefined));
 const times=semanticTimes(q);d.timeEvidence=times;delete d.conditions.timeOfDay;delete d.timeConditions;const condition=times.find(t=>t.condition);if(condition)d.conditions.timeOfDay=condition.text;
 const window=condition?.text.match(/(?:between|from)\s+(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\s*(?:and|to|[-–])\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)?/i);if(window){const clock=(h:string,m:string,ap:string|undefined)=>String(ap?Number(h)%12+(ap.toLowerCase()==='pm'?12:0):Number(h)).padStart(2,'0')+':'+(m??'00');const start=clock(window[1],window[2],window[3]??window[6]),end=clock(window[4],window[5],window[6]);d.timeConditions={start,end,clock:condition.role==='IN_GAME_TIME'?'IN_GAME':condition.role==='REAL_WORLD_CLOCK_TIME'?'REAL_WORLD':'UNKNOWN',wrapsMidnight:start>end};}
 d.outcome={...reportOutcome(q),scope:{reporter:s.author,platform:d.platform??null,version:d.gameVersion??null,conditions:d.conditions}} as any;
 if(rewards.length){d.rewards=rewards;d.reward=primaryReward(rewards);if(d.reward?.eligibility){d.conditions.accountEligibility=q.match(/once per account|once per character|per account,? not character/i)![0];d.reportedRepeatability='ONE_TIME';}}
 d.primaryEntity=semanticEntity(c,q,loc);if(d.primaryEntity&&!entityRoleValid(d.primaryEntity,q,loc))d.primaryEntity=undefined;
 d.action=semanticAction(q,declared('action')??label('Action'));
 if(loc.relativeDescription)loc.relativeDescription=clean(loc.relativeDescription.split(/\s+(?:hiding|when|and then|but|while|I)\b/i)[0]);
 const locationHints=['region','district','street','business','building','interior','landmark','relativeDescription'];for(const key of locationHints){const v=declared(key);if(v){if(key==='building')loc.namedLocation=v;else loc[key]=v;}}
 if(loc.interior&&/^(?:counter|fragment|county|generic area)$/i.test(loc.interior)&&!new RegExp('(?:at|behind|inside|under) (?:the )?'+loc.interior,'i').test(q))delete loc.interior;
 if(loc.identity&&/^(?:counter|fragment|county|generic area|.+ County)$/i.test(loc.identity))delete loc.identity;
 if(loc.namedLocation&&/\bcounty\b/i.test(loc.namedLocation)&&!loc.coordinates)loc.precision='REGION';
 loc.needsDetail=!loc.coordinates&&!loc.identity&&!label('Location')&&(!loc.street&&!loc.landmark&&(!loc.namedLocation||/^(?:the )?(?:supermarket|store|shop|hotel|road|highway|alley|.+ County)$/i.test(loc.namedLocation))||/\b(?:that location|somewhere|unspecified|near a highway)\b/i.test(q));
 for(const [key,name]of Object.entries({requiredVehicle:'required_vehicle',requiredItem:'required_item',previousAction:'previous_action',missionState:'mission',weather:'weather',gameVersion:'version',platform:'platform',other:'context',requirements:'requirements',accountEligibility:'eligibility'})){const v=declared(name)??declared(key);if(v)d.conditions[key]=v;}
 d.platform=d.conditions.platform??q.match(/\b(?:PS[345]|Xbox (?:One|360|Series [XS])|PC|Console)\b/i)?.[0];if(d.platform)d.conditions.platform=d.platform;
 d.gameVersion=d.conditions.gameVersion??q.match(/\b(?:before|after|since|post[- ]|latest|new|last couple)\s*(?:the )?[^.!?\n]{0,65}\b(?:patch|update|DLC)\b(?:\s+[\d.-]+)?|\b(?:version|patch|update)\s+\d+(?:\.\d+)+|\b(?:recorded (?:in |before )?)[^.!?\n]{0,60}/i)?.[0];if(d.gameVersion)d.conditions.gameVersion=d.gameVersion;
 d.reportedPatchStatus=/\b(?:patch|update|DLC|removed|no longer|stopped working)\b/i.test(q)?/pretty (?:sure|certain)|probably|maybe|might/i.test(q)?'ALLEGED':'REPORTED':'UNKNOWN';
 const repeatText=q.match(/\b(?:once per account|once per character|(?:three|3|two|2) times(?: in a row)?|(?:did|spawned|found).{0,35}(?:in a row|a couple of times)|on repeat|never worked|did not work|didn't work|not working|doesn't spawn|haven't seen another|stopped working|used to work|no longer works)/i)?.[0];if(repeatText){const n=repeatText.match(/\b(\d+|three|two)\b/)?.[1];const count=n?({three:3,two:2}[n]??Number(n)):undefined;d.reportedRepetition={text:repeatText,count,state:/once per/i.test(repeatText)?'ONE_TIME':/not|never|stopped|no longer/i.test(repeatText)?'FAILED_REPRODUCTION':'REPEATED_OBSERVATION',support:supportedSpan(s.text,repeatText)!};if(count)d.reportedOccurrences=count;}
 const lines=[...q.matchAll(/(?:^|\n)\s*(?:\d+[.)]|\*)\s*([^\n]+)/g)].map(m=>clean(m[1]));const arrows=q.includes('->')?q.split('->').map(x=>clean(x.replace(/^\s*\d+\s*/,''))):[];const declaredSteps=Object.entries(c.conditions).filter(([k,v])=>/^step_\d+$/.test(k)&&supportedSpan(q,v)).sort((a,b)=>Number(a[0].slice(5))-Number(b[0].slice(5))).map(([k,v])=>v);if(lines.length>1)d.steps=lines;else if(arrows.length>1)d.steps=arrows;else if(declaredSteps.length)d.steps=declaredSteps;
 if(d.outcome)d.outcome.scope={reporter:s.author,platform:d.platform??null,version:d.gameVersion??null,conditions:{...d.conditions}};
 d.weatherConditions=d.conditions.weather;d.missionConditions=d.conditions.missionState;d.playerCount=d.conditions.playerCount;
 d.numericEvidence=numericRoles(q,d.game);
 const received=d.rewards?.find(r=>r.receipt==='RECEIVED'),expected=d.rewards?.find(r=>['EXPECTED','COMPARISON','BASELINE'].includes(r.receipt??''));
 if(received?.amount!==undefined&&expected?.amount!==undefined&&received.currency===expected.currency&&received.amount<expected.amount&&/only got|expected|should have|supposed/i.test(q)&&d.outcome){d.outcome.state='PARTIAL';d.outcome.qualification='Received less than the expected/comparison reward; not two received payouts';}
 const offset=s.text.toLowerCase().indexOf(q.toLowerCase());const rebase=(e:any)=>e?{...e,start:e.start+offset,end:e.end+offset}:e;
 for(const r of d.rewards??[]){r.support=rebase(r.support);r.relationship=rebase(r.relationship);r.eligibilitySupport=rebase(r.eligibilitySupport);}for(const t of times)t.support=rebase(t.support);if(d.outcome)d.outcome.evidence=d.outcome.evidence.map(rebase).filter(Boolean);
 for(const n of d.numericEvidence){n.support=rebase(n.support);n.relationship=rebase(n.relationship);n.token=rebase(n.token);}
 projectQualifiedProposition(d,c,s);bindDiscoveryPropositions(d,c,s);attachFieldSupport(d,s.text);return validateDiscoveryDraft(d);

}
export function discoveryCandidate(c:Candidate,s:SourceItem):Candidate{
 c=groundedDiscoveryCandidate(qualifyWholeReport(c,s));const d=extractDiscovery(c,s);if(!d)return c;const q=c.quote;
 // Do not make a single reported event a universal rule, regardless of model wording.
 const observation=d.assertionKind==='OBSERVATION';const scopedClaim=d.proposition?.text??c.claim;let claim=observation&&!/\b(?:i|my|we|our|player.+report)\b/i.test(scopedClaim)?'A player reports: '+scopedClaim:scopedClaim;
 if(s.platform==='twitch'&&s.raw.observationOnly===true)claim='Chat participants report: '+claim.replace(/^Chat participants report:\s*/i,'');
 const scope:Record<string,string>={};if(d.location.namedLocation)scope.discovery_location=d.location.namedLocation;if(d.location.street)scope.discovery_street=d.location.street;if(d.conditions.timeOfDay)scope.discovery_time=d.conditions.timeOfDay;if(d.platform)scope.discovery_platform=d.platform;if(d.gameVersion)scope.discovery_version=d.gameVersion;for(const [i,q]of (d.proposition?.qualifiers??[]).entries())scope['discovery_qualification_'+i]=q.support.quote;
 let values=c.values;const rewards=d.rewards??(d.reward?[d.reward]:[]);if(rewards.length){values=rewards.flatMap((r,index)=>{const basis=r.eligibility==='ONCE_PER_ACCOUNT'?'once_per_account':r.eligibility==='ONCE_PER_CHARACTER'?'once_per_character':r.basis==='PER_HOUR'||r.measurement==='per_hour'?'hour':r.basis==='PER_ACTIVITY'||r.measurement==='per_successful_loot'?'per_activity':r.basis==='SESSION_TOTAL'?r.measurement??'session_total':r.basis==='DAY_TOTAL'?'day':r.basis==='CUMULATIVE'?'cumulative':'not_established';const numeric=(name:string,value:number)=>({name,value,unit:r.currency??'unknown',currency:r.currency??'unknown',measurement:['COST','INVESTMENT'].includes(r.receipt??'')?'investment':r.receipt==='MISSING'?'expected_reward':['EXPECTED','COMPARISON','BASELINE','ADVERTISED','UNKNOWN'].includes(r.receipt??'')?(r.receipt??'unknown').toLowerCase():r.currency==='non_currency'?'quantity':basis==='hour'?'earnings_rate':'payout',timeBasis:basis,activityBasis:r.activityBasis??'not_established',conditions:{...(r.eligibility?{eligibility:r.eligibility}:{}),...(r.receipt?{receipt:r.receipt}:{}),...(r.amountKind==='UNKNOWN'?{qualifier:'lower_bound'}:{})}});return r.amount!==undefined?[numeric('reward_'+index,r.amount)]:r.minimum!==undefined?[numeric('reward_minimum_'+index,r.minimum),...(r.maximum!==undefined?[numeric('reward_maximum_'+index,r.maximum)]:[])]:[];});}

 const classification=(s.raw.discoveryConfirmation as any)?.classification;d.confirmationClass=classification;const stance=['PARTIAL_CONFIRMATION','COULD_NOT_REPRODUCE','DIFFERENT_CONDITIONS'].includes(classification)?'uncertain':c.stance;return {...c,category:discoveryCategory[d.discoveryType],claim,stance,values,conditions:{...c.conditions,...scope},discovery:d};
}
