import {validatePropositionBindings} from './discovery-binding.ts';
import {extractDiscovery} from './discovery-extraction.ts';
import {discoveryCategory} from './discovery-model.ts';
import {status as claimStatus} from './claim-status.ts';
import {createHash} from 'node:crypto';
import type {Repository,Candidate,Claim,SourceItem} from './model.ts';
import type {ActionableDiscovery,DiscoveryDraft,DiscoveryType,Coordinates,DiscoveryLocation} from './discovery-model.ts';
import {validateCoordinates} from './discovery-model.ts';
import {sourceFamily,sourceNetwork} from './independence.ts';
import {assertionKind,DeterministicSemanticSupport} from './feed-quality.ts';
const norm=(s:unknown)=>String(s??'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const stable=(o:any):string=>JSON.stringify(o&&typeof o==='object'?Array.isArray(o)?o.map(x=>JSON.parse(stable(x))):Object.fromEntries(Object.keys(o).sort().filter(k=>o[k]!==undefined).map(k=>[k,JSON.parse(stable(o[k]))])):o??null);
const rewardIdentity=(r:any)=>r?Object.fromEntries(Object.entries(r).filter(([k])=>!['support','eligibilitySupport','relationship','propositionId','activityRelationship'].includes(k))):r;
const applicableConditions=(d:DiscoveryDraft)=>{const scope=(d.proposition?.qualifiers??[]).filter(q=>!['VERSION','OUTCOME','REPEATABILITY'].includes(q.kind)).map(q=>[q.kind,norm(q.support.quote)]).sort((a,b)=>stable(a).localeCompare(stable(b)));return stable({conditions:Object.fromEntries(Object.entries(d.conditions).filter(([k])=>k!=='gameVersion'&&!k.startsWith('materialQualifier_'))),scope});};
const hash=(o:any)=>createHash('sha256').update(stable(o)).digest('hex').slice(0,24);
export function locationKey(l:DiscoveryLocation){if(l.coordinates)return stable(l.coordinates);if(l.identity)return norm(l.identity);return stable(Object.fromEntries(['namedLocation','business','street','district','region','landmark','interior','relativeDescription'].map(k=>[k,norm(l[k])]).filter(([,v])=>v)));}
export function resolvedLocation(l:DiscoveryLocation){return l.needsDetail!==true&&!!(l.coordinates||l.identity||l.street||l.landmark||(l.namedLocation&&!/^(?:the )?(?:supermarket|store|shop|hotel|this street|somewhere|unknown)$/i.test(l.namedLocation)));}
export function discoveryRelation(a:DiscoveryDraft,b:DiscoveryDraft):{kind:'SAME'|'RELATED'|'AMBIGUOUS'|'DIFFERENT';reason:string}{
 a=validatePropositionBindings(structuredClone(a));b=validatePropositionBindings(structuredClone(b));
 if(norm(a.game)!==norm(b.game)||a.discoveryType!==b.discoveryType)return {kind:'DIFFERENT',reason:'type_entity_or_game'};
 if(a.primaryEntity&&b.primaryEntity&&norm(a.primaryEntity)!==norm(b.primaryEntity)&&!['safe','car','vehicle','weapon','npc','item','collectible'].includes(norm(a.primaryEntity))&&!['safe','car','vehicle','weapon','npc','item','collectible'].includes(norm(b.primaryEntity)))return {kind:'DIFFERENT',reason:'distinct_entity'};
 if(!a.primaryEntity||!b.primaryEntity||['safe','car','vehicle','weapon','npc','item','collectible'].includes(norm(a.primaryEntity))||['safe','car','vehicle','weapon','npc','item','collectible'].includes(norm(b.primaryEntity)))return {kind:'AMBIGUOUS',reason:'unresolved_entity'};
 if(a.location.coordinates&&b.location.coordinates&&a.location.coordinates.coordinateSystem!==b.location.coordinates.coordinateSystem)return {kind:'DIFFERENT',reason:'coordinate_system'};
 if(a.confirmationClass==='DIFFERENT_CONDITIONS'||b.confirmationClass==='DIFFERENT_CONDITIONS')return {kind:'RELATED',reason:'different_confirmation_context_requires_review'};
 if(!resolvedLocation(a.location)||!resolvedLocation(b.location))return {kind:'AMBIGUOUS',reason:'unresolved_location'};
 if(locationKey(a.location)!==locationKey(b.location))return {kind:'DIFFERENT',reason:'distinct_location'};
 if(norm(a.action)!==norm(b.action)||norm(a.method)!==norm(b.method)||stable(a.steps)!==stable(b.steps))return {kind:'RELATED',reason:'different_action_or_method'};
 if(stable(a.conditions)!==stable(b.conditions)||stable(a.timeConditions)!==stable(b.timeConditions)||stable(a.requirements)!==stable(b.requirements)||norm(a.cooldown)!==norm(b.cooldown)||norm(a.resetCondition)!==norm(b.resetCondition)||norm(a.respawnCondition)!==norm(b.respawnCondition))return {kind:'RELATED',reason:'different_or_missing_conditions'};
 if(a.reward?.basis!==b.reward?.basis||a.reward?.eligibility!==b.reward?.eligibility||a.reward?.frequency!==b.reward?.frequency||a.reward?.receipt!==b.reward?.receipt)return {kind:'RELATED',reason:'different_reward_eligibility_or_receipt'};
 if(a.outcome&&b.outcome&&a.outcome.state!==b.outcome.state)return {kind:'RELATED',reason:'different_reported_outcome_requires_scope_review'};
 if(a.reward?.rewardType!==b.reward?.rewardType||a.reward?.currency!==b.reward?.currency||a.reward?.measurement!==b.reward?.measurement||norm(a.reward?.itemReward)!==norm(b.reward?.itemReward))return {kind:'RELATED',reason:'different_reward_basis'};
 if(a.binding?.state==='INCOMPLETE_NEEDS_REVIEW'||b.binding?.state==='INCOMPLETE_NEEDS_REVIEW')return {kind:'AMBIGUOUS',reason:'unresolved_proposition_binding'};
 return {kind:'SAME',reason:'same_scoped_discovery; amounts retained per observation'};
}
export function guardDiscoveryMatch(c:Candidate,claims:Claim[],decision:any){
 if(!c.discovery)return decision;
 validatePropositionBindings(c.discovery);
 if(c.discovery.proposition?.state==='INCOMPLETE_NEEDS_REVIEW')return {kind:'ambiguous',score:0,alternatives:[],reason:'Discovery proposition contains unresolved material qualification'};
 const similar=claims.filter(x=>x.discovery&&discoveryRelation(c.discovery!,x.discovery).kind!=='DIFFERENT');
 if(decision.kind==='merge'){const target=claims.find(x=>x.id===decision.claimId);const relation=target?.discovery?discoveryRelation(c.discovery,target.discovery):{kind:'AMBIGUOUS',reason:'target_has_no_discovery_scope'};if(relation.kind!=='SAME')return {kind:'ambiguous',score:decision.score,alternatives:[{id:decision.claimId,score:decision.score}],reason:'Discovery scope prevents merge: '+relation.reason};}
 if(decision.kind==='new'&&similar.some(x=>discoveryRelation(c.discovery!,x.discovery!).kind==='AMBIGUOUS'))return {kind:'ambiguous',score:0,alternatives:similar.map(x=>({id:x.id,score:0})),reason:'Discovery location identity needs resolution; separate report retained'};
 return decision;
}
const requiredByType:Partial<Record<DiscoveryType,string[]>>={MONEY:['location','action','reward','conditions','repeatability'],VEHICLE:['entity','location','conditions','repeatability'],SPAWN:['entity','location','conditions','repeatability'],WEAPON:['entity','location','action','requirements'],ROUTE:['location','action','steps','outcome'],MISSION:['entity','action','steps','requirements'],HEIST:['entity','action','steps','requirements'],BUG:['action','platform','version','conditions'],GLITCH:['action','platform','version','conditions'],WORKAROUND:['action','platform','version','steps'],BUSINESS:['entity','location','action','reward'],STORE:['location','action','reward']};
export function assessDiscovery(d:DiscoveryDraft,at:string,lastCheckedAt:string|null=null){
 validatePropositionBindings(d);
 const dimensions={location:resolvedLocation(d.location),entity:!!d.primaryEntity,action:!!d.action&&!/^(?:found|got|spawn(?:s|ed)?|drops?|stopped working|no longer works)$/i.test(d.action)||d.steps.length>0,reward:!!d.reward&&(d.reward.amount!==undefined||d.reward.minimum!==undefined||!!d.reward.itemReward),outcome:!!d.outcome&&d.outcome.state!=='UNKNOWN'||!!d.reward?.outcome||!!d.reward?.itemReward,conditions:Object.values(d.conditions).some(Boolean),repeatability:d.repeatable!=='UNKNOWN',steps:d.steps.length>0,platform:!!d.platform,version:!!d.gameVersion,requirements:d.requirements.length>0||d.conditions.requirements==='none',timeliness:!!lastCheckedAt&&Date.parse(at)-Date.parse(lastCheckedAt)<86400000};
 const weights={location:20,action:20,reward:20,conditions:10,repeatability:10,steps:10,timeliness:10};const actionability={score:Object.entries(weights).reduce((n,[k,w])=>n+(dimensions[k]?w:0),0),dimensions,meaning:'Structured usefulness only; never alters truth confidence or verification'};
 const required=requiredByType[d.discoveryType]??['location','action','conditions'];const missing=required.filter(k=>!dimensions[k]&&!(k==='repeatability'&&(d.reportedRepetition||d.reportedRepeatability==='ONE_TIME')));
 const completeness={score:Math.round(100*(required.length-missing.length)/required.length),missingFields:missing,state:missing.includes('location')?'NEEDS_LOCATION_DETAIL':missing.length?'INCOMPLETE':'COMPLETE'};
 if(d.proposition?.state==='INCOMPLETE_NEEDS_REVIEW'){completeness.state='NEEDS_REVIEW';completeness.missingFields.push('materialQualifiers');actionability.score=0;}
 const questions:Record<string,string>={location:'Which exact location or business, and where inside it?',entity:'Which vehicle, item or activity did you find?',action:'What did you do and what happened?',reward:'What amount or item did you receive?',conditions:'What time, weather or mission conditions applied?',repeatability:'Have you reproduced it more than once?',steps:'Which steps did you actually follow?',platform:'What platform were you playing on?',version:'Which game update or version was this?',requirements:'What was required, or did you test it without prerequisites?',outcome:'What result did the route or method produce?'};
 const priority=['location',...(['BUG','GLITCH','WORKAROUND'].includes(d.discoveryType)?['platform','version']:[]),'action','reward','conditions','repeatability','platform','version','steps','entity','requirements','outcome'].filter((v,i,a)=>a.indexOf(v)===i);const fields=priority.filter(k=>missing.includes(k)||k==='location'&&d.location.needsDetail===true||k==='platform'&&!dimensions.platform).slice(0,3);
 return {actionability,completeness,followUps:fields.map(field=>({field,question:questions[field]}))};
}
export const freshnessHours:Partial<Record<DiscoveryType,number>>={GLITCH:24,BUG:72,WORKAROUND:72,MONEY:72,SPAWN:168,VEHICLE:168,ROUTE:336,BUSINESS:168,INTERIOR:2160,LOCATION:2160,EASTER_EGG:4320,SECRET:2160};
export function discoveryFreshness(d:DiscoveryDraft,checkedAt:string|null,at:string,patched=false){const maxAgeHours=freshnessHours[d.discoveryType]??720;return {state:patched?'OUTDATED':!checkedAt?'UNKNOWN':Date.parse(at)-Date.parse(checkedAt)>maxAgeHours*3600000?'NEEDS_REVALIDATION':'CURRENT',maxAgeHours,checkedAt} as ActionableDiscovery['freshness'];}
function independentObservations(observations:ActionableDiscovery['observations'],sources:SourceItem[]){const families=new Set<string>(),authors=new Set<string>(),networks=new Set<string>(),texts=new Set<string>();return observations.filter(o=>{const s=sources.find(s=>s.id===o.sourceId);if(!o.eligible||!s||s.copiedFrom)return false;const family=sourceFamily(s,sources),network=sourceNetwork(s),text=norm(s.text);if(families.has(family)||s.author&&authors.has(s.author)||network&&networks.has(network)||texts.has(text))return false;families.add(family);if(s.author)authors.add(s.author);if(network)networks.add(network);texts.add(text);return true;});}
export function refreshDiscoveries(repo:Repository,at=new Date().toISOString()){
 const sources=repo.sources(),evidence=repo.evidence(),claims=repo.claims(),checker=new DeterministicSemanticSupport();const records:ActionableDiscovery[]=[];
 for(const c of claims.filter(c=>c.discovery)){
  const old=repo.communityRecords('discoveries').find(d=>d.claimId===c.id);const linked=evidence.filter(e=>e.claimId===c.id&&e.candidate.discovery);
  const observations=linked.map(e=>{const s=sources.find(s=>s.id===e.sourceId)!;const seeded=s.platform==='informant'&&repo.communityRecords('profiles').some(p=>p.id===s.author&&p.accountOrigin==='SEEDED');return {evidenceId:e.id,sourceId:e.sourceId,observedAt:e.candidate.temporal?.observedAt??s.timestamp,stance:e.stance,dimensions:e.candidate.discovery!,independenceFamily:sourceFamily(s,sources),author:s.author,eligible:!seeded&&!s.raw.informantSuppressed&&!s.raw.discoverySuppressed&&(!s.raw.synthetic||repo.setting('discoveryTestOnly')===true)&&checker.check({...c,claim:e.candidate.claim,conditions:e.candidate.conditions,values:e.candidate.values},e,s).result==='supported'};});
  if(observations.some(o=>sources.find(s=>s.id===o.sourceId)?.raw.discoveryFixture)&&(!repo.testIsolation||repo.setting('discoveryTestOnly')!==true))throw Error('Discovery fixtures cannot enter operational repository');
  const ind=independentObservations(observations,sources),positive=ind.filter(o=>o.stance==='supports'),d=c.discovery!;
  const compatiblePositive=positive.filter(o=>stable(rewardIdentity(o.dimensions.reward))===stable(rewardIdentity(c.discovery!.reward)));const lastConfirmedAt=compatiblePositive.length>=2?compatiblePositive.map(o=>o.observedAt).sort().at(-1)!:null;const lastCheckedAt=ind.map(o=>o.observedAt).sort().at(-1)??null;
  const variants=[...new Map(observations.filter(o=>o.eligible&&o.dimensions.reward).map(o=>[stable(rewardIdentity(o.dimensions.reward)),o.dimensions.reward!])).values()];
  const inconsistent=positive.length>=2&&new Set(positive.map(o=>stable(rewardIdentity(o.dimensions.reward)))).size>1;
  const repeatReports=positive.map(o=>o.dimensions.reportedRepeatability).filter(v=>v&&['REPEATABLE','ONE_TIME','CONDITIONAL'].includes(v));const reportedState=repeatReports.length>=2&&new Set(repeatReports).size===1?repeatReports[0]:undefined;const base={...d,repeatable:inconsistent?'INCONSISTENT' as const:reportedState??d.repeatable};
  const record:ActionableDiscovery={...base,discoveryId:'discovery_'+hash(c.id),claimId:c.id,evidenceIds:linked.map(e=>e.id),sourceIds:[...new Set(linked.map(e=>e.sourceId))],discoveredBy:sources.find(s=>s.id===linked[0]?.sourceId)?.author??null,firstObservedAt:old?.firstObservedAt??observations.map(o=>o.observedAt).sort()[0]??c.firstDetected,lastConfirmedAt,lastCheckedAt,status:claimStatus(c),truthStatus:c.status,confidence:c.confidence,observations,archived:!linked.length,testOnly:observations.some(o=>sources.find(s=>s.id===o.sourceId)?.raw.discoveryFixture===true),...assessDiscovery(base,at,lastCheckedAt),freshness:discoveryFreshness(base,positive.map(o=>o.observedAt).sort().at(-1)??null,at),patchState:ind.some(o=>o.dimensions.patchReport)?'REPORTED':'NONE',related:[],supersededBy:[],rewardVariants:variants,possibleTimeConditions:[],generalizationEstablished:d.proposition?.state!=='INCOMPLETE_NEEDS_REVIEW'&&assertionKind(c)==='GENERALIZED'&&c.status==='VERIFIED'&&c.publication?.state==='PUBLISHABLE'};
  if(old){const history=[...(old.observations??[]),...observations];repo.saveCommunityRecord('discoveryHistory',record.discoveryId,{id:record.discoveryId,observations:[...new Map(history.map(o=>[o.evidenceId,o])).values()]});}
  records.push(record);
 }
 for(const d of records){
  const others=records.filter(o=>o.discoveryId!==d.discoveryId);for(const o of others){const r=discoveryRelation(d,o);if(r.kind==='RELATED'||r.kind==='AMBIGUOUS')d.related.push({discoveryId:o.discoveryId,reason:r.reason});}
  // Patch reports link a method across versions only when entity/location/action and platform agree.
  const patches=others.filter(o=>o.patchReport&&o.discoveryType===d.discoveryType&&norm(o.game)===norm(d.game)&&norm(o.primaryEntity)===norm(d.primaryEntity)&&resolvedLocation(d.location)&&locationKey(d.location)===locationKey(o.location)&&norm(o.action)===norm(d.action)&&norm(o.method)===norm(d.method)&&stable(o.requirements)===stable(d.requirements)&&norm(o.platform)===norm(d.platform)&&applicableConditions(o)===applicableConditions(d)&&stable(o.timeConditions)===stable(d.timeConditions)&&o.firstObservedAt>d.firstObservedAt);
  const reportObservations=[...d.observations.filter(o=>o.dimensions.patchReport),...patches.flatMap(o=>o.observations.filter(x=>x.dimensions.patchReport))];
  const latestVersion=reportObservations.toSorted((a,b)=>b.observedAt.localeCompare(a.observedAt))[0]?.dimensions.gameVersion;
  const independent=independentObservations(reportObservations.filter(o=>o.dimensions.gameVersion===latestVersion&&o.stance!=='uncertain'&&o.dimensions.reportedPatchStatus!=='ALLEGED'),sources);
  if(independent.length>=2){d.patchState='PATCHED';d.repeatable='PATCHED';d.status='OUTDATED';d.supersededBy=patches.map(o=>o.discoveryId);d.freshness=discoveryFreshness(d,d.lastCheckedAt,at,true);}else if(reportObservations.length)d.patchState='REPORTED';
  const newer=others.filter(o=>!o.patchReport&&o.discoveryType===d.discoveryType&&norm(o.game)===norm(d.game)&&norm(o.primaryEntity)===norm(d.primaryEntity)&&resolvedLocation(d.location)&&locationKey(d.location)===locationKey(o.location)&&norm(o.action)===norm(d.action)&&norm(o.method)===norm(d.method)&&stable(o.requirements)===stable(d.requirements)&&norm(o.platform)===norm(d.platform)&&applicableConditions(o)===applicableConditions(d)&&stable(o.timeConditions)===stable(d.timeConditions)&&o.gameVersion&&d.gameVersion&&o.gameVersion!==d.gameVersion&&o.firstObservedAt>d.firstObservedAt&&o.reward?.rewardType===d.reward?.rewardType&&o.reward?.currency===d.reward?.currency&&o.reward?.measurement===d.reward?.measurement);
  const newerConfirmed=newer.filter(o=>independentObservations(o.observations.filter(x=>x.stance==='supports'),sources).length>=2&&o.rewardVariants.length===1);
  if(newerConfirmed.length){d.supersededBy=[...new Set([...d.supersededBy,...newerConfirmed.map(o=>o.discoveryId)])];d.status='OUTDATED';d.freshness={...d.freshness,state:'OUTDATED'};}
  const timeReports=others.filter(o=>o.discoveryType===d.discoveryType&&norm(o.primaryEntity)===norm(d.primaryEntity)&&locationKey(o.location)===locationKey(d.location)&&norm(o.platform)===norm(d.platform)&&norm(o.gameVersion)===norm(d.gameVersion));
  const observedTimes=[...d.observations,...timeReports.flatMap(o=>o.observations)].filter(o=>o.eligible&&o.stance==='supports'&&o.dimensions.conditions.timeOfDay).map(o=>o.dimensions.conditions.timeOfDay!);d.possibleTimeConditions=[...new Set(observedTimes)];
  repo.saveCommunityRecord('discoveries',d.discoveryId,{...d,id:d.discoveryId});
 }
 // Retain derivatives whose source claim was replaced/removed, but never query them as current.
 for(const old of repo.communityRecords('discoveries'))if(!claims.some(c=>c.id===old.claimId))repo.saveCommunityRecord('discoveries',old.discoveryId,{...old,archived:true,status:'OUTDATED'});
 return records;
}
export type DiscoveryQuery={type?:DiscoveryType;status?:string;platform?:string;district?:string;region?:string;location?:string;entity?:string;repeatable?:boolean;noPrerequisite?:boolean;updatedSince?:string;patched?:boolean;includeHistorical?:boolean;near?:{coordinates:Coordinates;radius:number};testOnly?:boolean};
export function coordinateDistance(a:Coordinates,b:Coordinates){validateCoordinates(a);validateCoordinates(b);if(a.coordinateSystem!==b.coordinateSystem||a.units!==b.units)throw Error('Cannot mix coordinate systems or units');if(a.coordinateSystem==='WGS84'){const rad=(n:number)=>n*Math.PI/180,dl=rad(b.latitude!-a.latitude!),dn=rad(b.longitude!-a.longitude!),h=Math.sin(dl/2)**2+Math.cos(rad(a.latitude!))*Math.cos(rad(b.latitude!))*Math.sin(dn/2)**2;return 6371000*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}return Math.hypot(b.x!-a.x!,b.y!-a.y!);}
export class DiscoveryService{
 repo:Repository;constructor(repo:Repository){this.repo=repo;}
 list(query:DiscoveryQuery={}){if(query.near){validateCoordinates(query.near.coordinates);if(!Number.isFinite(query.near.radius)||query.near.radius<0)throw Error('Invalid proximity radius');}return (this.repo.communityRecords('discoveries') as ActionableDiscovery[]).filter(d=>!d.archived&&(query.testOnly===true?d.testOnly:!d.testOnly)&&(!query.type||d.discoveryType===query.type)&&(!query.status||d.status===query.status)&&(!query.platform||norm(d.platform)===norm(query.platform))&&(!query.district||norm(d.location.district)===norm(query.district))&&(!query.region||norm(d.location.region)===norm(query.region))&&(!query.location||norm(locationKey(d.location)).includes(norm(query.location)))&&(!query.entity||norm(d.primaryEntity)===norm(query.entity))&&(!query.repeatable||d.repeatable==='REPEATABLE'||d.repeatable==='CONDITIONAL')&&(!query.noPrerequisite||d.conditions.requirements==='none')&&(!query.updatedSince||!!d.lastCheckedAt&&d.lastCheckedAt>=query.updatedSince)&&(query.patched===undefined||query.patched===(d.patchState==='PATCHED'))&&(query.includeHistorical||query.patched===true||d.status!=='OUTDATED'&&d.freshness.state!=='OUTDATED')&&(!query.near||!!d.location.coordinates&&d.location.coordinates.coordinateSystem===query.near.coordinates.coordinateSystem&&d.location.coordinates.units===query.near.coordinates.units&&coordinateDistance(d.location.coordinates,query.near.coordinates)<=query.near.radius));}
 forClaim(claimId:string){return this.repo.communityRecords('discoveries').find(d=>d.claimId===claimId&&!d.archived&&!d.testOnly)??null;}
 feedMetadata(claimId:string){const d=this.forClaim(claimId);return d?{discoveryId:d.discoveryId,discoveryType:d.discoveryType,location:d.location,reward:d.reward,rewardVariants:d.rewardVariants,status:d.status,truthStatus:d.truthStatus,confidence:d.confidence,assertionKind:d.assertionKind,repeatable:d.repeatable,lastConfirmedAt:d.lastConfirmedAt,freshness:d.freshness,actionability:d.actionability,completeness:d.completeness,patchState:d.patchState,steps:d.steps,conditions:d.conditions}:null;}
 askRecords(query:DiscoveryQuery={}){return this.list(query).map(d=>{const claim=this.repo.claims().find(c=>c.id===d.claimId)!;return {discovery:d,claim:claim.claim,status:d.status,truthStatus:claim.status,confidence:claim.confidence,authority:claim.breakdown.authority??null,freshness:d.freshness,currentness:d.status==='OUTDATED'?'OUTDATED':d.freshness.state,evidence:this.repo.evidence().filter(e=>d.evidenceIds.includes(e.id)),contradictions:this.repo.evidence().filter(e=>e.claimId===d.claimId&&e.stance==='contradicts'),historical:d.status==='OUTDATED',publication:claim.publication};});}
}
export function discoveryConfirmation(d:DiscoveryDraft,input:any){
 if(input.discoveryContext!==undefined&&(!input.discoveryContext||typeof input.discoveryContext!=='object'||Array.isArray(input.discoveryContext)))throw Error('Invalid discovery confirmation context');
 const context=input.discoveryContext??{};if(Object.keys(context).some(k=>!['location','reward','conditions','platform','version','sameLocation','sameReward','sameConditions'].includes(k))||Object.values(context).some(v=>!['string','boolean'].includes(typeof v)||typeof v==='string'&&v.length>500))throw Error('Invalid discovery confirmation dimensions');
 let observed:DiscoveryDraft|null=null;
 if(typeof input.report==='string'&&input.report.trim()){
  const source:SourceItem={id:'confirmation-preview',sourceId:'confirmation-preview',platform:'informant',url:'https://vice-wire.invalid/confirmation-preview',author:null,title:d.game,text:input.report,timestamp:input.observedAt??new Date().toISOString(),ingestedAt:new Date().toISOString(),engagement:{score:0},independenceKey:'confirmation-preview',itemType:'comment',raw:{game:d.game,declaredConditions:input.conditions??{}}};
  observed=extractDiscovery({category:discoveryCategory[d.discoveryType],claim:input.report,predicate:'reported_confirmation',entities:[d.primaryEntity??d.discoveryType],conditions:{...input.conditions,game:d.game},values:[],stance:'supports',quote:input.report},source);
 }
 const observedDifferent=observed&&(observed.platform&&d.platform&&norm(observed.platform)!==norm(d.platform)||observed.gameVersion&&d.gameVersion&&norm(observed.gameVersion)!==norm(d.gameVersion)||resolvedLocation(observed.location)&&resolvedLocation(d.location)&&locationKey(observed.location)!==locationKey(d.location)||Object.entries(observed.conditions).some(([k,v])=>d.conditions[k]&&norm(v)!==norm(d.conditions[k])));
 const rewardMismatch=observed?.reward&&d.reward&&stable(rewardIdentity(observed.reward))!==stable(rewardIdentity(d.reward));
 const platform=input.platform??context.platform,version=input.version??context.version;const conditions=input.conditions??{};
 const different=observedDifferent||platform&&d.platform&&norm(platform)!==norm(d.platform)||version&&d.gameVersion&&norm(version)!==norm(d.gameVersion)||Object.entries(conditions).some(([k,v])=>d.conditions[k]&&norm(v)!==norm(d.conditions[k]))||context.sameConditions===false||context.sameLocation===false||context.location&&resolvedLocation(d.location)&&!norm(locationKey(d.location)).includes(norm(context.location));
 const classification=different?'DIFFERENT_CONDITIONS':input.result==='could_not_confirm'?'COULD_NOT_REPRODUCE':input.result==='did_not_work'?'CONTRADICTING_OBSERVATION':context.sameReward===false||rewardMismatch?'PARTIAL_CONFIRMATION':context.sameLocation===true&&context.sameReward===true&&context.sameConditions===true?'FULL_CONFIRMATION':'PARTIAL_CONFIRMATION';
 return {classification,context,observed,countsAsTruth:false,requiresGroundedExtraction:true};
}
