import {validatePropositionBindings} from './discovery-binding.ts';
import type {GroundedProposition,PropositionFieldBinding} from './discovery-binding.ts';
import {materialQualifiers} from './discovery-projection.ts';
import {numericRoles} from './discovery-numeric.ts';
// Discovery types refine the existing IntelClaim category, rather than replacing it.
export const discoveryTypes=['MONEY','VEHICLE','WEAPON','LOCATION','INTERIOR','SECRET','EASTER_EGG','COLLECTIBLE','NPC','MISSION','HEIST','ROUTE','BUSINESS','STORE','ACTIVITY','BUG','GLITCH','WORKAROUND','STRATEGY','SPAWN','ITEM','WORLD_EVENT','MECHANIC','OTHER'] as const;
export type DiscoveryType=typeof discoveryTypes[number];
export const discoveryCategory:Record<DiscoveryType,string>={MONEY:'money',VEHICLE:'vehicle',WEAPON:'weapon',LOCATION:'location',INTERIOR:'location',SECRET:'discovery',EASTER_EGG:'easter_egg',COLLECTIBLE:'discovery',NPC:'discovery',MISSION:'mission',HEIST:'mission',ROUTE:'strategy',BUSINESS:'business',STORE:'business',ACTIVITY:'mission',BUG:'bug',GLITCH:'bug',WORKAROUND:'workaround',STRATEGY:'strategy',SPAWN:'location',ITEM:'discovery',WORLD_EVENT:'discovery',MECHANIC:'discovery',OTHER:'other'};
export type FieldSupport={source:'PRIMARY';quote:string;start:number;end:number};
export type MonetaryRole='RECEIVED'|'EXPECTED'|'ADVERTISED'|'BASELINE'|'BONUS'|'COST'|'INVESTMENT'|'SALE_PRICE'|'PROFIT'|'MISSING'|'COMPARISON'|'UNKNOWN';
export type NumericRole='MONEY'|'DURATION'|'TIME_OF_DAY'|'VIDEO_OFFSET'|'COUNT'|'PERCENTAGE'|'DISTANCE'|'QUANTITY'|'LEVEL'|'VERSION'|'DATE'|'COORDINATE'|'UNKNOWN';
export type NumericEvidence={role:NumericRole;expression:string;value?:number;maximum?:number;unit?:string;amountKind:'EXACT'|'APPROXIMATE'|'RANGE'|'LOWER_BOUND';currency?:DiscoveryReward['currency'];moneyRole?:MonetaryRole;support:FieldSupport;token?:FieldSupport;relationship:FieldSupport;warning?:string};
export type MaterialQualifier={kind:'ELIGIBILITY'|'EXCLUSION'|'PLATFORM'|'VERSION'|'TIME'|'LOCATION'|'REPEATABILITY'|'REWARD_BASIS'|'OUTCOME'|'METHOD';support:FieldSupport;scope:'PROPOSITION'|'UNRESOLVED';projectedField?:string};
export type QualifiedDiscoveryProposition={text:string;subject?:string;action?:string;outcome:OutcomeState;qualifiers:MaterialQualifier[];support:FieldSupport;state:'COMPLETE'|'INCOMPLETE_NEEDS_REVIEW';missingQualifiers:string[];reviewReasons:string[]};
export type OutcomeState='SUCCESS'|'FAILURE'|'PARTIAL'|'INCONSISTENT'|'NOT_TESTED'|'UNKNOWN';
export type Precision='EXACT'|'BUILDING'|'STREET'|'DISTRICT'|'REGION'|'APPROXIMATE'|'UNKNOWN';
export type Coordinates={coordinateSystem:string;units:'degrees'|'map_units'|'meters';x?:number;y?:number;latitude?:number;longitude?:number};
export type DiscoveryLocation={identity?:string;namedLocation?:string;business?:string;street?:string;district?:string;region?:string;landmark?:string;interior?:string;relativeDescription?:string;mapEntity?:string;coordinates?:Coordinates;precision:Precision;needsDetail?:boolean};
export type DiscoveryReward={rewardType:'MONEY'|'RP'|'VEHICLE'|'WEAPON'|'ITEM'|'COLLECTIBLE'|'ACCESS'|'OTHER';amount?:number;minimum?:number;maximum?:number;amountKind:'EXACT'|'APPROXIMATE'|'RANGE'|'UNKNOWN';currency?:'GTA$'|'USD'|'EUR'|'GBP'|'unknown'|'non_currency';itemReward?:string;measurement?:string;outcome?:string;basis?:'ACCOUNT_BONUS'|'CHARACTER_BONUS'|'PER_HOUR'|'SESSION_TOTAL'|'DAY_TOTAL'|'PER_ACTIVITY'|'CUMULATIVE'|'UNKNOWN';eligibility?:'ONCE_PER_ACCOUNT'|'ONCE_PER_CHARACTER';frequency?:'ONE_TIME';reportedRepeatability?:Repeatability;receipt?:MonetaryRole;relationship?:FieldSupport;support?:FieldSupport;eligibilitySupport?:FieldSupport;propositionId?:string;activityBasis?:string;activityRelationship?:FieldSupport};
export type Repeatability='UNKNOWN'|'ONE_TIME'|'REPEATABLE'|'CONDITIONAL'|'PATCHED'|'INCONSISTENT';
export type DiscoveryConditions={ [key:string]:string|undefined;exclusions?:string;eligibility?:string;timeOfDay?:string;weather?:string;missionState?:string;storyProgression?:string;character?:string;playerCount?:string;platform?:string;gameVersion?:string;requiredItem?:string;requiredVehicle?:string;wantedLevel?:string;previousAction?:string;cooldown?:string;other?:string;requirements?:string;accountEligibility?:string};
export type TimeCondition={start:string;end:string;clock:'IN_GAME'|'REAL_WORLD'|'UNKNOWN';wrapsMidnight:boolean};
export type DiscoveryDraft={discoveryType:DiscoveryType;primaryEntity?:string;location:DiscoveryLocation;action?:string;reward?:DiscoveryReward;requirements:string[];conditions:DiscoveryConditions;timeConditions?:TimeCondition;weatherConditions?:string;missionConditions?:string;playerCount?:string;platform?:string;gameVersion?:string;method?:string;steps:string[];resetCondition?:string;respawnCondition?:string;cooldown?:string;risk?:string;repeatable:Repeatability;confirmationClass?:'FULL_CONFIRMATION'|'PARTIAL_CONFIRMATION'|'CONTRADICTING_OBSERVATION'|'DIFFERENT_CONDITIONS'|'COULD_NOT_REPRODUCE';reportedRepeatability?:Repeatability;reportedOccurrences?:number;patchReport:boolean;assertionKind:'OBSERVATION'|'GENERALIZED';binding?:{propositions:GroundedProposition[];fields:Record<string,PropositionFieldBinding[]>;state:'COMPLETE'|'INCOMPLETE_NEEDS_REVIEW';reviewReasons:string[]};numericEvidence?:NumericEvidence[];proposition?:QualifiedDiscoveryProposition;eligibilityStates?:string[];rewards?:DiscoveryReward[];outcome?:{state:OutcomeState;evidence:FieldSupport[];qualification?:string;scope?:Record<string,unknown>};timeEvidence?:{role:string;text:string;support:FieldSupport;condition:boolean}[];fieldSupport?:Record<string,FieldSupport[]>;reportedRepetition?:{text:string;count?:number;state:string;support:FieldSupport};reportedPatchStatus?:'ALLEGED'|'REPORTED'|'UNKNOWN';grounding:{quote:string;method:'DETERMINISTIC_QUOTE'|'GROUNDED_STRUCTURED'};game:string};
export type DiscoveryObservation={evidenceId:string;sourceId:string;observedAt:string;stance:string;dimensions:DiscoveryDraft;independenceFamily:string;author:string|null;eligible:boolean};
export type ActionableDiscovery=DiscoveryDraft&{discoveryId:string;claimId:string;evidenceIds:string[];sourceIds:string[];discoveredBy:string|null;firstObservedAt:string;lastConfirmedAt:string|null;lastCheckedAt:string|null;status:string;truthStatus:string;confidence:number;observations:DiscoveryObservation[];archived:boolean;testOnly:boolean;actionability:{score:number;dimensions:Record<string,boolean>;meaning:string};completeness:{score:number;missingFields:string[];state:string};followUps:{field:string;question:string}[];freshness:{state:'UNKNOWN'|'CURRENT'|'NEEDS_REVALIDATION'|'OUTDATED';maxAgeHours:number;checkedAt:string|null};patchState:'NONE'|'REPORTED'|'PATCHED';related:{discoveryId:string;reason:string}[];supersededBy:string[];rewardVariants:DiscoveryReward[];possibleTimeConditions:string[];generalizationEstablished:boolean};
export function validateCoordinates(c:Coordinates){
 if(!c||typeof c.coordinateSystem!=='string'||!c.coordinateSystem.trim()||!['degrees','map_units','meters'].includes(c.units))throw Error('Explicit coordinate system and units required');
 const geo=c.latitude!==undefined||c.longitude!==undefined,xy=c.x!==undefined||c.y!==undefined;
 if(geo===xy)throw Error('One complete coordinate pair required');
 const pair=geo?[c.latitude,c.longitude]:[c.x,c.y];if(pair.some(v=>typeof v!=='number'||!Number.isFinite(v)))throw Error('Invalid coordinates');
 if(geo&&(c.coordinateSystem!=='WGS84'||c.units!=='degrees'||Math.abs(c.latitude!)>90||Math.abs(c.longitude!)>180))throw Error('Geographic coordinates require WGS84 degrees and valid ranges');
 if(xy&&(c.coordinateSystem==='WGS84'||c.units==='degrees'))throw Error('Map coordinates cannot masquerade as latitude/longitude');
}
export function validateDiscoveryDraft(d:DiscoveryDraft){
 if(!d||!discoveryTypes.includes(d.discoveryType)||!d.location||!['EXACT','BUILDING','STREET','DISTRICT','REGION','APPROXIMATE','UNKNOWN'].includes(d.location.precision)||!['UNKNOWN','ONE_TIME','REPEATABLE','CONDITIONAL','PATCHED','INCONSISTENT'].includes(d.repeatable)||!['OBSERVATION','GENERALIZED'].includes(d.assertionKind))throw Error('Invalid discovery schema');
 if(Object.entries(d.location).some(([k,v])=>!['coordinates','needsDetail'].includes(k)&&v!==undefined&&(typeof v!=='string'||v.length>500)))throw Error('Invalid location dimension');
 if(['primaryEntity','action','method','resetCondition','respawnCondition','cooldown','risk','platform','gameVersion'].some(k=>d[k]!==undefined&&(typeof d[k]!=='string'||d[k].length>1000)))throw Error('Invalid discovery text dimension');
 if(d.location.needsDetail!==undefined&&typeof d.location.needsDetail!=='boolean')throw Error('Invalid location ambiguity');
 const spans=[...Object.values(d.fieldSupport??{}).flat(),...(d.timeEvidence??[]).map(t=>t.support),...(d.outcome?.evidence??[]),...(d.rewards??[]).flatMap(r=>[r.support,r.eligibilitySupport].filter(Boolean)),...(d.reportedRepetition?[d.reportedRepetition.support]:[])];if(spans.some(e=>!e||e.source!=='PRIMARY'||typeof e.quote!=='string'||!e.quote||!Number.isInteger(e.start)||e.start<0||!Number.isInteger(e.end)||e.end-e.start!==e.quote.length))throw Error('Invalid primary evidence span');
 if(d.outcome&&!['SUCCESS','FAILURE','PARTIAL','INCONSISTENT','NOT_TESTED','UNKNOWN'].includes(d.outcome.state))throw Error('Invalid outcome');
 if(d.proposition){
 const p=d.proposition,offset=p.support.start,local=(e:FieldSupport)=>e&&e.source==='PRIMARY'&&Number.isInteger(e.start)&&e.start>=offset&&e.end-e.start===e.quote.length&&d.grounding.quote.slice(e.start-offset,e.end-offset)===e.quote;
 if(!['COMPLETE','INCOMPLETE_NEEDS_REVIEW'].includes(p.state))throw Error('Invalid proposition state');
 if(!local(p.support)||p.support.quote!==d.grounding.quote)throw Error('Invalid proposition evidence');
 if(p.qualifiers.some(q=>q.scope==='PROPOSITION'&&q.projectedField&&(d.conditions[q.projectedField.replace('conditions.','')]!==q.support.quote||!p.text.toLowerCase().includes(q.support.quote.toLowerCase()))))throw Error('Detached material qualification');
 if(p.qualifiers.some(q=>!local(q.support)))throw Error('Invalid qualifier evidence');
 if(materialQualifiers(d.grounding.quote).some(q=>q.scope==='PROPOSITION'&&!p.qualifiers.some(x=>x.kind===q.kind&&x.support.quote===q.support.quote&&x.support.start===q.support.start+offset)))throw Error('Missing material qualification');
 if(p.state==='COMPLETE'&&(materialQualifiers(d.grounding.quote).some(q=>!p.qualifiers.some(x=>x.kind===q.kind&&x.support.quote===q.support.quote&&x.support.start===q.support.start+offset))||p.missingQualifiers.length||p.qualifiers.some(q=>q.scope==='UNRESOLVED'||!q.projectedField||d.conditions[q.projectedField.replace('conditions.','')]!==q.support.quote||!p.text.toLowerCase().includes(q.support.quote.toLowerCase()))))throw Error('Incomplete qualified proposition');
 const canonical=numericRoles(d.grounding.quote,d.game);
 for(const n of d.numericEvidence??[]){const original=canonical.find(x=>x.support.start+offset===n.support.start&&x.support.quote===n.support.quote);if(!original||!local(n.support)||!local(n.relationship)||['role','value','maximum','currency','moneyRole','amountKind'].some(k=>n[k]!==original[k])||n.relationship.quote!==original.relationship.quote||n.relationship.start!==original.relationship.start+offset)throw Error('Invalid numeric role or relationship');}
 for(const r of d.rewards??(d.reward?[d.reward]:[])){if(r.rewardType==='MONEY'&&!canonical.some(n=>n.role==='MONEY'&&r.support?.start===n.support.start+offset&&r.support?.quote===n.support.quote&&r.currency===n.currency&&r.receipt===n.moneyRole&&r.amountKind===(n.amountKind==='LOWER_BOUND'?'UNKNOWN':n.amountKind)&&local(r.support!)&&local(r.relationship!)&&(r.amount??r.minimum)===n.value&&r.maximum===n.maximum&&r.relationship?.quote===n.relationship.quote&&r.relationship?.start===n.relationship.start+offset))throw Error('Unsupported monetary projection');}
 }
 if(d.rewards)for(const reward of d.rewards)validateDiscoveryDraft({...d,rewards:undefined,reward,binding:undefined});
 if(d.location.coordinates)validateCoordinates(d.location.coordinates);
 if(d.location.precision==='EXACT'&&!d.location.coordinates&&!d.location.identity)throw Error('Exact location needs an explicit identity or coordinates');
 if(!Array.isArray(d.steps)||d.steps.length>20||d.steps.some(s=>typeof s!=='string'||s.length>500)||!Array.isArray(d.requirements)||d.requirements.length>20||d.requirements.some(s=>typeof s!=='string'||s.length>500)||!d.conditions||typeof d.conditions!=='object'||Array.isArray(d.conditions)||Object.values(d.conditions).some(v=>typeof v!=='string'||v.length>500))throw Error('Invalid discovery procedure or conditions');
 if(d.reward){const r=d.reward;if(!['MONEY','RP','VEHICLE','WEAPON','ITEM','COLLECTIBLE','ACCESS','OTHER'].includes(r.rewardType)||!['EXACT','APPROXIMATE','RANGE','UNKNOWN'].includes(r.amountKind))throw Error('Invalid reward schema');if([r.amount,r.minimum,r.maximum].some(v=>v!==undefined&&(typeof v!=='number'||!Number.isFinite(v)||v<0)))throw Error('Invalid reward amount');if(r.amountKind==='RANGE'&&(r.minimum===undefined||r.maximum===undefined||r.minimum>r.maximum))throw Error('Invalid reward range');if(['EXACT','APPROXIMATE'].includes(r.amountKind)&&r.amount===undefined)throw Error('Amount required');if(r.currency!==undefined&&!['GTA$','USD','EUR','GBP','unknown','non_currency'].includes(r.currency))throw Error('Invalid reward currency');}
 if(d.timeConditions){const t=d.timeConditions;if(!/^\d{2}:\d{2}$/.test(t.start)||!/^\d{2}:\d{2}$/.test(t.end)||[t.start,t.end].some(v=>Number(v.slice(0,2))>23||Number(v.slice(3))>59)||!['IN_GAME','REAL_WORLD','UNKNOWN'].includes(t.clock))throw Error('Invalid time conditions');}
 if(!d.grounding?.quote||typeof d.game!=='string')throw Error('Discovery grounding required');return validatePropositionBindings(d);
}
