import{randomBytes,randomUUID,createHash,scrypt,timingSafeEqual}from'node:crypto';import{promisify}from'node:util';import{InformantService}from'./informants.ts';import type{SqliteRepository}from'./store.ts';const derive=promisify(scrypt),digest=(v:string)=>createHash('sha256').update(v).digest('hex');export const passwordParameters={N:131072,r:8,p:1,maxmem:256*1024*1024};
export async function passwordHash(password:string){if(typeof password!=='string'||password.length<12||password.length>128)throw Error('Password must have 12–128 characters');const salt=randomBytes(16).toString('hex'),key=await derive(password,salt,64,passwordParameters) as Buffer;return['scrypt',131072,8,1,salt,key.toString('hex')].join('$');}
export async function passwordMatches(password:string,encoded:string){if(typeof password!=='string'||password.length>128)return false;const parts=encoded.split('$');if(parts.length!==6||parts[0]!=='scrypt'||parts[1]!=='131072'||parts[2]!=='8'||parts[3]!=='1')return false;const key=await derive(password,parts[4],64,passwordParameters) as Buffer,target=Buffer.from(parts[5],'hex');return target.length===key.length&&timingSafeEqual(key,target);}
export function emailKey(value:any){if(typeof value!=='string'||value.length>254||!/^[A-Z0-9.!#$%&'*+\/=?^_`{|}~-]+@[A-Z0-9](?:[A-Z0-9.-]*[A-Z0-9])?\.[A-Z]{2,63}$/i.test(value.trim()))throw Error('Valid email required');return value.trim().toLowerCase();}
export function handleKey(value:any){if(typeof value!=='string'||!/^[a-zA-Z][a-zA-Z0-9_]{2,23}$/.test(value)||/^(admin|administrator|operator|moderator|staff|support|rockstar|vicewire|thevicewire|deleted|system)(?:_|$)/i.test(value)||/fuck|nigger|nazi/i.test(value))throw Error('Choose a different handle (3–24 letters/numbers/underscore)');return value.toLowerCase();}
export type EmailDelivery=(message:{to:string;purpose:'VERIFY'|'RESET';url:string})=>Promise<void>;
export class FoundationAuth{repo:SqliteRepository;origin:string;deliver?:EmailDelivery;hashesInFlight=0;consentVersion:string;constructor(repo:SqliteRepository,origin:string,deliver?:EmailDelivery,consentVersion='draft-v1'){this.repo=repo;this.origin=origin;this.deliver=deliver;this.consentVersion=consentVersion;}
async hash(password:string){if(this.hashesInFlight>=2)throw Error('Authentication busy; try again later');this.hashesInFlight++;try{return await passwordHash(password);}finally{this.hashesInFlight--;}}
user(id:string){return this.repo.db.prepare('SELECT * FROM foundation_users WHERE id=?').get(id) as any;}
publicUser(id:string){const u=this.user(id);if(!u||u.status!=='ACTIVE')throw Error('Account unavailable');return{id:u.id,handle:u.handle,email:u.email,emailVerified:!!u.verified,role:u.role,createdAt:u.created_at,status:u.status};}
async signup(input:any,legalApproved:boolean){if(!legalApproved)throw Error('Registration awaits owner approval of Terms and Privacy');if(input.agree!==true)throw Error('Terms and Privacy agreement required');const email=emailKey(input.email),handle=handleKey(input.handle),hash=await this.hash(input.password);if(this.repo.communityRecords('profiles').some(p=>p.displayName.toLowerCase()===handle)||this.repo.db.prepare('SELECT 1 FROM foundation_users WHERE email=? OR handle=?').get(email,handle))return{ok:true,note:'If this registration is available, verification instructions will be sent.'};const id=randomUUID(),at=new Date().toISOString();this.repo.transaction(()=>{this.repo.db.prepare('INSERT INTO foundation_users VALUES(?,?,?,?,?,?,?,?,?)').run(id,email,handle,hash,'INFORMANT','ACTIVE',0,at,this.consentVersion);new InformantService(this.repo).save('profiles',{id,displayName:handle,createdAt:at,suspended:false,role:'informant',accountOrigin:'ORGANIC'});this.audit(id,'SIGNUP');});await this.send(id,'VERIFY');return{ok:true,note:'If this registration is available, verification instructions will be sent.',internalUserId:id};}
audit(id:string,action:string){new InformantService(this.repo).audit(id,'ACCOUNT_'+action,id,{scope:'ORGANIC_ONLY'});}
async send(id:string,purpose:'VERIFY'|'RESET'){if(!this.deliver)return false;const u=this.user(id);if(!u||u.status!=='ACTIVE')return false;const token=randomBytes(32).toString('hex'),expires=Date.now()+(purpose==='VERIFY'?86400000:1800000);this.repo.transaction(()=>{this.repo.db.prepare('DELETE FROM foundation_tokens WHERE user_id=? AND purpose=?').run(id,purpose);this.repo.db.prepare('INSERT INTO foundation_tokens VALUES(?,?,?,?)').run(digest(token),id,purpose,expires);});try{await this.deliver({to:u.email,purpose,url:this.origin+'/account#'+purpose.toLowerCase()+'='+token});return true;}catch{this.repo.db.prepare('DELETE FROM foundation_tokens WHERE hash=?').run(digest(token));return false;}}
async resetRequest(email:any){let key='';try{key=emailKey(email);}catch{return{ok:true};}const u=this.repo.db.prepare("SELECT id FROM foundation_users WHERE email=? AND status='ACTIVE'").get(key) as any;if(u)await this.send(u.id,'RESET');return{ok:true};}
async consume(token:any,purpose:'VERIFY'|'RESET',password?:string,expectedUser?:string){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))throw Error('Invalid or expired link');const entry=this.repo.db.prepare('SELECT * FROM foundation_tokens WHERE hash=? AND purpose=? AND expires>?').get(digest(token),purpose,Date.now()) as any;if(!entry||(expectedUser&&entry.user_id!==expectedUser)||this.user(entry.user_id)?.status!=='ACTIVE')throw Error('Invalid or expired link');const hashed=purpose==='RESET'?await this.hash(password!):null;this.repo.transaction(()=>{const deleted=this.repo.db.prepare('DELETE FROM foundation_tokens WHERE hash=? AND expires>?').run(digest(token),Date.now());if(deleted.changes!==1)throw Error('Invalid or expired link');if(purpose==='VERIFY')this.repo.db.prepare('UPDATE foundation_users SET verified=1 WHERE id=?').run(entry.user_id);else{this.repo.db.prepare('UPDATE foundation_users SET password_hash=? WHERE id=?').run(hashed!,entry.user_id);this.invalidate(entry.user_id);this.repo.db.prepare('DELETE FROM foundation_tokens WHERE user_id=?').run(entry.user_id);}this.audit(entry.user_id,purpose);});return{ok:true};}
async login(email:any,password:any){let key='';try{key=emailKey(email);}catch{}const u=this.repo.db.prepare('SELECT * FROM foundation_users WHERE email=?').get(key) as any,hash=u?.password_hash||'scrypt$131072$8$1$00000000000000000000000000000000$'+'00'.repeat(64);if(this.hashesInFlight>=2)throw Error('Authentication busy; try again later');this.hashesInFlight++;let matches=false;try{matches=await passwordMatches(password,hash);}finally{this.hashesInFlight--;}if(!matches||!u||u.status!=='ACTIVE'||this.repo.communityRecords('profiles').find(p=>p.id===u.id)?.accountOrigin!=='ORGANIC')throw Error('Invalid credentials');const token=randomBytes(32).toString('hex'),csrf=randomBytes(32).toString('hex');this.repo.db.prepare('INSERT INTO foundation_sessions VALUES(?,?,?,?)').run(digest(token),u.id,digest(csrf),Date.now()+8*3600000);return{token,csrf,user:this.publicUser(u.id)};}
session(token:any){if(typeof token!=='string'||!/^[a-f0-9]{64}$/.test(token))return null;const s=this.repo.db.prepare('SELECT * FROM foundation_sessions WHERE hash=? AND expires>?').get(digest(token),Date.now()) as any,u=s?this.user(s.user_id):null,p=u?this.repo.communityRecords('profiles').find(p=>p.id===u.id):null;return u?.status==='ACTIVE'&&p?.accountOrigin==='ORGANIC'&&!p.suspended?{...s,user:this.publicUser(u.id)}:null;}
csrf(session:any,token:any){return typeof token==='string'&&/^[a-f0-9]{64}$/.test(token)&&digest(token)===session.csrf;}
logout(token:string){this.repo.db.prepare('DELETE FROM foundation_sessions WHERE hash=?').run(digest(token));}
invalidate(id:string){this.repo.db.prepare('DELETE FROM foundation_sessions WHERE user_id=?').run(id);}
verified(id:string){const u=this.user(id);if(!u||u.status!=='ACTIVE'||!u.verified)throw Error('Verified email required for community actions');new InformantService(this.repo).active(id);return u;}
moderate(actor:string,id:string,status:string){const a=this.user(actor);if(a?.status!=='ACTIVE'||!a.verified||!['MODERATOR','ADMIN'].includes(a.role)||!['ACTIVE','SUSPENDED','BANNED'].includes(status))throw Error('Moderator required');if(id===actor)throw Error('Cannot change own moderation status');if(this.user(id)?.role==='ADMIN'&&a.role!=='ADMIN')throw Error('Administrator authority required');this.repo.transaction(()=>{if(!this.user(id)||this.user(id).status==='DELETED')throw Error('Unknown or deleted user');this.repo.db.prepare('UPDATE foundation_users SET status=? WHERE id=?').run(status,id);const service=new InformantService(this.repo),p=service.account(id);service.save('profiles',{...p,suspended:status!=='ACTIVE'});this.invalidate(id);new InformantService(this.repo).audit(actor,'ACCOUNT_MODERATION_'+status,id,{scope:'ORGANIC_ONLY'});});}
delete(id:string){const user=this.user(id);if(user?.role==='ADMIN'&&Number((this.repo.db.prepare("SELECT count(*) AS n FROM foundation_users WHERE role='ADMIN' AND status='ACTIVE' AND verified=1").get() as any).n)<=1)throw Error('Create a verified successor administrator before deleting the last administrator');this.repo.transaction(()=>{const service=new InformantService(this.repo),p=service.active(id),label='deleted_'+id.slice(0,8);this.repo.db.prepare("UPDATE foundation_users SET email=?,handle=?,password_hash='',status='DELETED',verified=0 WHERE id=?").run(id+'@deleted.invalid',label,id);service.save('profiles',{...p,displayName:label,suspended:true});this.invalidate(id);this.repo.db.prepare('DELETE FROM foundation_tokens WHERE user_id=?').run(id);this.audit(id,'DELETE');});}
}

export async function bootstrapFoundationAdmin(auth:FoundationAuth,env:Record<string,string|undefined>){if(auth.repo.db.prepare("SELECT 1 FROM foundation_users WHERE role='ADMIN'").get())throw Error('Admin already exists; use audited role management');if(!env.VW_ADMIN_EMAIL||!env.VW_ADMIN_HANDLE||!env.VW_ADMIN_PASSWORD)throw Error('Admin credentials must be configured locally in ignored .env');if(!auth.deliver)throw Error('Configure verification email delivery before admin bootstrap');const result=await auth.signup({email:env.VW_ADMIN_EMAIL,handle:env.VW_ADMIN_HANDLE,password:env.VW_ADMIN_PASSWORD,agree:true},true) as any;if(!result.internalUserId)throw Error('Admin identity already exists');auth.repo.transaction(()=>{auth.repo.db.prepare("UPDATE foundation_users SET role='ADMIN' WHERE id=?").run(result.internalUserId);const service=new InformantService(auth.repo),profile=service.account(result.internalUserId);service.save('profiles',{...profile,role:'moderator'});auth.audit(result.internalUserId,'PRIVATE_ADMIN_BOOTSTRAP');});return{created:true,verificationRequired:true};}
export function changeFoundationRole(auth:FoundationAuth,actor:string,id:string,role:string){const a=auth.verified(actor);if(a.role!=='ADMIN'||!['INFORMANT','MODERATOR','ADMIN'].includes(role)||id===actor)throw Error('Administrator role management required');const target=auth.user(id);if(!target||target.status!=='ACTIVE')throw Error('Active organic user required');auth.repo.transaction(()=>{const service=new InformantService(auth.repo),p=service.active(id);auth.repo.db.prepare('UPDATE foundation_users SET role=? WHERE id=?').run(role,id);service.save('profiles',{...p,role:role==='INFORMANT'?'informant':'moderator'});auth.invalidate(id);service.audit(actor,'ACCOUNT_ROLE_CHANGE',id,{role});});}
