import {createHash,randomUUID} from 'node:crypto';
import {locateQuote} from './provenance.ts';
import type {Repository,Claim} from './model.ts';
export const isGtaVI=(c:Claim)=>/^(gta vi|gta 6|grand theft auto vi)$/i.test(c.conditions.game??'');
export function stagingFingerprint(repo:Repository,c:Claim){const evidence=repo.evidence().filter(e=>e.claimId===c.id);return createHash('sha256').update(JSON.stringify({claim:{claim:c.claim,category:c.category,conditions:c.conditions,values:c.values,review:c.review,status:c.status,confidence:c.confidence,contradictions:c.breakdown.independentContradicting},evidence,sources:repo.sources().filter(s=>evidence.some(e=>e.sourceId===s.id))})).digest('hex');}
export function stagingReview(repo:Repository,c:Claim){return repo.communityRecords('gtaVIStagingReviews').filter(r=>r.claimId===c.id).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)||(a.revision??0)-(b.revision??0)).at(-1);}
export function stagingVisible(repo:Repository,c:Claim,at=new Date().toISOString()){
 if(!isGtaVI(c)||['invalid','duplicate'].includes(c.review??'')||c.status==='POTENTIALLY_OUTDATED'||c.category==='LEAK_DERIVED')return false;
 const r=stagingReview(repo,c);if(!r||r.supported!=='YES'||r.current!=='YES'||r.playerCare!=='YES'||r.safeWithStatus!=='YES'||r.usefulness<3||r.fingerprint!==stagingFingerprint(repo,c)||Date.parse(r.expiresAt)<=Date.parse(at)||Date.parse(r.at)>Date.parse(at))return false;
 const sources=repo.sources(),linked=repo.evidence().filter(e=>e.claimId===c.id),grounded=linked.some(e=>{const s=sources.find(s=>s.id===e.sourceId);return s&&!s.raw.synthetic&&!s.raw.informantSuppressed&&s.platform!=='informant'&&/^https:\/\//.test(s.url)&&e.stance!=='contradicts'&&!!locateQuote(s.title+'\n'+s.text,e.candidate.quote);});
 return grounded&&c.publication?.dimensions.grounding.result==='pass'&&c.publication?.dimensions.specificity.result==='pass'&&c.publication?.dimensions.semanticSupport.result!=='fail';
}
export function recordStagingReview(repo:Repository,c:Claim,input:any,at=new Date().toISOString()){
 if(!isGtaVI(c)||!input.reviewer?.trim()||!input.notes?.trim()||!['YES','PARTIAL','NO'].includes(input.supported)||!['YES','UNCERTAIN','NO'].includes(input.current)||!['YES','NO'].includes(input.playerCare)||!['YES','NO'].includes(input.safeWithStatus)||!Number.isInteger(input.usefulness)||input.usefulness<1||input.usefulness>5||!['FACT','OBSERVATION','INFERENCE'].includes(input.intelligenceKind)||!input.topic)throw Error('Complete GTA VI staging review required');
 const r={...input,revision:repo.communityRecords('gtaVIStagingReviews').length+1,id:randomUUID(),claimId:c.id,at,expiresAt:new Date(Date.parse(at)+30*86400000).toISOString(),fingerprint:stagingFingerprint(repo,c),backendStatus:c.status,confidence:c.confidence,publicationState:c.publication?.state,publishingEnabled:false};repo.saveCommunityRecord('gtaVIStagingReviews',r.id,r);return r;
}
export function editorialOrder(repo:Repository,claims:Claim[]){const remaining=claims.map(c=>({c,r:stagingReview(repo,c)})),ordered:Claim[]=[],counts=new Map<string,number>();while(remaining.length){remaining.sort((a,b)=>{const score=(x:any)=>(x.r?.usefulness??3)*10+(x.r?.importance??3)*4+(x.c.calibration?.currentness==='CURRENT'?3:0)+(x.c.status==='DEVELOPING'&&(x.r?.importance??3)>=4?3:0)+Math.max(0,8-(Date.parse(x.r?.at??x.c.firstDetected)-Date.parse(x.r?.sourcePublishedAt??x.c.firstDetected))/86400000/10)-(counts.get(x.r?.topic??x.c.category)??0)*14+(x.c.status==='VERIFIED'?3:x.c.status==='LIKELY'?2:0);return score(b)-score(a)||a.c.claim.localeCompare(b.c.claim);});const next=remaining.shift()!;ordered.push(next.c);counts.set(next.r?.topic??next.c.category,(counts.get(next.r?.topic??next.c.category)??0)+1);}return ordered;}
export function consumerSourceLabel(type:string){return ({OFFICIAL:'Official Rockstar source',OFFICIAL_FOOTAGE:'Official footage',COMMUNITY_DISCOVERY:'Community analysis',INDEPENDENT_ANALYSIS:'Independent report',LEAK_DERIVED:'Independent report',RUMOR:'Community analysis'} as any)[type]??'Independent report';}
