import {createHash,randomUUID} from 'node:crypto';
import {runPipeline} from './pipeline.ts';
import {isGtaVI,recordStagingReview,stagingVisible} from './gta-vi-staging.ts';
import {saveHumanEvaluation} from './human-evaluation.ts';
import type {Repository,SourceItem,Candidate} from './model.ts';
export function corpusScope(repo:Repository):Repository{return Object.assign(Object.create(repo),{claims:()=>repo.claims().filter(isGtaVI)});}
export async function buildGtaVICorpus(repo:Repository,manifest:any){
 if(repo.setting('corpus:'+manifest.id))throw Error('This bounded corpus already ran; no automatic repeated research or extraction');
 const now=manifest.checkedAt;if(!Number.isFinite(Date.parse(now))||manifest.sources.length>30)throw Error('Invalid bounded corpus');
 const legacyBefore=JSON.stringify(repo.claims().filter(c=>!isGtaVI(c))),legacySources=JSON.stringify(repo.sources()),legacyEvidence=JSON.stringify(repo.evidence());
 const items:SourceItem[]=[],responses=new Map<string,any[]>();
 for(const source of manifest.sources){if(!/^https:\/\//.test(source.url)||source.claims.length>30)throw Error('Invalid source record');for(let offset=0;offset<source.claims.length;offset+=10){const rows=source.claims.slice(offset,offset+10),id='gta-vi:'+manifest.id+':'+source.key+':'+offset;const text='EDITORIAL FACTUAL NOTES — paraphrases, not source quotations. GTA VI pre-release context.\n'+rows.map((r:any)=>r.claim).join('\n');const item:SourceItem={id,sourceId:source.url,url:source.url,platform:'web',author:source.author,title:source.title,text,timestamp:source.publishedAt?source.publishedAt+'T12:00:00.000Z':now,ingestedAt:now,engagement:{score:0},evidenceType:source.evidenceType,provenanceDescription:source.context,independenceKey:source.upstream??source.url,raw:{corpusId:manifest.id,game:'GTA VI',textRepresentation:'EDITORIAL_FACTUAL_NOTES',originalPublishedAt:source.publishedAt,checkedAt:now,sourceContext:source.context,upstreamReference:source.upstream??undefined,extractionMethod:'Recorded source-reviewed editorial extraction; no external LLM'},pilotId:manifest.id};items.push(item);responses.set(id,rows);}}
 // Reuse the complete intelligence pipeline with recorded extraction. This adapter
 // and provider have no networking capability. Scope refreshes to GTA VI only.
 const scoped=corpusScope(repo),result=await runPipeline(scoped,{name:'bounded-gta-vi-reviewed-text',fetchItems:async()=>items},{signature:manifest.id,extract:async item=>({output:{kind:'INTEL',reason:'Source-reviewed factual notes with explicit provenance',candidates:responses.get(item.id)!.map((r:any)=>({category:r.category,claim:r.claim,predicate:'documented_'+r.topic,entities:r.entities,conditions:{game:'GTA VI',scope:'pre-release'},values:[],stance:r.kind==='INFERENCE'?'uncertain':'supports',quote:r.claim} as Candidate))},usage:{provider:'recorded-replay',model:'editorial-source-review',stage:'EXTRACT',inputTokens:0,outputTokens:0,estimatedCost:0,at:now}})},now,{cache:false});
 if(result.stopped)throw Error(result.stopped);
 for(const c of scoped.claims()){
 const evidence=repo.evidence().filter(e=>e.claimId===c.id),e=evidence[0],source=items.find(s=>s.id===e?.sourceId);if(!source)continue;const row=responses.get(source.id)!.find(r=>r.claim===e.candidate.quote);if(!row)throw Error('Missing reviewed extraction row');
 const review=recordStagingReview(repo,c,{reviewer:'Codex assisted editorial source review',supported:row.supported,current:row.current,usefulness:row.usefulness,playerCare:row.playerCare,safeWithStatus:row.safeWithStatus,intelligenceKind:row.kind,topic:row.topic,importance:row.importance,searchTerms:row.searchTerms,sourcePublishedAt:source.timestamp,sourceType:source.evidenceType,corroboration:'Supporting sources are attached; shared footage and copied announcements are one evidence family. No invented community corroboration.',contradictions:c.breakdown.independentContradicting?'Attached contrary evidence':'No contrary evidence found in this bounded reviewed set; absence is not exhaustive.',notes:row.notes},now);
 saveHumanEvaluation(repo,{sourceId:source.id,reviewer:review.reviewer,useful:row.playerCare==='YES'?'YES':'NO',showToPlayer:stagingVisible(scoped,c,now)?'YES':'NO',category:c.category,extractionQuality:'correct',matching:e.match.kind==='merge'?'correctly matched existing claim':'correctly created new claim',usefulness:row.usefulness,notes:row.notes,claimIds:[c.id],evidenceReview:{currentness:row.current==='NO'?'OUTDATED':'PRE_RELEASE_UNCONFIRMED',currentnessNote:'Source checked '+now+'. The content describes pre-release material, not a tested release build.',corroboration:review.corroboration,contradictions:review.contradictions}},now);
 }
 const legacyUnchanged=legacyBefore===JSON.stringify(repo.claims().filter(c=>!isGtaVI(c)))&&repo.sources().filter(s=>!items.some(i=>i.id===s.id)).every((s,i)=>JSON.stringify(s)===JSON.stringify(JSON.parse(legacySources)[i]))&&repo.evidence().filter(e=>!items.some(i=>i.id===e.sourceId)).every((e,i)=>JSON.stringify(e)===JSON.stringify(JSON.parse(legacyEvidence)[i]));if(!legacyUnchanged)throw Error('Historical operational graph changed');
 const summary={id:manifest.id,at:now,sourcePages:manifest.sources.length,sourceItems:items.length,candidates:[...responses.values()].reduce((n,r)=>n+r.length,0),normalizedClaims:scoped.claims().length,duplicateMerges:repo.evidence().filter(e=>items.some(s=>s.id===e.sourceId)&&e.match.kind==='merge').length,visible:scoped.claims().filter(c=>stagingVisible(scoped,c,now)).length,legacyUnchanged,costUSD:0,externalLLMCalls:0,searchCostUSD:null,publishingEnabled:false};repo.setSetting('corpus:'+manifest.id,summary);repo.setSetting('consumerGtaVICorpus',{id:manifest.id,at:now});return summary;
}
export function migrateSeedArchives(repo:Repository,corpusId:string,at=new Date().toISOString()){
 if(repo.setting('seededArchiveCorpus')===corpusId)return {updated:0,idempotent:true};
 const profiles=repo.communityRecords('profiles').filter(p=>p.accountOrigin==='SEEDED'),claims=repo.claims().filter(c=>stagingVisible(repo,c,at));if(profiles.length!==24||claims.length<24)throw Error('Expected 24 existing seeded profiles and sufficient reviewed GTA VI claims');
 const before=JSON.stringify({claims:repo.claims(),evidence:repo.evidence(),sources:repo.sources(),usages:repo.usages()}),policy:any=repo.setting('seededPresentation');let count=0;
 repo.transaction(()=>{for(const old of repo.communityRecords('seededContributions'))repo.saveCommunityRecord('seededContributions',old.id,{...old,archivedFromConsumer:true,archivedAt:at});
 const topics=['vehicles','world','characters','gameplay','activities','platforms','weapons','story','businesses','release'];profiles.forEach((p,i)=>{const topic=topics[i%topics.length],specialty=claims.filter(c=>repo.communityRecords('gtaVIStagingReviews').filter(r=>r.claimId===c.id).at(-1)?.topic===topic),pool=[...specialty,...claims.filter(c=>!specialty.includes(c))],n=1+(i*7%5);for(let j=0;j<n;j++){const c=pool[(Math.floor(i/topics.length)+j)%pool.length],evidence=repo.evidence().filter(e=>e.claimId===c.id),sources=repo.sources().filter(s=>evidence.some(e=>e.sourceId===s.id)),id=randomUUID();repo.saveCommunityRecord('seededContributions',id,{id,corpusId,informantId:p.id,accountOrigin:'SEEDED',kind:'SOURCE_BACKED_ARCHIVE',claimId:c.id,evidenceIds:evidence.map(e=>e.id),sourceIds:sources.map(s=>s.id),at,recordedAt:at,sourceObservedAt:c.firstDetected,firstReportEligible:false,provenanceSnapshot:{claim:c,evidence,sources}});count++;}});repo.setSetting('seededPresentation',{...policy,frozen:true});repo.setSetting('seededArchiveCorpus',corpusId);repo.audit({sourceId:corpusId,stage:'SEEDED_ARCHIVE_SCOPE_MIGRATION',result:{profiles:24,contributions:count,priorArchivesRetained:true,frozen:true,firstReports:0},at});if(before!==JSON.stringify({claims:repo.claims(),evidence:repo.evidence(),sources:repo.sources(),usages:repo.usages()}))throw Error('Archive presentation changed operational intelligence');});return {updated:24,contributions:count,priorArchivesRetained:true,frozen:true};
}
