import {SqliteRepository} from './store.ts';import {InformantService} from './informants.ts';import {positiveControls} from './feed-controls.ts';import {writeFileSync,mkdirSync} from 'node:fs';
const repo=new SqliteRepository(process.env.INFORMANT_SCENARIO_DB??'data/informants-synthetic.sqlite'),s=new InformantService(repo);if(s.rows('profiles').length)throw Error('Synthetic scenarios already run; use report, not automatic repeat');const password='synthetic-only-password-123',admin=s.createAccount('Operator',password,'moderator'),alice=s.createAccount('Alice',password),bob=s.createAccount('Bob',password),carol=s.createAccount('Carol',password),dana=s.createAccount('Dana',password),at=new Date().toISOString();const vehicle=positiveControls[1],money={...positiveControls[0],claim:{...positiveControls[0].claim,claim:'Mission X pays GTA$400000 in one hour while playing solo.',predicate:'mission_hourly_payout'}};
const spec=new Map<string,any>();const provider={async extract(source:any){const sub=s.submission(source.raw.submissionId),c=spec.get(sub.id),negative=/did not work|did not pay/i.test(source.text),different=source.raw.platform==='PS5';return {output:{kind:'INTEL',reason:'Synthetic scenario oracle; not live model validation',candidates:[{category:c.category,claim:c.claim,predicate:c.predicate,entities:c.entities,conditions:different?{...c.conditions,platform:'PS5',version:'different update'}:c.conditions,values:c.values,stance:negative?'contradicts':'supports',quote:source.text.split('\n')[0]}]},usage:{provider:'fixture',model:'synthetic-informant-oracle',stage:'EXTRACT',inputTokens:0,outputTokens:0,estimatedCost:0}};}};
async function submit(label:string,c:any,actor=alice){const sub=s.submit(actor.id,{title:'GTA V / GTA Online '+label,description:c.claim,category:c.category,conditions:c.conditions,observedAt:at});spec.set(sub.id,c);await s.process(admin.id,provider);const e=repo.evidence().find(e=>e.sourceId===sub.sourceId);return {sub,claimId:e.claimId};}
async function confirm(x:any,actor:any,report:string,extra={}){s.confirm(actor.id,x.sub.id,{claimId:x.claimId,result:/did not/.test(report)?'did_not_work':'confirmed',report,conditions:{},observedAt:at,...extra});await s.process(admin.id,provider);}
const snapshots=[];const snapshot=(scenario:string,x:any,before:any)=>snapshots.push({scenario,submissionId:x.sub.id,informantId:x.sub.informantId,before,after:{claim:repo.claims().find(c=>c.id===x.claimId),profile:s.list().find(p=>p.id===x.sub.informantId),firstReports:s.rows('firstReports').filter(f=>f.submissionId===x.sub.id),reputation:s.rows('reputation').find(r=>r.id===x.sub.id)}});
const a=await submit('A — new vehicle location',vehicle.claim),aBefore=repo.claims().find(c=>c.id===a.claimId);await confirm(a,bob,vehicle.claim.claim+' I tested independently at 20:00.');await confirm(a,carol,vehicle.claim.claim+' I tested independently at 21:00.');s.vote(bob.id,a.sub.id,'useful');s.reconcile();s.helped(bob.id,a.sub.id);snapshot('A: new useful location independently confirmed',a,aBefore);
const b=await submit('B — fake money method',money.claim),bBefore=repo.claims().find(c=>c.id===b.claimId);await confirm(b,bob,money.claim.claim+' I tested it and it did not pay the amount on test one.');await confirm(b,carol,money.claim.claim+' I tested it and it did not pay the amount on test two.');if(Number(repo.claims().find(c=>c.id===b.claimId).breakdown.independentContradicting)>=2)s.moderate(admin.id,'false',b.sub.id,'Two independent synthetic same-scope failures; false method scenario');snapshot('B: fake money method, scoped contrary reports',b,bBefore);
const c=await submit('C — already-known useful location',vehicle.claim,dana);s.vote(bob.id,c.sub.id,'useful');s.reconcile();snapshot('C: known information; no First Report',c,null);
const fresh={...vehicle.claim,claim:'A Sentinel spawns at the pier parking lot at night in story mode.',entities:['Sentinel','pier parking lot'],conditions:{game:'GTA V',location:'pier parking lot',time:'night',mode:'story mode'}};
const d=await submit('D — popular without confirmation',fresh),dBefore=repo.claims().find(c=>c.id===d.claimId);for(const actor of [bob,carol,dana])s.vote(actor.id,d.sub.id,'useful');s.reconcile();snapshot('D: usefulness alone cannot verify',d,dBefore);
const e=await submit('E — mixed platform reports',{...fresh,claim:'A Futo spawns at the depot at night in story mode.',entities:['Futo','depot'],conditions:{game:'GTA V',location:'depot',time:'night',mode:'story mode'}}),eBefore=repo.claims().find(c=>c.id===e.claimId);const et=spec.get(e.sub.id).claim;await confirm(e,bob,et+' I tested it independently at 23:00.');await confirm(e,carol,et+' I tested it and it did not work on PS5 different update.',{platform:'PS5',version:'different update'});snapshot('E: different platform/update not forced into one truth state',e,eBefore);
const f=await submit('F — sustained accurate contribution',{...fresh,claim:'A Blista spawns at the marina parking lot at night in story mode.',entities:['Blista','marina parking lot'],conditions:{game:'GTA V',location:'marina parking lot',time:'night',mode:'story mode'}},dana),fBefore=s.list();const ft=spec.get(f.sub.id).claim;await confirm(f,bob,ft+' I tested independently at 22:30.');await confirm(f,carol,ft+' I tested independently at 23:30.');snapshot('F: accurate repeat contributor moves on The Informant List',f,fBefore);
const report={synthetic:true,paidCalls:0,costUSD:0,publishingEnabled:false,scenarios:snapshots,leaderboard:s.list(),weekly:s.list('week'),monthly:s.list('month'),submissions:s.rows('submissions').map(({knownCandidates,...r})=>r),votes:s.rows('votes'),confirmations:s.rows('confirmations'),reputation:s.rows('reputation'),confirmationAggregates:s.aggregates(),confirmationReputation:s.rows('confirmationReputation'),firstReports:s.rows('firstReports'),audit:s.rows('events'),evidenceHistoryCount:s.rows('evidenceHistory').length};mkdirSync('data',{recursive:true});writeFileSync('data/informants-scenarios.json',JSON.stringify(report,null,2));console.log(JSON.stringify({scenarios:snapshots.map(r=>({scenario:r.scenario,confidence:r.after.claim.confidence,state:r.after.claim.publication.state,reputation:r.after.profile.reputation,firstReports:r.after.firstReports.length})),costUSD:0}));repo.close();
