import { readFileSync } from 'node:fs';
export type SamplingLane={kind:'new'|'hot'|'top'|'search';query?:string};
export type PilotConfig={pilotId:string;subreddits:string[];queries:string[];listingLimit:number;commentsPerPost:number;maxPagesPerLane:number;maxApiRequests:number;requestDelayMs:number;maxSourceItems:number;maxLLMCalls:number;maxEstimatedSpend:number;maxOutputTokens:number;maxInputBytes:number;inputPrice:number|null;outputPrice:number|null;otherCost:number|null};
export function pilotConfig():PilotConfig {
  const file=process.env.REDDIT_PILOT_CONFIG??'config/reddit-pilot.json';
  const raw=JSON.parse(readFileSync(new URL('../'+file,import.meta.url),'utf8'));
  const number=(key:string,fallback:number,min:number,max:number)=>{const n=Number(process.env[key]??fallback);if(!Number.isFinite(n)||n<min||n>max||(key!=='PILOT_MAX_ESTIMATED_SPEND'&&!Number.isInteger(n)))throw Error(`${key} must be ${key==='PILOT_MAX_ESTIMATED_SPEND'?'a number':'an integer'} between ${min} and ${max}`);return n;};
  const price=(key:string)=>{const v=process.env[key];if(v===undefined||!v.trim())return null;const n=Number(v);if(!Number.isFinite(n)||n<0)throw Error('Invalid '+key);return n;};
  const subreddits=(process.env.REDDIT_SUBREDDITS?.split(',')??raw.subreddits).map((s:string)=>s.trim());
  if(!subreddits.length||subreddits.length>10||subreddits.some((s:any)=>typeof s!=='string'||!/^[A-Za-z0-9_]{1,50}$/.test(s)))throw Error('Invalid configured communities');
  if(!Array.isArray(raw.queries)||!raw.queries.length||raw.queries.length>50||raw.queries.some((q:any)=>typeof q!=='string'||q.length>100||!q.trim()))throw Error('Invalid pilot queries');
  const pilotId=process.env.PILOT_ID??'reddit-v0';if(!/^[a-zA-Z0-9_-]{1,60}$/.test(pilotId))throw Error('Invalid PILOT_ID');
  return {pilotId,subreddits:[...new Set(subreddits)] as string[],queries:raw.queries,listingLimit:number('REDDIT_LISTING_LIMIT',10,1,100),commentsPerPost:number('REDDIT_COMMENTS_PER_POST',5,0,50),maxPagesPerLane:number('REDDIT_MAX_PAGES_PER_LANE',2,1,10),maxApiRequests:number('REDDIT_MAX_API_REQUESTS',100,1,500),requestDelayMs:number('REDDIT_REQUEST_DELAY_MS',2000,1000,60000),maxSourceItems:number('PILOT_MAX_SOURCE_ITEMS',50,1,500),maxLLMCalls:number('PILOT_MAX_LLM_CALLS',50,0,1000),maxEstimatedSpend:number('PILOT_MAX_ESTIMATED_SPEND',2,0,100),maxOutputTokens:number('LLM_MAX_OUTPUT_TOKENS',1500,100,4000),maxInputBytes:number('LLM_MAX_INPUT_BYTES',48000,1000,200000),inputPrice:price('LLM_INPUT_PRICE_PER_MILLION'),outputPrice:price('LLM_OUTPUT_PRICE_PER_MILLION'),otherCost:price('PILOT_OTHER_COST')};
}
export function samplingLanes(config:PilotConfig):SamplingLane[]{return [{kind:'new'},{kind:'hot'},{kind:'top'},...config.queries.map(query=>({kind:'search' as const,query}))];}
export function assertRedditAccess(){if(process.env.REDDIT_ACCESS_APPROVED!=='true'||!process.env.REDDIT_ACCESS_TOKEN||!process.env.REDDIT_USER_AGENT)throw Error('Reddit requires explicit approval, OAuth token and identifying User-Agent. Configure .env; no live request made.');}
export function assertLLMAccess(config:PilotConfig){if(!process.env.LLM_ENDPOINT||!process.env.LLM_API_KEY||!process.env.LLM_MODEL)throw Error('Live extraction requires LLM_ENDPOINT, LLM_API_KEY and LLM_MODEL in .env; no fixture fallback.');if(new URL(process.env.LLM_ENDPOINT).protocol!=='https:')throw Error('LLM_ENDPOINT must use HTTPS');if(config.inputPrice===null||config.outputPrice===null)throw Error('Pilot spend guard requires both LLM_INPUT_PRICE_PER_MILLION and LLM_OUTPUT_PRICE_PER_MILLION');}
