import {filter} from './intelligence.ts';import type {SourceItem} from './model.ts';
export type RelevanceDecision={usefulIntel:boolean;actionable:boolean;questionOnly:boolean;bugWorkaround:boolean;discovery:boolean;economy:boolean;worthExtraction:boolean};
export interface RelevanceClassifier {name:string;classify(item:SourceItem):Promise<{decision:RelevanceDecision;latencyMs:number;costUSD:number|null}>;}
export type HumanLabel={sourceId:string;label:'USEFUL_INTEL'|'NOT_USEFUL'|'UNCERTAIN';sendToExtraction:boolean;reason:string;reviewer:string};
export class BaselineRelevanceClassifier implements RelevanceClassifier {name='CURRENT_BASELINE';async classify(s:SourceItem){const start=performance.now(),f=filter(s),t=s.text.toLowerCase();return {decision:{usefulIntel:f.useful,actionable:f.useful,questionOnly:!f.useful&&f.reason==='unanswered question',bugWorkaround:/bug|workaround|fixed|crash/.test(t),discovery:/found|discover/.test(t),economy:/money|gta\$|payout|business/.test(t),worthExtraction:f.useful},latencyMs:performance.now()-start,costUSD:0};}}
// Transport injection avoids guessing between unrelated third-party JEV gateways.
export class JevRelevanceClassifier implements RelevanceClassifier {name='JEV';transport?: (input:{text:string;title:string;context:unknown;questions:string[]})=>Promise<{decision:unknown;costUSD:number|null}>;constructor(transport?:JevRelevanceClassifier['transport']){this.transport=transport;}async classify(s:SourceItem){if(!this.transport)throw Error('JEV unavailable: confirmed official provider documentation and locally configured credential required');const start=performance.now(),r=await this.transport({text:s.text,title:s.title,context:s.context,questions:['usefulIntel','actionable','questionOnly','bugWorkaround','discovery','economy','worthExtraction']});const keys=['usefulIntel','actionable','questionOnly','bugWorkaround','discovery','economy','worthExtraction'];if(!r.decision||typeof r.decision!=='object'||Object.keys(r.decision).length!==7||keys.some(k=>typeof r.decision[k]!=='boolean'))throw Error('Invalid JEV narrow decision');return {decision:r.decision as RelevanceDecision,costUSD:r.costUSD,latencyMs:performance.now()-start};}}
export async function shadowClassification(s:SourceItem,baseline:RelevanceClassifier,jev:RelevanceClassifier){const b=await baseline.classify(s);try{const j=await jev.classify(s);return {sourceId:s.id,baseline:b,jev:j,disagreement:b.decision.worthExtraction!==j.decision.worthExtraction,shadow:true,authoritativeDecision:b.decision.worthExtraction};}catch{return {sourceId:s.id,baseline:b,jev:null,jevStatus:'UNAVAILABLE',disagreement:null,shadow:true,authoritativeDecision:b.decision.worthExtraction};}}
export function benchmark(rows:any[],labels:HumanLabel[],classifier:'baseline'|'jev'){let tp=0,fp=0,fn=0,tn=0,uncertain=0;const latency:number[]=[],costs:number[]=[];let unknownCost=false;for(const row of rows){const result=row[classifier],l=labels.find(l=>l.sourceId===row.sourceId);if(!result||!l)continue;latency.push(result.latencyMs);if(result.costUSD===null)unknownCost=true;else costs.push(result.costUSD);if(l.label==='UNCERTAIN'){uncertain++;continue;}const positive=l.label==='USEFUL_INTEL',predicted=result.decision.worthExtraction;if(positive&&predicted)tp++;else if(positive)fn++;else if(predicted)fp++;else tn++;}const n=tp+fp+fn+tn;return {evaluated:n,uncertain,tp,fp,fn,tn,precision:tp+fp?tp/(tp+fp):null,recall:tp+fn?tp/(tp+fn):null,meanLatencyMs:latency.length?latency.reduce((a,b)=>a+b,0)/latency.length:null,costUSD:unknownCost||!latency.length?null:costs.reduce((a,b)=>a+b,0),costPer1000:unknownCost||!latency.length?null:costs.reduce((a,b)=>a+b,0)/latency.length*1000,extractionAvoidedPercent:n?(tn+fn)/n*100:null};}
export function costProjection(itemsPerDay:number,classificationCost:number|null,passRate:number|null,extractionCost:number|null){return {itemsPerDay,days:30,monthlyItems:itemsPerDay*30,projectedMonthlyCostUSD:classificationCost===null||passRate===null||extractionCost===null?null:itemsPerDay*30*(classificationCost+passRate*extractionCost),assumption:'Pilot rates scaled linearly; no accuracy or traffic guarantee'};}
