import{createHash}from'node:crypto';import type{TransactionalEmailAdapter}from'./foundation-email.ts';
const escape=(v:string)=>v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export class ResendEmailAdapter implements TransactionalEmailAdapter{
 private config:{apiKey:string;from:string;origin:string;testRecipient?:string};private transport:typeof fetch;
 constructor(config:{apiKey:string;from:string;origin:string;testRecipient?:string},transport:typeof fetch=fetch){this.config=config;this.transport=transport;if(!config.apiKey||/\r|\n/.test(config.apiKey)||!/^The Vice Wire <[^<>\s]+@[^<>\s]+>$/.test(config.from))throw Error('Resend configuration required');if(new URL(config.origin).protocol!=='https:')throw Error('Email links require canonical HTTPS');if(config.from.endsWith('@resend.dev>')&&!config.testRecipient)throw Error('Resend development sender requires restricted account recipient');}
 sendVerificationEmail(m:{to:string;url:string}){return this.send(m,'VERIFY');}
 sendPasswordResetEmail(m:{to:string;url:string}){return this.send(m,'RESET');}
 private async send(m:{to:string;url:string},purpose:'VERIFY'|'RESET'){if(this.config.testRecipient&&m.to.toLowerCase()!==this.config.testRecipient.toLowerCase())throw Error('Recipient not permitted for staging test sender');const u=new URL(m.url);if(u.origin!==this.config.origin||u.pathname!=='/account'||!new RegExp('^#'+purpose.toLowerCase()+'=[a-f0-9]{64}$').test(u.hash))throw Error('Invalid transactional link');const action=purpose==='VERIFY'?'Verify your email':'Reset your password',expiry=purpose==='VERIFY'?'24 hours':'30 minutes',security=purpose==='RESET'?'If you did not request this, ignore this message. Your password is unchanged until the link is used.':'This link verifies your private staging Informant account.';let response:Response;try{response=await this.transport('https://api.resend.com/emails',{method:'POST',redirect:'error',signal:AbortSignal.timeout(15000),headers:{Authorization:'Bearer '+this.config.apiKey,'Content-Type':'application/json','Idempotency-Key':createHash('sha256').update(purpose+':'+m.url).digest('hex')},body:JSON.stringify({from:this.config.from,to:[m.to],subject:'The Vice Wire — '+action,text:'THE VICE WIRE\n'+action+'\n'+m.url+'\nExpires in '+expiry+'. '+security+'\nIndependent fan site; not affiliated with Rockstar Games or Take-Two Interactive.',html:'<h1>The Vice Wire</h1><h2>'+action+'</h2><p><a href="'+escape(m.url)+'">'+action+'</a></p><p>Expires in '+expiry+'. '+security+'</p><p>Independent fan site; not affiliated with Rockstar Games or Take-Two Interactive.</p>'})});}catch{throw Error('Email delivery unavailable');}if(!response.ok)throw Object.assign(Error('Email delivery rejected'),{providerStatus:response.status}); // Never retain provider body, which may echo addresses or payload.
 }
}
export function resendFromEnvironment(env:Record<string,string|undefined>,origin:string,transport:typeof fetch=fetch){if(env.VW_EMAIL_PROVIDER!=='resend'||!env.VW_EMAIL_API_KEY||!env.VW_EMAIL_FROM)throw Error('Configure Resend securely before hosted email use');return new ResendEmailAdapter({apiKey:env.VW_EMAIL_API_KEY,from:env.VW_EMAIL_FROM,origin,testRecipient:env.VW_RESEND_TEST_RECIPIENT},transport);}
