import{ReviewerDesk}from'./reviewer-desk.ts';import{InformantService}from'./informants.ts';import{randomUUID}from'node:crypto';import type{Repository,SourceItem}from'./model.ts';
export function reviewerFixtures(repo:Repository,password:string){repo.setSetting('reviewerFixtureMode',true);const service=new InformantService(repo),operator=service.createAccount('DeskReviewer',password,'moderator'),organic=service.createAccount('fixture-reporter',password);const desk=new ReviewerDesk(repo,true);const reports=[
['Clear money lead','money','I found a safe behind the supermarket counter and got about GTA$20k.',{entity:'supermarket safe',action:'opened safe',location:'behind the supermarket counter',reward:'about GTA$20k',amount:20000,currency:'GTA$',rewardRole:'RECEIVED',rewardBasis:'PER_ACTIVITY',assertionKind:'PERSONAL_OBSERVATION',outcome:'SUCCESS',discoveryType:'MONEY'}],
['Combined-session reward','money','I completed the treasure hunt and killed the slasher. I got GTA$500k across the combined session in less than 30 minutes.',{entity:'combined session',action:'completed combined session',reward:'GTA$500k combined session',amount:500000,currency:'GTA$',rewardRole:'RECEIVED',rewardBasis:'SESSION_TOTAL',assertionKind:'PERSONAL_OBSERVATION',outcome:'SUCCESS',discoveryType:'MONEY'}],
['Vehicle spawn','vehicle','I saw a rare car outside the motel at 2am once, on PS5.',{entity:'rare car',action:'observed spawn',location:'outside the motel',conditions:'2am; one observation',platform:'PS5',assertionKind:'PERSONAL_OBSERVATION',discoveryType:'VEHICLE'}],
['Secret location','discovery','I found an unusual locked basement below the motel. I have not found a way inside.',{entity:'locked basement',location:'below the motel',action:'found basement',outcome:'NOT_TESTED',discoveryType:'SECRET'}],
['Alleged patch','bug','After the update my motel door no longer opens on PS5. It worked before the update.',{entity:'motel door',action:'reported access change',platform:'PS5',temporal:'ALLEGED_PATCH',outcome:'FAILURE',discoveryType:'BUG'}],
['Failed workaround','workaround','I restarted the mission on PC and still got no reward. This workaround did not work for me.',{entity:'mission restart',action:'restarted mission',platform:'PC',outcome:'FAILURE',assertionKind:'PERSONAL_OBSERVATION',discoveryType:'WORKAROUND'}],
['Hypothesis','location','Maybe this locked door opens at night. I have not tested it.',{entity:'locked door',action:'opens at night',outcome:'NOT_TESTED',assertionKind:'HYPOTHESIS'}],
['Reported other','money','A friend says they got GTA$25k from the shop safe, but I have not tried it.',{entity:'shop safe',action:'reported receipt',reward:'GTA$25k',amount:25000,currency:'GTA$',rewardRole:'RECEIVED',assertionKind:'REPORTED_OTHER'}],
['Possible duplicate','money','I found a safe behind the supermarket counter and got about GTA$20k.',{entity:'supermarket safe',action:'opened safe'}],
['Possible existing match','vehicle','I saw the same rare car outside the motel at night on PS5.',{entity:'rare car',action:'observed spawn',location:'outside the motel',platform:'PS5'}],
['Possible contradiction','money','I opened the supermarket safe and got GTA$5k, not the expected GTA$20k.',{entity:'supermarket safe',action:'opened safe',reward:'GTA$5k',amount:5000,currency:'GTA$',rewardRole:'RECEIVED'}],
['Shared-source report one','location','I saw the blue car beside the motel at night.',{entity:'blue car',action:'saw car',location:'beside the motel'}],
['Shared-source report two','location','My blue car also appeared beside the motel at night.',{entity:'blue car',action:'saw car',location:'beside the motel'}],
['Independent report','location','I found the blue car beside the motel at night on a separate session.',{entity:'blue car',action:'saw car',location:'beside the motel'}],
['Informant submission','location','I found a locked safe inside the east supermarket on PS5.',{entity:'locked safe',action:'found safe',location:'east supermarket',platform:'PS5'}],
['Official-source change','vehicle','The official gallery caption names the Dinka Enduro motorcycle.',{entity:'Dinka Enduro motorcycle',action:'gallery names vehicle',assertionKind:'CLAIM'}],
['Spam / non-intel','other','Best game ever. Buy cheap coins here.',{}],
['Long source and context','other','A deliberately long isolated editorial report. '+('Source context remains separate from interpretation. '.repeat(70)),{}]
];const result=[];for(let i=0;i<reports.length;i++){const[title,category,text,fields]=reports[i] as any;const source:SourceItem={id:'desk-fixture:'+i,sourceId:'fixture-video-'+i,platform:i===14?'informant':i===15?'web':'youtube',url:'https://example.invalid/reviewer-fixture/'+i+'?reference='+('long-reference-'.repeat(i===17?20:1)),author:i===14?organic.id:'fixture-author-'+i,title,text,timestamp:'2026-10-06T00:00:00Z',ingestedAt:'2026-10-06T00:01:00Z',engagement:{score:0},independenceKey:i===11||i===12?'fixture-shared-video':'fixture-family-'+i,itemType:'comment',evidenceType:i===15?'OFFICIAL':'COMMUNITY_DISCOVERY',raw:{reviewerFixture:true,game:'GTA V'},context:{subreddit:'fixture',postId:'fixture-video-'+i,postTitle:title,postBody:'Necessary isolated fixture context; not a primary observation.',parentId:'fixture-parent',threadId:i===11||i===12?'same-video':'fixture-video-'+i,discovery:[]}};const c=desk.enqueue(source,operator.id,category);if(i!==17)desk.setSuggestion(c.id,{sourceHash:c.sourceHash,model:'FIXTURE_NO_PROVIDER',summary:i===1?'SUGGESTED: GTA$500k from the slasher.':text,fields:{title,summary:text,game:'GTA V',category,...fields,...(i===1?{entity:'slasher',rewardBasis:'PER_ACTIVITY'}:{})},uncertainties:i===1?['Activity attribution may be wrong.']:i===6?['Unperformed hypothesis.']:[],missing:['Version not stated.']});result.push(c.id);}return{desk,operator,organic,ids:result};}
