import {createHash,randomUUID} from 'node:crypto';
import type {Repository,SourceItem,Candidate,Claim,Evidence} from './model.ts';
import {categories,validateExtraction} from './model.ts';
import {InformantService} from './informants.ts';
import {filter,normalize,match,scoreConfidence} from './intelligence.ts';
import {guardDiscoveryMatch,refreshDiscoveries} from './discoveries.ts';
import {evaluateFeedQuality} from './feed-quality.ts';
import {sourceFamily,sourceNetwork} from './independence.ts';
import {sourceEvidenceType,validateSourceProvenance,humanEvidenceReview} from './source-provenance.ts';
import {claimFingerprint} from './proposition.ts';
import {locateQuote} from './provenance.ts';
import {numericRoles} from './discovery-numeric.ts';
import {discoveryTypes,validateDiscoveryDraft} from './discovery-model.ts';
import type {DiscoveryDraft} from './discovery-model.ts';
export const deskStates=['NEW','TRIAGED','NEEDS_REVIEW','NEEDS_CONFIRMATION','APPROVED','EDITED_AND_APPROVED','REJECTED','DUPLICATE','SUPERSEDED'] as const;
export const deskAssertions=['PERSONAL_OBSERVATION','REPORTED_OTHER','GENERALIZATION','HYPOTHESIS','QUESTION','WISH','INSTRUCTION','CLAIM','UNKNOWN'];
export const deskOutcomes=['SUCCESS','FAILURE','PARTIAL','INCONSISTENT','NOT_TESTED','UNKNOWN'];
export const deskTemporal=['CURRENT_OBSERVATION','HISTORICAL','BEFORE_PATCH','AFTER_PATCH','ALLEGED_PATCH','UNKNOWN'];
export const rejectReasons=['NOT_INTEL','DUPLICATE','UNSUPPORTED','TOO_VAGUE','SPECULATION','MISLEADING','OUTDATED','SPAM','OTHER'];
export const deskRelations=['KEEP_SEPARATE','CONFIRM_MATCH','RELATED','DUPLICATE','CONTRADICTION','DIFFERENT_CONDITIONS','SUPERSEDES','UNRELATED','NEEDS_MORE_EVIDENCE'];
export type Editorial={title:string;summary:string;category:string;game:string;discoveryType:string;entity:string;location:string;action:string;reward:string;amount:number|null;currency:string;rewardRole:string;rewardBasis:string;conditions:string;eligibility:string;platform:string;mode:string;version:string;repeatability:string;outcome:string;assertionKind:string;temporal:string;quote:string;statusRecommendation:string;corroboration:string;contradictions:string};
export type Lead={reviewUnit?:import('./review-units.ts').ReviewUnit;id:string;source:SourceItem;sourceHash:string;category:string;state:typeof deskStates[number];revision:number;priority:{score:number;reasons:string[]};flags:string[];suggestion:null|{state:'SUGGESTED';summary:string;fields:Partial<Editorial>;uncertainties:string[];missing:string[];model:string;at:string;sourceHash:string};draft:Editorial;humanApproval:null|{actor:string;at:string;fields:Editorial;claimId:string;evidenceId:string};followUp:{state:'NONE'|'ASK_INFORMANT';questions:string[];delivery:'NOT_SENT'};createdAt:string;updatedAt:string;fixture:boolean};
const h=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');const clone=<T>(x:T):T=>structuredClone(x);const time=()=>new Date().toISOString();
export const blankEditorial=():Editorial=>({title:'',summary:'',category:'other',game:'GTA VI',discoveryType:'OTHER',entity:'',location:'',action:'',reward:'',amount:null,currency:'unknown',rewardRole:'UNKNOWN',rewardBasis:'UNKNOWN',conditions:'',eligibility:'',platform:'',mode:'',version:'',repeatability:'UNKNOWN',outcome:'UNKNOWN',assertionKind:'UNKNOWN',temporal:'UNKNOWN',quote:'',statusRecommendation:'UNVERIFIED',corroboration:'Not assessed',contradictions:'Not assessed'});
export function editorial(input:unknown,base=blankEditorial()):Editorial{if(!input||typeof input!=='object'||Array.isArray(input))throw Error('Editorial fields required');const value={...base};for(const[k,v]of Object.entries(input)){if(!(k in value))throw Error('Unknown editorial field '+k);if(k==='amount'){if(v!==null&&(typeof v!=='number'||!Number.isFinite(v)||v<0))throw Error('Invalid amount');value.amount=v as number|null;}else{if(typeof v!=='string'||v.length>(['quote','conditions','summary'].includes(k)?6000:1500))throw Error('Invalid field '+k);value[k]=v.trim();}}
if(!categories.includes(value.category)||!discoveryTypes.includes(value.discoveryType as any)||!['GTA VI','GTA V','GTA Online','GTA V / GTA Online'].includes(value.game)||!deskAssertions.includes(value.assertionKind)||!deskOutcomes.includes(value.outcome)||!deskTemporal.includes(value.temporal)||!['UNKNOWN','ONE_TIME','REPEATABLE','CONDITIONAL','PATCHED','INCONSISTENT'].includes(value.repeatability)||!['GTA$','USD','EUR','GBP','unknown','non_currency'].includes(value.currency)||!['RECEIVED','EXPECTED','ADVERTISED','BASELINE','BONUS','COST','INVESTMENT','SALE_PRICE','PROFIT','MISSING','COMPARISON','UNKNOWN'].includes(value.rewardRole)||!['UNKNOWN','SESSION_TOTAL','PER_ACTIVITY','CUMULATIVE','DAY_TOTAL','PER_HOUR','ACCOUNT_BONUS','CHARACTER_BONUS'].includes(value.rewardBasis)||!['UNVERIFIED','DEVELOPING','LIKELY','VERIFIED','OUTDATED','DISPUTED'].includes(value.statusRecommendation))throw Error('Invalid editorial enum');return value;}
export function deskFlags(source:SourceItem,suggestion:Lead['suggestion'],draft:Editorial){const flags=[];if(!draft.location)flags.push('MISSING_LOCATION');if(!draft.reward&&draft.category==='money')flags.push('MISSING_REWARD');if(!draft.platform)flags.push('MISSING_PLATFORM');if(!draft.version)flags.push('MISSING_VERSION');if(/\bbut\b|\bthen\b|\balso\b/i.test(source.text))flags.push('COMPOUND_REPORT','MULTIPLE_EVENTS');if(/didn.t|failed|no reward/i.test(source.text)&&/got|worked|received/i.test(source.text))flags.push('CONFLICTING_OUTCOMES');if(draft.assertionKind==='REPORTED_OTHER')flags.push('REPORTED_OTHER');if(draft.assertionKind==='HYPOTHESIS')flags.push('HYPOTHESIS');flags.push(suggestion?.uncertainties.length?'AMBIGUOUS':'CLEAR');return [...new Set(flags)];}
export function deskPriority(source:SourceItem,category:string,flags:string[],independentReports=1){let score=10;const reasons=[];const add=(n:number,r:string)=>{score+=n;reasons.push(r);};if(sourceEvidenceType(source)==='OFFICIAL')add(50,'official-source change');if(category==='money')add(25,'potential money lead');if(['location','easter_egg','discovery'].includes(category))add(20,'potential secret/location');if(/patch|no longer|changed/i.test(source.text))add(20,'patch/change report');if(source.platform==='informant'&&category!=='other')add(15,'actionable Informant lead');if(independentReports>1)add(Math.min(20,(independentReports-1)*10),'multiple distinct source families');if(flags.includes('POSSIBLE_CONTRADICTION'))add(25,'possible contradiction');if(flags.includes('POSSIBLE_DUPLICATE'))add(-20,'possible duplicate');if(/maybe|wish|think/i.test(source.text))add(-10,'weak speculation');if(!filter(source).useful)add(-30,'low-value discussion');return{score:Math.max(0,Math.min(100,score)),reasons};}
export class ReviewerDesk{
repo:Repository;fixtureMode:boolean;constructor(repo:Repository,fixtureMode=false){this.repo=repo;this.fixtureMode=fixtureMode;}
rows():Lead[]{return this.repo.communityRecords('reviewerCandidates');}
get(id:string){const c=this.rows().find(x=>x.id===id);if(!c)throw Error('Candidate not found');return c;}
actor(id:string){const p=new InformantService(this.repo).active(id);if(p.role!=='moderator')throw Error('Moderator required');return p;}
save(c:Lead){this.repo.saveCommunityRecord('reviewerCandidates',c.id,c);}
history(id?:string){return this.repo.communityRecords('reviewerAudit').filter(a=>!id||a.candidateId===id).sort((a,b)=>(a.sequence??0)-(b.sequence??0));}
log(c:Lead,actor:string,action:string,before:any,after:any,reason:string,durationMs=0){const a={id:randomUUID(),sequence:this.repo.communityRecords('reviewerAudit').length+1,candidateId:c.id,actor,action,at:time(),before:clone(before),after:clone(after),reason,durationMs:Math.max(0,Math.min(3600000,Number.isFinite(durationMs)?durationMs:0))};this.repo.saveCommunityRecord('reviewerAudit',a.id,a);return a;}
enqueue(source:SourceItem,actor:string,category='other'){const submitter=new InformantService(this.repo).active(actor);if(submitter.role!=='moderator'&&!(source.platform==='informant'&&source.author===actor&&this.repo.communityRecords('submissions').some(s=>s.sourceId===source.id&&s.informantId===actor&&s.state==='active')))throw Error('Only own authenticated submission may enter queue');if(!categories.includes(category))throw Error('Invalid category');if(!source||typeof source.text!=='string'||source.text.length>6000||source.title.length>200||!Number.isFinite(Date.parse(source.timestamp))||!Number.isFinite(Date.parse(source.ingestedAt)))throw Error('Short source report and timestamps required');const u=new URL(source.url);if(u.protocol!=='https:'||u.username||u.password)throw Error('HTTPS source reference required');validateSourceProvenance(source);const fixture=source.raw.reviewerFixture===true;if(fixture&&!this.fixtureMode)throw Error('Reviewer fixtures cannot enter staging');if(source.platform==='informant'){const p=new InformantService(this.repo).account(source.author!);if(p.accountOrigin!=='ORGANIC'||p.suspended)throw Error('Seeded/suspended Informants cannot supply evidence');}const sourceHash=h(source);const old=this.rows().find(c=>c.source.id===source.id&&c.sourceHash===sourceHash);if(old)return old;
const draft={...blankEditorial(),title:source.title,category,quote:source.text.slice(0,2000),game:String(source.raw.game??'GTA VI')};const c:Lead={id:randomUUID(),source:clone(source),sourceHash,category,state:'NEW',revision:0,priority:{score:0,reasons:[]},flags:[],suggestion:null,draft,humanApproval:null,followUp:{state:'NONE',questions:[],delivery:'NOT_SENT'},createdAt:time(),updatedAt:time(),fixture};c.flags=deskFlags(source,null,draft);c.priority=deskPriority(source,category,c.flags);this.repo.transaction(()=>{this.save(c);this.log(c,actor,'ENQUEUE',null,c,'Source queued; no intelligence created');});return c;}
setSuggestion(id:string,input:any){const c=this.get(id);if(c.humanApproval||['REJECTED','DUPLICATE','SUPERSEDED'].includes(c.state))throw Error('Review is closed');if(input.sourceHash!==c.sourceHash)throw Error('Stale source suggestion');if(c.suggestion)return c;const fields=editorial(input.fields??{},blankEditorial());if(typeof input.summary!=='string'||input.summary.length>3000||typeof input.model!=='string'||!Array.isArray(input.uncertainties)||!Array.isArray(input.missing)||[...input.uncertainties,...input.missing].some(x=>typeof x!=='string'||x.length>500))throw Error('Invalid suggested assistance');const suggestion={state:'SUGGESTED' as const,summary:input.summary,fields:clone(input.fields??{}),uncertainties:input.uncertainties,missing:input.missing,model:input.model,at:time(),sourceHash:c.sourceHash};const next={...c,suggestion,state:'NEEDS_REVIEW' as const,revision:c.revision+1,updatedAt:time()};next.flags=deskFlags(c.source,suggestion,fields);this.repo.transaction(()=>{this.save(next);this.log(next,'AI_ASSISTANT','SUGGESTION',null,suggestion,'Suggestion only; draft and graph not changed');});return next;}
annotated(c:Lead){const possible=this.matches(c.id),flags=[...c.flags];if(possible.length)flags.push('POSSIBLE_DUPLICATE');if(possible.some(m=>m.status==='VERIFIED'&&c.draft.amount!==null&&m.values.some(v=>v.value!==c.draft.amount)))flags.push('POSSIBLE_CONTRADICTION');const related=this.pendingMatches(c.id),families=new Set([sourceFamily(c.source),...related.map(x=>x.family)]);return{...c,flags:[...new Set(flags)],priority:deskPriority(c.source,c.category,flags,families.size)};}
pendingMatches(id:string){const c=this.get(id),words=new Set(c.source.text.toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]);return this.rows().filter(x=>x.id!==id&&x.category===c.category&&!x.humanApproval&&['NEW','TRIAGED','NEEDS_REVIEW','NEEDS_CONFIRMATION'].includes(x.state)).map(x=>{const tokens=new Set(x.source.text.toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]);return{id:x.id,title:x.draft.title,state:x.state,score:[...tokens].filter(t=>words.has(t)).length/Math.max(tokens.size,1),family:sourceFamily(x.source)};}).filter(x=>x.score>.35).sort((a,b)=>b.score-a.score).slice(0,5);}
list(filters:any={}){return this.rows().map(c=>this.annotated(c)).filter(c=>(!filters.state||c.state===filters.state)&&(!filters.category||c.category===filters.category)&&(!filters.source||c.source.platform===filters.source)&&(!filters.family||sourceFamily(c.source)===filters.family)&&(!filters.priority||c.priority.score>=Number(filters.priority))&&(!filters.duplicate||this.matches(c.id).length>0)&&(!filters.contradiction||c.flags.includes('POSSIBLE_CONTRADICTION'))&&(!filters.informant||c.source.platform==='informant')&&(!filters.official||sourceEvidenceType(c.source)==='OFFICIAL')&&(!filters.since||c.createdAt>=filters.since)).sort((a,b)=>b.priority.score-a.priority.score||a.createdAt.localeCompare(b.createdAt));}
independence(c:Lead){const sources=[...this.repo.sources(),...this.rows().map(x=>x.source)],family=sourceFamily(c.source,sources),thread=c.source.context?.threadId??(c.source.platform==='youtube'?c.source.sourceId:null);const shared=this.rows().filter(x=>x.id!==c.id&&(sourceFamily(x.source,sources)===family||thread&&x.source.context?.threadId===thread||c.source.author&&x.source.author===c.source.author));return{source:c.source.platform,sourceFamily:family,upstreamFamily:c.source.context?.threadId??c.source.raw.upstreamReference??null,authorHash:c.source.author?h(c.source.author).slice(0,16):null,copiedOrigin:c.source.copiedFrom??null,publicationNetwork:sourceNetwork(c.source),sharedCandidates:shared.map(x=>x.id),label:shared.length?'SHARED UPSTREAM CONTEXT / AUTHOR / FAMILY':'Independence not yet established',countsAsIndependentHuman:c.source.platform==='informant'?new InformantService(this.repo).account(c.source.author!).accountOrigin==='ORGANIC':null};}
preview(c:Lead,fields=c.draft):Candidate{return{category:fields.category,claim:fields.summary||fields.title,predicate:'reviewed_'+(fields.action||fields.category).toLowerCase().replace(/\W+/g,'_'),entities:[fields.entity||fields.title],conditions:Object.fromEntries(Object.entries({game:fields.game,location:fields.location,action:fields.action,conditions:fields.conditions,eligibility:fields.eligibility,platform:fields.platform,mode:fields.mode,version:fields.version,reward_basis:fields.rewardBasis,outcome:fields.outcome,assertion_kind:fields.assertionKind}).filter(([,v])=>v&&v!=='UNKNOWN')),values:fields.amount===null?[]:[{name:'reported_reward',value:fields.amount,unit:fields.currency,currency:fields.currency as any,measurement:fields.rewardBasis==='SESSION_TOTAL'?'cumulative_earnings':'payout',activityBasis:fields.rewardBasis==='UNKNOWN'?'unknown':fields.entity,timeBasis:fields.rewardBasis==='PER_HOUR'?'hour':'per_activity',conditions:{}}],stance:'supports',quote:fields.quote};}
matches(id:string,fields?:Editorial){const c=this.get(id),candidate=normalize(this.preview(c,fields??c.draft),c.source),decision=guardDiscoveryMatch(candidate,this.repo.claims(),match(candidate,this.repo.claims()));const words=new Set((candidate.claim+' '+candidate.entities.join(' ')+' '+c.source.text).toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]);return this.repo.claims().map(x=>{const tokens=new Set((x.claim+' '+x.entities.join(' ')).toLowerCase().match(/[\p{L}\p{N}]+/gu)??[]);const lexical=[...tokens].filter(w=>words.has(w)).length/Math.max(1,tokens.size);const rank=decision.alternatives.find(a=>a.id===x.id)?.score??lexical;return{id:x.id,title:x.claim,status:x.status,conditions:x.conditions,values:x.values,score:rank,automaticDecision:decision,discovery:x.discovery??null};}).filter(x=>x.score>.12).sort((a,b)=>b.score-a.score).slice(0,5);}
discovery(fields:Editorial):DiscoveryDraft{const d:DiscoveryDraft={discoveryType:fields.discoveryType as any,primaryEntity:fields.entity,location:{namedLocation:fields.location||undefined,precision:fields.location?'APPROXIMATE':'UNKNOWN'},action:fields.action,requirements:fields.conditions?[fields.conditions]:[],conditions:Object.fromEntries(Object.entries({other:fields.conditions,eligibility:fields.eligibility,platform:fields.platform,gameVersion:fields.version,mode:fields.mode}).filter(([,v])=>v)),platform:fields.platform||undefined,gameVersion:fields.version||undefined,steps:[],repeatable:fields.repeatability as any,patchReport:fields.temporal==='ALLEGED_PATCH',reportedPatchStatus:fields.temporal==='ALLEGED_PATCH'?'ALLEGED':'UNKNOWN',assertionKind:fields.assertionKind==='PERSONAL_OBSERVATION'?'OBSERVATION':'GENERALIZED',outcome:{state:fields.outcome as any,evidence:[]},grounding:{quote:fields.quote,method:'GROUNDED_STRUCTURED'},game:fields.game};if(fields.reward)d.reward={rewardType:fields.amount===null?'OTHER':'MONEY',amount:fields.amount??undefined,amountKind:fields.amount===null?'UNKNOWN':/about|approximately|~/.test(fields.quote)?'APPROXIMATE':'EXACT',currency:fields.currency as any,itemReward:fields.amount===null?fields.reward:undefined,basis:fields.rewardBasis as any,receipt:fields.rewardRole as any};return validateDiscoveryDraft(d);}
validation(c:Lead,f:Editorial){if(!f.title||!f.summary||!f.entity||!f.action||!f.quote)throw Error('Title, summary, entity, action and source quote required');if(!locateQuote(c.source.text,f.quote))throw Error('Quote must be present in the original report');const roles=numericRoles(f.quote,f.game);if(f.amount!==null&&!roles.some(n=>n.role==='MONEY'&&n.value===f.amount&&n.currency===f.currency&&(f.rewardRole==='UNKNOWN'||n.moneyRole===f.rewardRole)))throw Error('Amount/currency/reward role must match existing numeric safety; leave UNKNOWN if unresolved');if(f.repeatability==='PATCHED')throw Error('Do not declare PATCHED manually; retain an alleged patch report');const candidate=this.preview(c,f);const v=validateExtraction({kind:'INTEL',candidates:[candidate]},c.source.text);if(v.kind!=='INTEL')throw Error('Invalid reviewed structure');return{...v.candidates[0],temporal:{publishedAt:c.source.timestamp,observedAt:['HISTORICAL','BEFORE_PATCH','ALLEGED_PATCH'].includes(f.temporal)?null:c.source.timestamp,observedTimeText:f.temporal,invalidates:f.temporal==='ALLEGED_PATCH',update:f.temporal==='AFTER_PATCH'}};}
act(actor:string,id:string,input:any){this.actor(actor);const c=this.get(id);if(input.revision!==c.revision)throw Error('Review changed; reload before acting');if(c.humanApproval||['REJECTED','DUPLICATE','SUPERSEDED'].includes(c.state))throw Error('Review is closed');const action=input.action;if(!['SAVE','TRIAGE','APPROVE','EDIT_AND_APPROVE','REJECT','NEEDS_CONFIRMATION','DUPLICATE','SUPERSEDED','ASK_INFORMANT'].includes(action))throw Error('Invalid review action');const fields=editorial(input.fields??{},c.draft),next={...clone(c),draft:fields,category:fields.category,revision:c.revision+1,updatedAt:time()};const reason=String(input.reason??'').trim();if(reason.length>2000)throw Error('Review note too long');const relation=input.relation??'KEEP_SEPARATE';if(!deskRelations.includes(relation))throw Error('Invalid evidence relationship');const target=input.targetClaimId?this.repo.claims().find(x=>x.id===input.targetClaimId):null;if(['CONFIRM_MATCH','DUPLICATE','CONTRADICTION','SUPERSEDES','RELATED','DIFFERENT_CONDITIONS'].includes(relation)&&!target)throw Error('Select an existing claim');
return this.repo.transaction(()=>{
if(action==='SAVE')next.state='NEEDS_REVIEW';if(action==='TRIAGE')next.state='TRIAGED';if(action==='REJECT'){if(!rejectReasons.includes(input.rejectReason))throw Error('Rejection reason required');next.state='REJECTED';}if(action==='DUPLICATE'||relation==='DUPLICATE'){if(!target)throw Error('Duplicate target required');next.state='DUPLICATE';}if(action==='SUPERSEDED'){if(!target)throw Error('Superseding claim required');next.state='SUPERSEDED';}if(action==='NEEDS_CONFIRMATION'){next.state='NEEDS_CONFIRMATION';}if(action==='ASK_INFORMANT'){if(c.source.platform!=='informant')throw Error('ASK INFORMANT is for submissions only');const questions=input.questions??['Which location?','Which platform?','Did it happen more than once?','What version?','Can you provide screenshot/video?'];if(!Array.isArray(questions)||questions.length>10||questions.some(x=>typeof x!=='string'||x.length>500))throw Error('Invalid follow-up questions');next.followUp={state:'ASK_INFORMANT',questions,delivery:'NOT_SENT'};next.state='NEEDS_CONFIRMATION';}
if(['APPROVE','EDIT_AND_APPROVE'].includes(action)&&next.state!=='DUPLICATE'){
if(['RELATED','DIFFERENT_CONDITIONS','UNRELATED','NEEDS_MORE_EVIDENCE','KEEP_SEPARATE','SUPERSEDES'].includes(relation)&&input.targetClaimId&&!target)throw Error('Related target missing');
if(relation==='NEEDS_MORE_EVIDENCE')throw Error('Use NEEDS_CONFIRMATION before graph approval');
const candidate=this.validation(c,fields);if(fields.discoveryType!=='OTHER')candidate.discovery=this.discovery(fields);const recommendation=guardDiscoveryMatch(candidate,this.repo.claims(),match(candidate,this.repo.claims()));
if(relation==='CONFIRM_MATCH'&&target){const entitiesOverlap=candidate.entities.some(e=>target.entities.some(x=>e.toLowerCase()===x.toLowerCase()));if(!entitiesOverlap)throw Error('Unrelated entity: keep separate');const different=Object.keys(candidate.conditions).some(k=>k in target.conditions&&candidate.conditions[k].toLowerCase().trim()!==target.conditions[k].toLowerCase().trim());if(different||candidate.category!==target.category)throw Error('Conflicting scope: keep separate or mark different conditions');}
const source={...clone(c.source),raw:{...c.source.raw,reviewerDeskApproved:true,reviewerId:actor,reviewedAt:time(),humanApprovalCandidateId:c.id}};if(source.platform==='informant'){const p=new InformantService(this.repo).active(source.author!);if(p.accountOrigin!=='ORGANIC')throw Error('Seeded account excluded');}const prior=this.repo.sources().find(s=>s.id===source.id);if(prior&&h(prior)!==c.sourceHash&&h({...prior,raw:c.source.raw})!==c.sourceHash)throw Error('Source changed since queueing');this.repo.saveSource(source);
let claim:Claim;const attach=['CONFIRM_MATCH','CONTRADICTION'].includes(relation);if(attach&&!target)throw Error('Target required');if(attach)claim=target!;else{claim={id:randomUUID(),category:candidate.category,claim:candidate.claim,predicate:candidate.predicate,entities:candidate.entities,conditions:candidate.conditions,values:candidate.values,firstDetected:c.source.timestamp,createdAt:time(),lastCorroborated:null,status:'UNVERIFIED',confidence:0,evidenceCount:0,breakdown:{},review:null,propositionFingerprint:claimFingerprint(candidate)};claim.discovery=candidate.discovery;this.repo.saveClaim(claim);}
if(relation==='SUPERSEDES')candidate.temporal={...candidate.temporal!,invalidates:true,update:true};const stance=relation==='CONTRADICTION'?'contradicts':'supports';candidate.stance=stance;const evidence:Evidence={id:randomUUID(),claimId:claim.id,sourceId:source.id,stance,candidate,match:{kind:attach?'merge':'new',humanReviewed:true,reviewer:actor,candidateId:c.id,relationship:relation,targetClaimId:target?.id??null,automaticRecommendation:recommendation,relatedTemporalClaims:relation==='SUPERSEDES'&&target?[target.id]:[]},createdAt:time()};next.humanApproval={actor,at:time(),fields:clone(fields),claimId:claim.id,evidenceId:evidence.id};next.state=action==='EDIT_AND_APPROVE'?'EDITED_AND_APPROVED':'APPROVED';this.save(next);this.repo.saveEvidence(evidence);
const affected=new Set([claim.id,...(relation==='SUPERSEDES'&&target?[target.id]:[])]);for(const existing of this.repo.claims().filter(x=>affected.has(x.id))){const scored={...existing,...scoreConfidence(existing,this.repo.evidence(),this.repo.sources(),time())};const gate=evaluateFeedQuality(scored,this.repo.evidence(),this.repo.sources(),time());this.repo.saveClaim({...scored,publication:{...gate,published:false}});}refreshDiscoveries(this.repo);const evidenceReview=humanEvidenceReview(this.repo,source,[claim.id],{currentness:['HISTORICAL','BEFORE_PATCH'].includes(fields.temporal)?'HISTORICAL':fields.temporal==='CURRENT_OBSERVATION'?'CURRENT':'UNKNOWN',corroboration:fields.corroboration,contradictions:fields.contradictions},time());next.humanApproval={actor,at:time(),fields:clone(fields),claimId:claim.id,evidenceId:evidence.id};next.state=action==='EDIT_AND_APPROVE'?'EDITED_AND_APPROVED':'APPROVED';this.repo.audit({sourceId:source.id,stage:'REVIEWER_DESK_HUMAN_APPROVAL',at:time(),result:{candidateId:c.id,reviewer:actor,fields:clone(fields),suggestion:clone(c.suggestion),evidenceReview,publication:'DISABLED'}});
// Existing qualification rules decide First Reports/reputation; approval alone earns neither.
new InformantService(this.repo).reconcile();
}
next.flags=deskFlags(c.source,c.suggestion,fields);next.priority=deskPriority(c.source,fields.category,next.flags);this.save(next);this.log(next,actor,action,{state:c.state,fields:c.draft,suggestion:c.suggestion},{state:next.state,fields,approval:next.humanApproval,followUp:next.followUp,relation,targetClaimId:target?.id??null},reason||input.rejectReason||action,input.durationMs);return next;});}
batch(actor:string,ids:string[],action:string){this.actor(actor);if(!['NOT_INTEL','ARCHIVE','DUPLICATE'].includes(action)||!Array.isArray(ids)||ids.length<1||ids.length>50)throw Error('Safe batch triage only');return ids.map(id=>{const c=this.get(id);if(action==='DUPLICATE'){const m=this.matches(id);if(m[0]?.automaticDecision.kind!=='merge')throw Error('Obvious duplicate requires exact compatible existing match');return this.act(actor,id,{revision:c.revision,action:'DUPLICATE',relation:'DUPLICATE',targetClaimId:m[0].id});}return this.act(actor,id,{revision:c.revision,action:'REJECT',rejectReason:action==='NOT_INTEL'?'NOT_INTEL':'TOO_VAGUE',reason:action==='ARCHIVE'?'Archived low-value lead':'Batch non-intel triage'});});}
metrics(){const a=this.history().filter(x=>!['ENQUEUE','SUGGESTION','SAVE'].includes(x.action));return{reviewActions:a.length,counts:Object.fromEntries(['APPROVE','EDIT_AND_APPROVE','REJECT','NEEDS_CONFIRMATION','DUPLICATE','CONFIRM_MATCH'].map(k=>[k,k==='CONFIRM_MATCH'?a.filter(x=>x.after.relation===k).length:a.filter(x=>x.action===k).length])),durationMs:a.map(x=>x.durationMs).filter(x=>x>0),meaning:'Workflow timing only; no reviewer-quality inference',publishingEnabled:false};}
}

