import{createHash}from'node:crypto';
import type{Candidate,Repository}from'./model.ts';
import{ReviewerDesk,blankEditorial,deskPriority,type Lead}from'./reviewer-desk.ts';
import{sourceEvidenceType}from'./source-provenance.ts';
export type ReviewUnit={reviewLeadId:string;parentCandidateId:string;sourceId:string;propositionId:string|null;propositionText:string;sourceExcerpt:string;necessaryContext:string;splitMethod:'EXISTING_CLAIM'|'STRUCTURED_RECORD'|'ENUMERATED_NOTE'|'DETERMINISTIC_SENTENCE'|'UNSPLIT_AMBIGUOUS';siblingIndex:number;siblingCount:number;existingMatch:any|null;flags:string[]};
export function relevantUnitFlags(text:string,category:string){const flags:string[]=[];if(/spawn|found.*(?:car|vehicle)|secret|easter egg/i.test(text)&&!/(?:behind|near|at|inside)\s+\S+/i.test(text))flags.push('MISSING_EXACT_LOCATION');if(category==='money'&&/payout|reward|earn/i.test(text))flags.push('CHECK_REWARD_ROLE');if(/patch|no longer|previously|supersed/i.test(text))flags.push('NEEDS_CURRENTNESS');if(/(?:my friend|someone|player).*?(?:but|then)/i.test(text))flags.push('COMPOUND_REPORT');return flags.length?flags:['CLEAR'];}
export function conservativeWording(text:string,type:string){if(['COMMUNITY_DISCOVERY','INDEPENDENT_ANALYSIS','RUMOR','LEAK_DERIVED','UNKNOWN'].includes(type)&&!/^.*?\b(reports?|reported|observed|describes?|identifies|analysis|recap|may|suggests?|says?|claims?)\b/i.test(text))return 'Source reports: '+text;return text;}
export function reviewBoundaries(repo:Repository,parent:Lead,allowedClaimIds?:Set<string>){const source=parent.source,type=sourceEvidenceType(source);const linked=repo.evidence().filter(e=>e.sourceId===source.id&&(!allowedClaimIds||allowedClaimIds.has(e.claimId))).map(e=>({e,claim:repo.claims().find(c=>c.id===e.claimId)})).filter(x=>x.claim&&x.e.candidate.quote&&source.text.includes(x.e.candidate.quote));if(linked.length){const seen=new Set<string>();return linked.filter(x=>{if(seen.has(x.e.claimId))return false;seen.add(x.e.claimId);return true;}).sort((a,b)=>source.text.indexOf(a.e.candidate.quote)-source.text.indexOf(b.e.candidate.quote)).map(({e,claim})=>({text:claim!.claim,excerpt:e.candidate.quote,method:'EXISTING_CLAIM' as const,claim:claim!,candidate:e.candidate}));}
const records=source.raw.editorialRecords;if(Array.isArray(records)&&records.length&&records.every(r=>r&&typeof r.proposition==='string'&&typeof r.excerpt==='string'&&source.text.includes(r.excerpt)))return records.map(r=>({text:r.proposition,excerpt:r.excerpt,method:'STRUCTURED_RECORD' as const,claim:null,candidate:null}));
if(source.raw.textRepresentation==='EDITORIAL_FACTUAL_NOTES'){const notes=source.text.split(/\r?\n/).map(t=>t.trim()).filter(t=>t&&!/^EDITORIAL FACTUAL NOTES/i.test(t));if(notes.length)return notes.map(text=>({text,excerpt:text,method:'ENUMERATED_NOTE' as const,claim:null,candidate:null}));}
if(type==='OFFICIAL'){const sentences=source.text.match(/[^.!?]+[.!?](?:\s|$)/g)?.map(t=>t.trim())??[];const connected=sentences.some((t,i)=>i>0&&/^(it|they|he|she|this|that|then|however|but|which|therefore|as a result)\b/i.test(t));if(sentences.length>1&&!connected&&sentences.join(' ').replace(/\s/g,'')===source.text.replace(/\s/g,''))return sentences.map(text=>({text,excerpt:text,method:'DETERMINISTIC_SENTENCE' as const,claim:null,candidate:null}));}
return[{text:'Report for human interpretation: '+source.title,excerpt:source.text.slice(0,2000),method:'UNSPLIT_AMBIGUOUS' as const,claim:null,candidate:null}];}
export function prepareReviewUnits(repo:Repository,parentId:string,actor:string,allowedClaimIds?:Set<string>,selectedClaimIds?:Set<string>){const desk=new ReviewerDesk(repo),parent=desk.get(parentId);desk.actor(actor);if(parent.fixture)throw Error('Real-source review preparation excludes fixtures');const stored=repo.sources().find(s=>s.id===parent.source.id);if(!stored||JSON.stringify(stored)!==JSON.stringify(parent.source))throw Error('Unchanged stored parent source required');const boundaries=reviewBoundaries(repo,parent,allowedClaimIds),at=new Date().toISOString();return repo.transaction(()=>boundaries.map((b,index)=>({b,index})).filter(({b})=>!selectedClaimIds||!!b.claim&&selectedClaimIds.has(b.claim.id)).map(({b,index})=>{const text=conservativeWording(b.text,sourceEvidenceType(parent.source)),id='rl-'+createHash('sha256').update(parent.id+'|'+(b.claim?.id??b.excerpt)).digest('hex').slice(0,24),existing=desk.rows().find(c=>c.id===id);if(existing)return existing;const category=b.candidate?.category??parent.category,fields={...blankEditorial(),title:text,summary:text,category,game:'GTA VI',entity:b.candidate?.entities[0]??'',action:b.candidate?.predicate??'',quote:b.excerpt,platform:b.candidate?.conditions.platform??'',mode:b.candidate?.conditions.mode??'',version:b.candidate?.conditions.version??'',temporal:b.claim?.status==='OUTDATED'?'HISTORICAL' as const:'UNKNOWN' as const,conditions:Object.entries(b.candidate?.conditions??{}).filter(([k])=>k!=='game').map(([k,v])=>k+': '+v).join('; ')};
const flags=relevantUnitFlags(text,category),unit:ReviewUnit={reviewLeadId:id,parentCandidateId:parent.id,sourceId:parent.source.id,propositionId:b.claim?.id??null,propositionText:text,sourceExcerpt:b.excerpt,necessaryContext:String(parent.source.raw.sourceContext??parent.source.provenanceDescription??''),splitMethod:b.method,siblingIndex:index+1,siblingCount:boundaries.length,existingMatch:b.claim?{id:b.claim.id,title:b.claim.claim,status:b.claim.status,conditions:b.claim.conditions,values:b.claim.values,score:1,relationship:'EXISTING_SOURCE_CLAIM_LINK'}:null,flags};const c:Lead={...structuredClone(parent),id,revision:0,state:'NEW',draft:fields,category,suggestion:null,humanApproval:null,flags,priority:deskPriority(parent.source,category,flags),createdAt:at,updatedAt:at,reviewUnit:unit};desk.save(c);desk.log(c,actor,'ENQUEUE',null,{reviewUnit:unit,draft:fields},'Deterministic review preparation: '+b.method+'; no truth decision or attachment');return c;}));}
export function recreateReviewSession(repo:Repository,previousId:string,id:string,candidateIds:string[]){if(candidateIds.length<1||candidateIds.length>15||new Set(candidateIds).size!==candidateIds.length)throw Error('Bounded unique review units required');if(repo.communityRecords('reviewerSessions').some(s=>s.id===id))throw Error('Session already exists');const previous=repo.communityRecords('reviewerSessions').find(s=>s.id===previousId);if(!previous||previous.decisions.length)throw Error('Only unreviewed session can be replaced');if(candidateIds.some(id=>!repo.communityRecords('reviewerCandidates').some(c=>c.id===id&&c.reviewUnit&&!c.humanApproval)))throw Error('Review units required');return repo.transaction(()=>{repo.saveCommunityRecord('reviewerSessions',previousId,{...previous,reviewState:'PRE_REVIEW_BLOCKED',friction:{kind:'SOURCE_LEVEL_BLOB',completedReview:false,reportedBy:'human operator'},replacedBy:id});const session={id,createdAt:new Date().toISOString(),startedAt:null,candidateIds,reviewOrder:candidateIds,reviewState:'READY',elapsedSeconds:0,decisions:[],paidAI:false,publishingEnabled:false};repo.saveCommunityRecord('reviewerSessions',id,session);repo.setSetting('reviewerActiveSession',id);return session;});}
