import type {SourceItem,Repository} from './model.ts';
export const evidenceTypes=['OFFICIAL','OFFICIAL_FOOTAGE','COMMUNITY_DISCOVERY','INDEPENDENT_ANALYSIS','LEAK_DERIVED','RUMOR','UNKNOWN'] as const;
export type EvidenceType=typeof evidenceTypes[number];
export function sourceEvidenceType(s:SourceItem):EvidenceType{if(s.evidenceType&&evidenceTypes.includes(s.evidenceType))return s.evidenceType;const legacy=s.raw?.evidenceType??s.raw?.sourceType;if(evidenceTypes.includes(legacy as any))return legacy as EvidenceType;let host='';try{host=new URL(s.url).hostname;}catch{}if(legacy==='official'&&/(^|\.)rockstargames\.com$/.test(host))return 'OFFICIAL';if(['informant','reddit','community'].includes(s.platform))return 'COMMUNITY_DISCOVERY';return 'UNKNOWN';}
export function textReference(url:string){if(!url)return '';const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password||/\.(?:mp4|webm|mov|avi|mkv|mp3|wav|jpg|jpeg|png|gif|webp|zip|rar|7z|exe|dll|iso|torrent|bin)(?:$|[/?#])/i.test(u.pathname))throw Error('Use an HTTPS textual source reference, never a leaked asset URL');return u.toString();}
export function validateSourceProvenance(s:SourceItem){if(s.evidenceType&&!evidenceTypes.includes(s.evidenceType))throw Error('Invalid evidence type');if(sourceEvidenceType(s)!=='LEAK_DERIVED')return; textReference(s.url);if(typeof s.text!=='string'||s.text.length>2000||s.title.length>200||/data:(?:image|video|audio|application)|<\s*(?:img|video|audio|iframe)\b/i.test(s.text))throw Error('Leak-derived storage is limited to short factual text/provenance; assets are prohibited');const inspect=(v:any,key='')=>{if(v instanceof Uint8Array||/^(?:leakedAssets?|assetBytes|mediaBytes|fileBytes|base64|downloadedFile|rawHtml|html)$/i.test(key))throw Error('Leaked asset payloads cannot be stored');if(v&&typeof v==='object')for(const [k,value] of Object.entries(v))inspect(value,k);if(typeof v==='string'&&v.length>2000)throw Error('Leak-derived metadata must remain short textual provenance');if(typeof v==='string'&&/data:(?:image|video|audio|application)|<\s*(?:img|video|audio|iframe)\b/i.test(v))throw Error('Embedded asset payloads cannot be stored');};inspect(s.raw);inspect(s.title);inspect(s.provenanceDescription??'');}
export function annotateSourceProvenance(repo:Repository,sourceId:string,input:any,reviewer:string,at=new Date().toISOString()){const source=repo.sources().find(s=>s.id===sourceId);if(!source)throw Error('Source not found');if(!evidenceTypes.includes(input?.sourceType)||typeof input.description!=='string'||!input.description.trim()||input.description.length>1000||typeof reviewer!=='string'||!reviewer.trim())throw Error('Source type, short provenance description and reviewer required');const next={...source,evidenceType:input.sourceType,provenanceDescription:input.description.trim()};validateSourceProvenance(next);repo.transaction(()=>{repo.saveSource(next);repo.audit({sourceId,stage:'PROVENANCE_REVIEW',at,result:{reviewer,before:sourceEvidenceType(source),sourceType:input.sourceType,description:input.description.trim(),assetPolicy:'TEXT_REFERENCE_ONLY'}});});return {sourceType:input.sourceType,assetPolicy:'TEXT_REFERENCE_ONLY'};}
export function humanEvidenceReview(repo:Repository,source:SourceItem,claimIds:string[],input:any,at:string){const type=sourceEvidenceType(source),required=['LEAK_DERIVED','RUMOR'].includes(type);const review=input??{};if(required&&(!review.currentness||typeof review.corroboration!=='string'||!review.corroboration.trim()||typeof review.contradictions!=='string'||!review.contradictions.trim()))throw Error('Leak/rumor review must explicitly record CURRENTNESS, CORROBORATION and CONTRADICTIONS');const currentness=review.currentness??'UNKNOWN';if(!['CURRENT','HISTORICAL','PRE_RELEASE_UNCONFIRMED','OUTDATED','UNKNOWN'].includes(currentness))throw Error('Invalid currentness');for(const key of ['corroboration','contradictions','currentnessNote'])if(review[key]!==undefined&&(typeof review[key]!=='string'||review[key].length>1500))throw Error('Invalid evidence review note');const allEvidence=repo.evidence(),sources=repo.sources();return {version:1,sourceType:type,sourceDescription:source.provenanceDescription??null,currentness,currentnessNote:review.currentnessNote??'',corroboration:review.corroboration?.trim()||'Not assessed by reviewer',contradictions:review.contradictions?.trim()||'Not assessed by reviewer',recordedAt:at,sourcePublishedAt:source.timestamp,confidence:repo.claims().filter(c=>claimIds.includes(c.id)).map(c=>({claimId:c.id,confidence:c.confidence,status:c.status,lastCorroborated:c.lastCorroborated,independentSupporting:Number(c.breakdown.independentSupporting??0),independentContradicting:Number(c.breakdown.independentContradicting??0),evidence:allEvidence.filter(e=>e.claimId===c.id).map(e=>({evidenceId:e.id,stance:e.stance,sourceType:e.sourceEvidenceType&&e.sourceEvidenceType!=='UNKNOWN'?e.sourceEvidenceType:sourceEvidenceType(sources.find(s=>s.id===e.sourceId)??source),createdAt:e.createdAt}))}))};}

export function claimHumanEvidenceReview(repo:Repository,claimId:string,at:string){const sourceIds=new Set(repo.evidence().filter(e=>e.claimId===claimId).map(e=>e.sourceId));return repo.sources().filter(s=>sourceIds.has(s.id)).map(s=>{const previous=repo.evaluations().filter(e=>e.sourceId===s.id&&e.claimIds.includes(claimId)).at(-1)?.evidenceReview;return {sourceId:s.id,...humanEvidenceReview(repo,s,[claimId],previous,at)};});}
