import {readFileSync} from 'node:fs';
import type {Repository} from './model.ts';
export type AccessStatus='SUPPORTED'|'LIMITED'|'NOT_SUPPORTED';
export type RegisteredSource={id:string;name:string;domain:string;url:string;sourceFamily:string;sourceType:string;authorityAreas:string[];accessMethod:string;adapter:string;intervalMinutes:number;enabled:boolean;accessStatus:AccessStatus;discoveryStatus:string;robotsStatus:string;termsNotes:string;termsUrl:string;reviewedAt:string;priority:number;estimatedCostUSD:number;changeFrequency:string;license:string;maxEntities:number;excerptWords:number};
export function masterSourceRegistry(path=new URL('../config/gta-vi-master-sources.json',import.meta.url)){const rows=JSON.parse(readFileSync(path,'utf8')).sources;const ids=new Set<string>();for(const r of rows){const u=new URL(r.url);if(ids.has(r.id)||!r.id||u.protocol!=='https:'||u.hostname!==r.domain||u.username||u.password||!Array.isArray(r.roles)||!r.roles.length||!['WORKING','BROKEN','PARTIAL','DISABLED_POLICY','DISABLED_TECHNICAL','UNVALIDATED'].includes(r.adapterStatus)||!r.reason||r.enabled&&r.accessStatus!=='SUPPORTED')throw Error('Invalid master source registry');ids.add(r.id);}return rows;}
export function sourceRegistry(path?:URL):RegisteredSource[]{return validateRegistry(path?JSON.parse(readFileSync(path,'utf8')).sources:masterSourceRegistry().filter(r=>r.adapterCatalog==='specialist'));}
export function validateRegistry(sources:RegisteredSource[]){const ids=new Set<string>();for(const s of sources){const u=new URL(s.url);if(!s.id||ids.has(s.id)||u.protocol!=='https:'||u.username||u.password||u.hostname!==s.domain)throw Error('Invalid/duplicate source registry identity');ids.add(s.id);if(!['SUPPORTED','LIMITED','NOT_SUPPORTED'].includes(s.accessStatus)||!Number.isFinite(s.intervalMinutes)||s.intervalMinutes<30||s.intervalMinutes>1440||!s.sourceFamily||!s.termsNotes||!s.reviewedAt||!Array.isArray(s.authorityAreas)||!s.authorityAreas.length||!Number.isInteger(s.maxEntities)||s.maxEntities<1||s.maxEntities>5000||s.excerptWords<1||s.excerptWords>80)throw Error('Invalid source access/interval/retention policy');if(s.enabled&&(s.accessStatus!=='SUPPORTED'||s.accessMethod==='existing-pipeline'))throw Error('Restricted source cannot be enabled');}return sources;}
export function specialistHealth(repo:Repository,sources=sourceRegistry()){return sources.map(s=>{const state:any=repo.setting('scan:state:'+s.id)??{},runtime:any=repo.setting('specialist:health:'+s.id)??{},history:any=repo.setting('specialist:versions:'+s.id)??[];return {...s,checkpoint:state.checkpoint?.state?{fingerprint:state.checkpoint.state.fingerprint,entities:Object.keys(state.checkpoint.state.entities??{}).length}:state.checkpoint??{},lastChecked:state.lastAttempt??runtime.lastChecked??null,lastChanged:runtime.lastChanged??null,lastSuccessfulRetrieval:state.lastSuccessfulScan??null,nextCheck:state.nextScheduledScan??null,health:s.enabled?(runtime.health??'NOT_CHECKED'):'DISABLED',failureCount:runtime.failureCount??0,contentFingerprint:state.checkpoint?.state?.fingerprint??null,itemsChanged:runtime.itemsChanged??0,aiCallsTriggered:repo.usages().filter(u=>u.source===s.id&&u.provider!=='fixture').length,costUSD:repo.usages().filter(u=>u.source===s.id).reduce((n,u)=>n+(u.estimatedCost??u.reservedCost??0),0),versionsRetained:history.length};});}
export function authorityFor(s:RegisteredSource,area:string){return ['OFFICIAL','STOREFRONT'].includes(s.sourceType)&&s.authorityAreas.includes(area)?'PRIMARY_FOR_STATED_SCOPE':'LEAD_OR_OBSERVATION_ONLY';}
export function confirmationRelationship(exists:boolean,explicitContradiction=false){return explicitContradiction?'CONTRADICTED':exists?'PRESENT':'NOT_CONFIRMED';}
