import {ScanScheduler} from './scheduler.ts';
import {SpecialistAdapter} from './specialist-network.ts';
import {sourceRegistry,specialistHealth} from './source-registry.ts';
import type {RegisteredSource} from './source-registry.ts';
import type {Repository} from './model.ts';
import type {ExtractionProvider} from './providers.ts';
import {runPipeline} from './pipeline.ts';
import {contentFingerprint} from './fingerprints.ts';
import {isGtaVI} from './gta-vi-staging.ts';
const forbiddenProvider:ExtractionProvider={signature:'no-ai-on-fetch',extract:async()=>{throw Error('Collection must not invoke AI');}};
export function specialistScheduler(repo:Repository,options:{sources?:RegisteredSource[];fetcher?:typeof fetch;clock?:()=>string}={}){const sources=options.sources??sourceRegistry();return new ScanScheduler(repo,forbiddenProvider,sources.filter(s=>s.enabled&&s.accessStatus==='SUPPORTED').map(s=>new SpecialistAdapter(repo,s,options.fetcher,options.clock)),{processEnabled:false,clock:options.clock});}
export async function scanSpecialists(repo:Repository,options:{sources?:RegisteredSource[];fetcher?:typeof fetch;clock?:()=>string;provider?:ExtractionProvider;candidateCap?:number}={}){
 const cap=options.candidateCap??20;if(!Number.isInteger(cap)||cap<0||cap>20)throw Error('Maximum 20 changed candidates');
 const registry=options.sources??sourceRegistry(),clock=options.clock??(()=>new Date().toISOString()),scheduler=specialistScheduler(repo,{...options,sources:registry}),beforeClaims=repo.claims(),beforeEvidence=repo.evidence(),beforeUsage=repo.usages(),beforeSets=new Set(repo.communityRecords('specialistChanges').map(x=>x.id));
 const checked:any[]=[];for(const s of registry){if(!s.enabled){checked.push({source:s.id,status:s.accessMethod==='existing-pipeline'?'EXISTING_PIPELINE':'BLOCKED',reason:s.termsNotes});continue;}await scheduler.scan(s.id,{reason:'one bounded manual specialist validation'});const runtime:any=repo.setting('specialist:health:'+s.id);checked.push({source:s.id,status:runtime.health,changes:runtime.itemsChanged,entities:Object.keys((scheduler.state(s.id)?.checkpoint.state as any)?.entities??{}).length});}
 const enabled=new Set(registry.filter(s=>s.enabled&&['BASELINED','CHANGED','UNCHANGED'].includes((repo.setting('specialist:health:'+s.id) as any)?.health)).map(s=>s.id)),pending=repo.communityRecords('specialistPending').filter(r=>r.state==='pending'&&enabled.has(r.item.sourceKey)).sort((a,b)=>a.at.localeCompare(b.at)||a.item.id.localeCompare(b.item.id));const selected=pending.slice(0,cap);let processing:any=null;
 if(options.provider&&selected.length){processing=await runPipeline(repo,{name:'specialist-change-only',fetchItems:async()=>selected.map(p=>p.item)},options.provider,clock());for(const p of selected){const source=repo.sources().find(s=>s.id===p.item.id);if(source?.analyzedHash===contentFingerprint(source))repo.saveCommunityRecord('specialistPending',p.item.id,{...p,state:'processed',processedAt:clock()});}}
 const claims=repo.claims(),evidence=repo.evidence(),newClaims=claims.filter(c=>!beforeClaims.some(b=>b.id===c.id)),updated=claims.filter(c=>beforeClaims.some(b=>b.id===c.id&&JSON.stringify(b)!==JSON.stringify(c))),addedEvidence=evidence.filter(e=>!beforeEvidence.some(b=>b.id===e.id)),usage=repo.usages().filter(u=>!beforeUsage.some(b=>b.id===u.id)),sets=repo.communityRecords('specialistChanges').filter(x=>!beforeSets.has(x.id));
 const inspect=[...newClaims.filter(c=>['VERIFIED','LIKELY','DISPUTED','OUTDATED'].includes(c.status)),...updated.filter(c=>beforeClaims.some(b=>b.id===c.id&&b.status==='VERIFIED'))];for(const c of inspect)repo.saveCommunityRecord('specialistHumanReview',c.id,{id:c.id,claimId:c.id,at:clock(),status:'REQUIRED',reason:'Source-driven high-status or existing VERIFIED change; publishing disabled'});
 return {at:clock(),checked,changeSets:sets.length,changedCandidateItems:pending.length,selectedCandidates:options.provider?selected.length:0,aiCalls:usage.filter(u=>u.provider!=='fixture'&&u.provider!=='recorded-replay').length,estimatedCostUSD:usage.every(u=>u.estimatedCost!==null)?usage.reduce((n,u)=>n+(u.estimatedCost??0),0):null,newClaims:newClaims.length,existingClaimsStrengthened:new Set(addedEvidence.filter(e=>beforeClaims.some(c=>c.id===e.claimId)&&e.stance==='supports').map(e=>e.claimId)).size,matchedClaims:new Set(addedEvidence.filter(e=>beforeClaims.some(c=>c.id===e.claimId)).map(e=>e.claimId)).size,additionalEvidence:addedEvidence.length,contradictions:addedEvidence.filter(e=>e.stance==='contradicts').length,supersededOrOutdated:updated.filter(c=>['OUTDATED','POTENTIALLY_OUTDATED'].includes(c.status)).length,duplicatesAvoided:addedEvidence.filter(e=>e.match.kind==='merge').length,humanReviewRequired:inspect.length,pendingCandidates:repo.communityRecords('specialistPending').filter(p=>p.state==='pending').length,baselineGtaVIClaims:beforeClaims.filter(isGtaVI).length,afterGtaVIClaims:claims.filter(isGtaVI).length,publishingEnabled:false,LIVE:false,recurringStarted:false,processing,health:specialistHealth(repo,registry)};
}
