import {createHash} from 'node:crypto';
import type {Repository,SourceItem} from './model.ts';
import type {ScannableSource,ScanRequest,ScanBatch} from './scheduler.ts';
import type {RegisteredSource} from './source-registry.ts';
import {plain,robotsDecision} from './web.ts';
export type Entity={id:string;url:string;fields:Record<string,unknown>};
export type Snapshot={entities:Record<string,Entity>;fingerprint:string;complete:boolean;normalizationVersion?:number;etag?:string;lastModified?:string};
export type FieldChange={entityId:string;kind:'added'|'removed'|'modified';fields:string[];previous?:Record<string,unknown>;current?:Record<string,unknown>};
export type ChangeSet={id:string;sourceId:string;family:string;at:string;previousFingerprint:string;fingerprint:string;changes:FieldChange[];sourceURL:string;state:'PENDING_REVIEW';propositionScope:string};
const sha=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
export function cleanURL(value:string,base?:string){const u=new URL(value,base);if(u.protocol!=='https:'||u.username||u.password)throw Error('Invalid source URL');u.hash='';for(const key of [...u.searchParams.keys()])if(/^(utm_|fbclid$|gclid$|sessionid$)/i.test(key))u.searchParams.delete(key);u.searchParams.sort();return u.href;}
export function stable(value:any):any{if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().filter(k=>!['retrievedAt','sessionId','trackingId','adCount','cookieBanner','navigationCount'].includes(k)).map(k=>[k,stable(value[k])]));return typeof value==='string'?value.replace(/\s+/g,' ').trim():value;}
export const semanticFingerprint=(value:unknown)=>sha(stable(value));
const bounded=(v:string,n:number)=>plain(v.replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g,'$1')).split(/\s+/).slice(0,n).join(' ');
function tag(xml:string,name:string){return xml.match(new RegExp('<'+name+'(?:\\s[^>]*)?>([\\s\\S]*?)</'+name+'>','i'))?.[1]??'';}
function nodes(html:string){const out:any[]=[];const visit=(v:any)=>{if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){out.push(v);if(v['@graph'])visit(v['@graph']);if(v.itemListElement)visit(v.itemListElement);if(v.item)visit(v.item);}};for(const m of html.matchAll(/<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){visit(JSON.parse(m[1]));}return out;}
export function parseSnapshot(body:string,s:RegisteredSource):Snapshot{
 const entities:Record<string,Entity>={};const add=(id:string,url:string,fields:Record<string,unknown>)=>{if(!id||entities[id])throw Error('Missing or duplicate structured entity identity');if(Object.keys(entities).length>=s.maxEntities)throw Error('Source entity cap; refuse incomplete checkpoint');entities[id]={id,url:cleanURL(url,s.url),fields:stable(fields)};};let complete=false;
 if(s.adapter==='gtadb'){const data=JSON.parse(body);if(!data||Array.isArray(data)||typeof data!=='object')throw Error('Invalid GTADB data');for(const [id,v] of Object.entries(data)){const row:any=v;if(!Array.isArray(row)||row.length<7||!Array.isArray(row[1])||!row[1].every(Number.isFinite))throw Error('GTADB landmark schema changed');add(id,'https://map.gtadb.org/',{name:row[0],mapCoordinates:row[1],realWorldReference:row[3],realWorldCoordinates:row[4],categories:row[6],scope:'Community landmark identification; not confirmed gameplay or exact game geometry'});}complete=true;
 }else if(s.adapter==='rss'){if(!/<(?:rss|feed)\b/i.test(body))throw Error('Not a published feed');for(const match of body.matchAll(/<(item|entry)\b[^>]*>([\s\S]*?)<\/\1>/gi)){const item=match[2],url=plain(tag(item,'link'))||item.match(/<link\b[^>]*href=["']([^"']+)/i)?.[1];if(!url)throw Error('Feed entry has no canonical URL');const resolved=cleanURL(url,s.url);if(new URL(resolved).hostname!==s.domain)throw Error('Feed entity outside reviewed source domain');const title=bounded(tag(item,'title'),40),description=tag(item,'description')||tag(item,'summary')||tag(item,'content:encoded'),text=bounded(description,s.excerptWords),id=plain(tag(item,'guid')||tag(item,'id'))||resolved;add(id,resolved,{title,excerpt:text,fullContentFingerprint:sha(plain(description)),publishedAt:plain(tag(item,'pubDate')||tag(item,'published')),updatedAt:plain(tag(item,'updated')),sourceReferences:[...description.matchAll(/href=["']([^"']+)/gi)].flatMap(m=>{try{return[cleanURL(m[1],s.url)]}catch{return[]}}).filter(u=>/rockstargames\.com|youtube\.com|gtadb\.org/.test(new URL(u).hostname)).slice(0,6)});}
 }else if(s.adapter==='jsonld'||s.adapter==='storefront'){const data=nodes(body).filter(n=>s.adapter==='storefront'?/Product|VideoGame/.test(String(n['@type'])):/Article|Posting|ListItem/.test(String(n['@type'])));for(const n of data){const url=n.url??n.mainEntityOfPage?.['@id']??n['@id'];if(typeof url!=='string')continue;const fields=s.adapter==='storefront'?{title:n.name,description:bounded(n.description??'',s.excerptWords),releaseDate:n.releaseDate??n.datePublished??null,platform:n.gamePlatform??null,offers:n.offers??null,features:n.featureList??null}:{title:n.headline??n.name??'',excerpt:bounded(n.description??'',s.excerptWords),fullContentFingerprint:sha(plain(n.description??'')),publishedAt:n.datePublished??null,updatedAt:n.dateModified??null};add(cleanURL(url,s.url),url,fields);}if(!data.length||!Object.keys(entities).length)throw Error('No usable reviewed structured metadata; HTML selector fallback disabled');
 }else if(s.adapter==='article-index'){for(const m of body.matchAll(/<article\b[^>]*>([\s\S]*?)<\/article>/gi)){const article=m[1],heading=article.match(/<h[123]\b[^>]*>([\s\S]*?)<\/h[123]>/i),href=article.match(/<a\b[^>]*href=["']([^"']+)["']/i)?.[1];if(!heading||!href)continue;const url=cleanURL(href,s.url);if(new URL(url).hostname!==s.domain)throw Error('Article outside reviewed domain');const paragraph=article.match(/<p\b[^>]*>([\s\S]*?)<\/p>/i)?.[1]??'',text=plain(article),date=article.match(/<time\b[^>]*(?:datetime|dateTime)=["']([^"']+)/i)?.[1]??text.match(/\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)[a-z]* \d{1,2}, \d{4}\b/)?.[0]??null;add(url,url,{title:bounded(heading[1],40),excerpt:bounded(paragraph,s.excerptWords),fullContentFingerprint:sha(plain(paragraph)),publishedAt:date&&Number.isFinite(Date.parse(date))?new Date(date).toISOString():null,sourceReferences:[...article.matchAll(/href=["']([^"']+)/gi)].flatMap(x=>{try{const u=cleanURL(x[1],s.url);return new URL(u).hostname==='www.rockstargames.com'?[u]:[];}catch{return[]}})});}if(!Object.keys(entities).length)throw Error('No published article cards; refuse selector fallback');complete=false;
 }else if(s.adapter==='mapping'||s.adapter==='json'){const data=JSON.parse(body);if(!Array.isArray(data.entities))throw Error('No documented structured entities');for(const e of data.entities)add(String(e.id??''),e.url??s.url,e.fields??e);if(data.version!==undefined)add('__version__',s.url,{version:data.version});complete=data.complete===true;
 }else throw Error('No audited parser');
 const fingerprint=semanticFingerprint(entities);return {entities,fingerprint,complete,normalizationVersion:2};
}
export function changesBetween(before:Snapshot,after:Snapshot):FieldChange[]{const changes:FieldChange[]=[];for(const id of Object.keys(after.entities).sort()){const old=before.entities[id],next=after.entities[id];if(!old)changes.push({entityId:id,kind:'added',fields:Object.keys(next.fields),current:next.fields});else{const fields=[...new Set([...Object.keys(old.fields),...Object.keys(next.fields)])].filter(k=>semanticFingerprint(old.fields[k]??null)!==semanticFingerprint(next.fields[k]??null));if(fields.length)changes.push({entityId:id,kind:'modified',fields,previous:Object.fromEntries(fields.map(k=>[k,old.fields[k]??null])),current:Object.fromEntries(fields.map(k=>[k,next.fields[k]??null]))});}}if(after.complete)for(const id of Object.keys(before.entities).sort())if(!after.entities[id])changes.push({entityId:id,kind:'removed',fields:Object.keys(before.entities[id].fields),previous:before.entities[id].fields});return changes;}
export function changeRelevant(change:FieldChange){if(change.kind==='removed')return false;const text=JSON.stringify(change.current);return /gta\s*(?:vi|6)|grand theft auto vi|leonida|lucia|jason|vice city|releaseDate|mapCoordinates|version/i.test(text);}
export function changedItem(s:RegisteredSource,c:FieldChange,e:Entity,set:ChangeSet):SourceItem|null{if(!changeRelevant(c))return null;const current=c.current??{},text=String(current.excerpt??current.description??(['gtadb','mapping'].includes(s.adapter)?'GTA VI community mapping observation (not official): '+JSON.stringify(current):''));if(!text)return null;return {id:'specialist:'+s.id+':'+sha([c.entityId,current]).slice(0,24),platform:'web',sourceKey:s.id,sourceId:c.entityId,url:e.url,author:null,title:String(e.fields.title??e.fields.name??s.name).slice(0,200),text,timestamp:typeof e.fields.publishedAt==='string'&&Number.isFinite(Date.parse(e.fields.publishedAt))?new Date(e.fields.publishedAt).toISOString():'1970-01-01T00:00:00.000Z',ingestedAt:set.at,engagement:{score:0},independenceKey:s.sourceFamily==='rockstar-official'?'https://www.rockstargames.com/VI':'upstream-family:'+s.sourceFamily,evidenceType:s.sourceType==='OFFICIAL'?'OFFICIAL':'INDEPENDENT_ANALYSIS',provenanceDescription:set.propositionScope+'; attributed specialist lead, not broader gameplay proof',raw:{sourceType:s.sourceType==='OFFICIAL'?'official':'specialist',sourceFamily:s.sourceFamily,changeSetId:set.id,changedFields:c.fields,sourceURL:e.url,license:s.license,termsUrl:s.termsUrl,upstreamReferences:e.fields.sourceReferences??[],upstreamReference:Array.isArray(e.fields.sourceReferences)?e.fields.sourceReferences[0]:undefined,propositionScope:set.propositionScope,storage:'short attributed changed excerpt only'}};}
export class SpecialistAdapter implements ScannableSource{
 id:string;platform='web';intervalMs:number;s:RegisteredSource;repo:Repository;fetcher:typeof fetch;clock:()=>string;
 constructor(repo:Repository,s:RegisteredSource,fetcher:typeof fetch=fetch,clock=()=>new Date().toISOString()){this.repo=repo;this.s=s;this.id=s.id;this.intervalMs=s.intervalMinutes*60000;this.fetcher=fetcher;this.clock=clock;}
 private async request(url:string,headers:Record<string,string>={}){const u=new URL(url);if(u.hostname!==this.s.domain||u.protocol!=='https:'||u.username||u.password)throw Error('Request outside registry');const r=await this.fetcher(url,{redirect:'manual',signal:AbortSignal.timeout(15000),headers:{'User-Agent':'ViceWireResearch/0.1 (bounded attributed monitoring; respects AI robots restrictions)',...headers}});if(r.status===304)return {response:r,body:''};if(!r.ok){const error:any=new Error('HTTP '+r.status+'; redirects, auth and challenges are not bypassed');error.httpStatus=r.status;const retry=r.headers.get('retry-after');if(retry){const ms=/^\d+$/.test(retry)?Number(retry)*1000:Date.parse(retry)-Date.parse(this.clock());if(Number.isFinite(ms)&&ms>0)error.retryAfterMs=ms;}throw error;}if(/noai/i.test(r.headers.get('x-robots-tag')??''))throw Error('Source AI opt-out');let count=0;const chunks:Uint8Array[]=[];const reader=r.body?.getReader();if(!reader)throw Error('Missing response');for(;;){const {value,done}=await reader.read();if(done)break;count+=value.length;if(count>2000000){await reader.cancel();throw Error('Source byte cap');}chunks.push(value);}const body=Buffer.concat(chunks).toString('utf8');if(/cf-chl-|verify you are human|captcha|<title>just a moment|<meta[^>]+noai/i.test(body.slice(0,20000)))throw Error('Access challenge/opt-out; no bypass');return {response:r,body};}
 async scan(request:ScanRequest):Promise<ScanBatch>{const at=this.clock(),health:any=this.repo.setting('specialist:health:'+this.id)??{failureCount:0};if(health.retryEligible===false&&health.accessReviewedAt===this.s.reviewedAt)throw Error('Source policy blocked; a new access review is required');try{if(!this.s.enabled||this.s.accessStatus!=='SUPPORTED')throw Error('Source access is disabled');if(Date.parse(at)-Date.parse(this.s.reviewedAt)>30*86400000)throw Error('Access review expired');if(this.s.adapter!=='gtadb'){const robots=await this.request(new URL('/robots.txt',this.s.url).href);const decision=robotsDecision(robots.body,new URL(this.s.url).pathname);if(!decision.allowed)throw Error(decision.reason);if(decision.delayMs>60000)throw Error('Crawl delay exceeds manual scan window');if(decision.delayMs)await new Promise(r=>setTimeout(r,decision.delayMs));}
 const previous=request.checkpoint.state as unknown as Snapshot|undefined;const headers:Record<string,string>={};if(previous?.etag)headers['If-None-Match']=previous.etag;if(previous?.lastModified)headers['If-Modified-Since']=previous.lastModified;const {response,body}=await this.request(this.s.url,headers);if(response.status===304&&!previous)throw Error('304 without checkpoint');const current=response.status===304?previous!:parseSnapshot(body,this.s);current.etag=response.headers.get('etag')??previous?.etag;current.lastModified=response.headers.get('last-modified')??previous?.lastModified;let items:SourceItem[]=[];let count=0;const comparable=previous?.normalizationVersion===current.normalizationVersion;
 if(previous&&comparable&&current.fingerprint!==previous.fingerprint){const changes=changesBetween(previous,current);count=changes.length;if(changes.length){const set:ChangeSet={id:sha([this.id,previous.fingerprint,current.fingerprint]),sourceId:this.id,family:this.s.sourceFamily,at,previousFingerprint:previous.fingerprint,fingerprint:current.fingerprint,changes,sourceURL:this.s.url,state:'PENDING_REVIEW',propositionScope:this.s.adapter==='gtadb'?'Community landmark interpretation; not official geometry or confirmed gameplay':'Source-stated proposition only; footage appearances do not imply purchasability/customization/spawn'};this.repo.saveCommunityRecord('specialistChanges',set.id,set);const older=this.repo.communityRecords('specialistChanges').filter(x=>x.sourceId===this.id&&x.id!==set.id&&x.changes.some((c:any)=>c.previous||c.current)).sort((a,b)=>b.at.localeCompare(a.at)).slice(7);for(const old of older)this.repo.saveCommunityRecord('specialistChanges',old.id,{...old,changes:old.changes.map((c:any)=>({entityId:c.entityId,kind:c.kind,fields:c.fields,previousFingerprint:semanticFingerprint(c.previous??null),currentFingerprint:semanticFingerprint(c.current??null)})),textRetention:'expired; metadata only'});for(const relation of sourceChangeRelationships(this.repo,set))this.repo.saveCommunityRecord('specialistRelations',relation.id,relation);for(const change of changes){const e=current.entities[change.entityId];if(!e)continue;const item=changedItem(this.s,change,e,set);if(item){this.repo.saveCommunityRecord('specialistPending',item.id,{item,changeSetId:set.id,at,state:'pending'});if(items.length<Math.min(10,request.limit))items.push(item);}}health.lastChanged=at;}
 }
 if(!previous||current.fingerprint!==previous.fingerprint){const versions:any[]=this.repo.setting('specialist:versions:'+this.id) as any[]??[];if(versions.at(-1)?.fingerprint!==current.fingerprint)this.repo.setSetting('specialist:versions:'+this.id,[...versions,{at,fingerprint:current.fingerprint,previousFingerprint:previous?.fingerprint??null,entities:Object.keys(current.entities).length,itemsChanged:count,sourceURL:this.s.url}].slice(-8));}
 this.repo.setSetting('specialist:health:'+this.id,{...health,lastChecked:at,health:previous&&comparable?(count?'CHANGED':'UNCHANGED'):'BASELINED',lastSuccessfulFetch:at,errorClass:null,retryEligible:true,failureCount:0,itemsChanged:count});return {items,checkpoint:{state:current as any}};
 }catch(e){const failures=(health.failureCount??0)+1,httpStatus=(e as any)?.httpStatus,message=String(e),policy=httpStatus?([401,403].includes(httpStatus)||httpStatus>=300&&httpStatus<400):/disabled|expired|robots|opt-out|challenge|crawl delay/i.test(message);this.repo.setSetting('specialist:health:'+this.id,{...health,lastChecked:at,accessReviewedAt:this.s.reviewedAt,failureCount:failures,health:failures>=3?'DEGRADED':'FAILED',errorClass:policy?'ACCESS_POLICY':httpStatus===429?'RATE_LIMIT':httpStatus?'HTTP_FAILURE':/Timeout/i.test(message)?'TIMEOUT':'SCHEMA_OR_TRANSPORT',retryEligible:!policy,itemsChanged:0});throw e;}}
}

export function sourceChangeRelationships(repo:Repository,set:ChangeSet){const relations:any[]=[];for(const change of set.changes){const release=change.fields.some(f=>/releaseDate|offers|platform/i.test(f)),oldName=String(change.previous?.name??change.previous?.title??'').toLowerCase();for(const claim of repo.claims()){if(!/^(gta vi|gta 6|grand theft auto vi)$/i.test(claim.conditions.game??''))continue;const relevant=release&&/release|edition|price|platform/i.test(claim.predicate+' '+claim.claim)||oldName.length>8&&claim.claim.toLowerCase().includes(oldName);if(relevant)relations.push({id:sha([set.id,claim.id,change.entityId]),changeSetId:set.id,claimId:claim.id,entityId:change.entityId,kind:change.kind==='removed'?'REMOVED_SOURCE_NOT_PROOF_FALSE':release?'POSSIBLE_SUPERSESSION':'REVERIFY_EXISTING',status:'REVIEW_REQUIRED',at:set.at,note:'Use existing verification and calibration review; preserve historical claim/evidence and do not assign OUTDATED from source absence.'});}}return relations;}
export type FrameObservation={entity:string;observation:string;officialSource:string;frame?:number;timecode?:string;category:string;sourceURL:string;propositionScope:'APPEARS_IN_OFFICIAL_MATERIAL_ONLY'};
export function frameObservation(input:Omit<FrameObservation,'propositionScope'>):FrameObservation{cleanURL(input.officialSource);cleanURL(input.sourceURL);if(!input.entity||!input.observation||!input.category||(input.frame===undefined&&!input.timecode)||input.frame!==undefined&&(!Number.isInteger(input.frame)||input.frame<0))throw Error('Invalid frame evidence');return {...input,propositionScope:'APPEARS_IN_OFFICIAL_MATERIAL_ONLY'};}
