import { questionClusters } from './twitch-selection.ts';
import type { SourceItem } from './model.ts';
import type { SourceAdapter } from './adapters.ts';
import type { ScannableSource, ScanRequest } from './scheduler.ts';
export type TwitchStream={id:string;user_id:string;user_login:string;user_name:string;title:string;game_id:string;game_name:string;viewer_count:number;language:string;started_at:string;type:string;tags?:string[];description?:string};
export type ChatMessage={id:string;user:string;text:string;at:string;emotes:number};
export type ActivityWindow={id:string;stream:TwitchStream;start:string;end:string;triggeredAt:string;reasons:string[];priority:number;signal:ReturnType<typeof summarizeChat>;messages:ChatMessage[];clips:any[];truncated:boolean;complete:boolean};
export const pilotLimits={streams:10,durationMinutes:60,windows:10,apiRequests:250,events:100000,messagesPerChannel:5000,messagesPerWindow:100,maxTextBytes:20000};
export function assertTwitchAccess(){if(process.env.TWITCH_ACCESS_APPROVED!=='true')throw Error('Twitch access requires TWITCH_ACCESS_APPROVED=true');if(!process.env.TWITCH_CLIENT_ID||!process.env.TWITCH_USER_ACCESS_TOKEN)throw Error('Missing TWITCH_CLIENT_ID and TWITCH_USER_ACCESS_TOKEN; no live access attempted');}
export class TwitchClient {
 requests=0; events=0;lastPagination:{cursor?:string}={}; requestLimit:number; fetcher:typeof fetch; token:string; clientId:string;
 constructor(options:{fetcher?:typeof fetch;token?:string;clientId?:string;requestLimit?:number}={}){this.fetcher=options.fetcher??fetch;this.token=options.token??process.env.TWITCH_USER_ACCESS_TOKEN??'';this.clientId=options.clientId??process.env.TWITCH_CLIENT_ID??'';this.requestLimit=options.requestLimit??pilotLimits.apiRequests;if(!Number.isInteger(this.requestLimit)||this.requestLimit<1||this.requestLimit>pilotLimits.apiRequests)throw Error('Invalid Twitch request cap');}
 async request(path:string,params:Record<string,string|string[]>={},body?:unknown){if(this.requests>=this.requestLimit)throw Error('Twitch API request cap reached');this.requests++;const url=new URL('https://api.twitch.tv/helix/'+path);for(const [k,v]of Object.entries(params))for(const part of Array.isArray(v)?v:[v])url.searchParams.append(k,part);const r=await this.fetcher(url,{method:body?'POST':'GET',headers:{'Client-Id':this.clientId,Authorization:'Bearer '+this.token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Twitch API HTTP '+r.status);const j:any=await r.json();if(!Array.isArray(j.data))throw Error('Invalid Twitch response');this.lastPagination=j.pagination??{};return j.data;}
 async auth(){if(this.requests>=this.requestLimit)throw Error('Twitch API request cap reached');this.requests++;const r=await this.fetcher('https://id.twitch.tv/oauth2/validate',{headers:{Authorization:'OAuth '+this.token},signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Twitch token validation HTTP '+r.status);const j:any=await r.json();if(j.client_id!==this.clientId||!j.user_id||!j.scopes?.includes('user:read:chat')||j.expires_in<3900)throw Error('Token must match client, authorize user:read:chat, and remain valid for at least 65 minutes');return {userId:j.user_id,scopes:j.scopes,expiresIn:j.expires_in};}
 async discover(limit=5){if(!Number.isInteger(limit)||limit<1||limit>10)throw Error('Stream cap must be 1-10');const games=await this.request('games',{name:'Grand Theft Auto V'});if(!games[0]?.id)throw Error('GTA category not found');return selectStreams(await this.request('streams',{game_id:games[0].id,language:'en',first:'100',type:'live'}),limit,games[0].id);}
 clips(channel:string,start:string,end:string){return this.request('clips',{broadcaster_id:channel,started_at:start,ended_at:end,first:'50'});}
 videos(channel:string){return this.request('videos',{user_id:channel,type:'archive',first:'5'});}
 subscribe(channel:string,user:string,session:string){return this.request('eventsub/subscriptions',{}, {type:'channel.chat.message',version:'1',condition:{broadcaster_user_id:channel,user_id:user},transport:{method:'websocket',session_id:session}});}
}
export function parseStream(s:any):TwitchStream{for(const k of ['id','user_id','user_login','user_name','title','game_id','game_name','language','started_at','type'])if(typeof s?.[k]!=='string')throw Error('Invalid stream '+k);if(!Number.isFinite(s.viewer_count)||s.viewer_count<0||!Number.isFinite(Date.parse(s.started_at)))throw Error('Invalid stream metadata');return {...Object.fromEntries(['id','user_id','user_login','user_name','title','game_id','game_name','viewer_count','language','started_at','type'].map(k=>[k,s[k]])),tags:Array.isArray(s.tags)?s.tags.filter((t:any)=>typeof t==='string').slice(0,20):[]} as TwitchStream;}
export function selectStreams(rows:any[],limit:number,gameId:string){const eligible=[...new Map(rows.map(parseStream).filter(s=>s.type==='live'&&s.game_id===gameId&&s.language==='en'&&!/\b(rp|roleplay|fivem)\b/i.test(s.title)).map(s=>[s.user_id,s])).values()].sort((a,b)=>b.viewer_count-a.viewer_count);const high=eligible.slice(0,Math.ceil(limit/2)),medium=eligible.slice(Math.ceil(eligible.length/2));return [...high,...medium,...eligible].filter((s,i,a)=>a.findIndex(x=>x.user_id===s.user_id)===i).slice(0,limit);}
const terms=['where','how','money','car','location','secret','glitch','bug','mission','weapon','found','works','patched','what is that','how did you','clip','no way','how much','how do you','what mission','what car','what business','what method','does this work','still works','fixed','payout','spawn','unlock','buy','worth','solo','update','new','changed'];
export function summarizeChat(messages:ChatMessage[],now:string,started:string){const at=Date.parse(now),recent=messages.filter(m=>Date.parse(m.at)>at-60000&&Date.parse(m.at)<=at),baseline=messages.filter(m=>Date.parse(m.at)>at-360000&&Date.parse(m.at)<=at-60000);const warm=at-Date.parse(started)>=360000,rate=baseline.length/5,current=recent.length;const counts=terms.map(term=>({term,count:recent.filter(m=>new RegExp('\\b'+term+'\\b','i').test(m.text)).length})).filter(x=>x.count>1);const questions=new Map<string,number>();for(const m of recent){if(m.text.includes('?')){const q=m.text.toLowerCase().replace(/[^a-z0-9 ?]/g,'').trim();questions.set(q,(questions.get(q)??0)+1);}}const reaction=recent.filter(m=>m.emotes>0||/no way|wow|pog|clip/i.test(m.text)).length;const multiplier=current/Math.max(rate,1),threshold=rate+Math.max(3,3*Math.sqrt(Math.max(rate,1)));return {baseline:rate,current,multiplier,change:current-rate,warm,spike:warm&&current>=threshold&&multiplier>=2,messageCount:messages.length,uniqueParticipants:new Set(messages.map(m=>m.user)).size,repeatedTerms:counts,questionClusters:questionClusters(recent),repeatedQuestions:[...questions].filter(([,n])=>n>1),urls:[...new Set(messages.flatMap(m=>m.text.match(/https?:\/\/[^\s]+/g)??[]))].slice(0,20),reactionConcentration:recent.length?reaction/recent.length:0,timestamp:now};}
export function parseChat(envelope:any):{channel:string;message:ChatMessage}|null{if(envelope?.metadata?.message_type!=='notification'||envelope.payload?.subscription?.type!=='channel.chat.message')return null;const e=envelope.payload.event,at=envelope.metadata.message_timestamp;if(!e?.message_id||!e.chatter_user_id||!e.broadcaster_user_id||typeof e.message?.text!=='string'||!Number.isFinite(Date.parse(at)))throw Error('Invalid chat event');return {channel:e.broadcaster_user_id,message:{id:e.message_id,user:e.chatter_user_id,text:e.message.text.slice(0,1000),at,emotes:(e.message.fragments??[]).filter((f:any)=>f.type==='emote').length}};}
export class TwitchSignals {
 streams:Map<string,TwitchStream>; buffers=new Map<string,ChatMessage[]>();seen=new Set<string>();windows:ActivityWindow[]=[];started:string;events=0;dropped=0;truncatedChannels=new Set<string>();
 enhanced:boolean;maxWindows:number;onProgress?:()=>void;
 constructor(streams:TwitchStream[],started:string,options:{maxWindows?:number;questionClusters?:boolean}={}){this.enhanced=options.questionClusters===true;this.maxWindows=options.maxWindows??30;if(!Number.isInteger(this.maxWindows)||this.maxWindows<1||this.maxWindows>30)throw Error('Invalid window cap');if(streams.length>10)throw Error('Too many streams');this.streams=new Map(streams.map(s=>[s.user_id,s]));this.started=started;}
 ingest(envelope:any){const parsed=parseChat(envelope);if(!parsed||!this.streams.has(parsed.channel)||this.seen.has(parsed.message.id))return;const now=parsed.message.at;if(Date.parse(now)<Date.parse(this.started)||Date.parse(now)>Date.parse(this.started)+3600000)return;if(++this.events>pilotLimits.events)throw Error('Twitch event cap reached');this.seen.add(parsed.message.id);let buffer=this.buffers.get(parsed.channel)??[];buffer=buffer.filter(m=>Date.parse(m.at)>Date.parse(now)-360000);buffer.push(parsed.message);if(buffer.length>pilotLimits.messagesPerChannel){buffer=buffer.slice(-pilotLimits.messagesPerChannel);this.truncatedChannels.add(parsed.channel);this.dropped++;}this.buffers.set(parsed.channel,buffer);for(const w of this.windows.filter(w=>w.stream.user_id===parsed.channel&&Date.parse(now)<=Date.parse(w.end)&&Date.parse(now)>=Date.parse(w.start))){if(w.messages.length<100)w.messages.push(parsed.message);else w.truncated=true;}const summary=summarizeChat(buffer,now,this.started);if(!this.truncatedChannels.has(parsed.channel)&&summary.spike&&summary.repeatedTerms.length)this.trigger(parsed.channel,now,['relative_chat_spike','repeated_gta_terms'],summary);if(this.enhanced&&summary.warm&&!this.truncatedChannels.has(parsed.channel)&&summary.questionClusters.length)this.trigger(parsed.channel,now,['question_cluster'],summary);}
 trigger(channel:string,now:string,reasons:string[],signal=summarizeChat(this.buffers.get(channel)??[],now,this.started)){const stream=this.streams.get(channel);if(!stream)return;const prior=this.windows.find(w=>w.stream.id===stream.id&&Date.parse(now)>=Date.parse(w.start)&&Date.parse(now)<=Date.parse(w.end));if(prior){prior.reasons=[...new Set([...prior.reasons,...reasons])];prior.priority=Math.max(prior.priority,this.priority(signal,reasons));return prior;}if(this.windows.length>=this.maxWindows)return;const messages=(this.buffers.get(channel)??[]).filter(m=>Date.parse(m.at)>=Date.parse(now)-120000&&Date.parse(m.at)<=Date.parse(now)+180000);const w:ActivityWindow={id:'twitch:'+stream.id+':'+now,stream,start:new Date(Date.parse(now)-120000).toISOString(),end:new Date(Date.parse(now)+180000).toISOString(),triggeredAt:now,reasons,signal,priority:this.priority(signal,reasons),messages:messages.slice(0,100),clips:[],truncated:messages.length>100||this.truncatedChannels.has(channel),complete:false};this.windows.push(w);return w;}
 priority(signal:ReturnType<typeof summarizeChat>,reasons:string[]){return Math.min(100,Math.round(Math.min(30,signal.multiplier*5)+signal.repeatedTerms.length*5+(this.enhanced?signal.questionClusters.reduce((n,c)=>n+Math.min(20,c.uniqueParticipants*3),0):0)+signal.reactionConcentration*10+(reasons.includes('clip_activity')?20:0)+(reasons.includes('title_change')?10:0)));}
 clip(channel:string,clip:any,now:string){if(typeof clip?.id!=='string'||typeof clip.title!=='string'||!/^https:\/\/(clips\.twitch\.tv|www\.twitch\.tv)\//.test(clip.url??'')||!Number.isFinite(Date.parse(clip.created_at)))return;if(Date.parse(clip.created_at)<Date.parse(this.started)||Date.parse(clip.created_at)>Date.parse(now))return;const key='clip:'+clip.id;if(this.seen.has(key))return;this.seen.add(key);const w=this.trigger(channel,clip.created_at,['clip_activity']);if(w)w.clips.push({id:clip.id,title:clip.title,url:clip.url,created_at:clip.created_at,view_count:clip.view_count,video_id:clip.video_id,vod_offset:clip.vod_offset,creator_name:clip.creator_name});}
 update(stream:TwitchStream,now:string){const previous=this.streams.get(stream.user_id);if(!previous||previous.id!==stream.id)return;if(previous.title!==stream.title&&/money|car|location|secret|glitch|bug|mission|weapon|found|patched/i.test(stream.title))this.trigger(stream.user_id,now,['title_change']);this.streams.set(stream.user_id,stream);}
 finalize(now:string){for(const w of this.windows){w.complete=Date.parse(now)>=Date.parse(w.end);}return this.windows;}
}
export function windowSource(w:ActivityWindow,at:string):SourceItem{const bounded=w.messages.filter(m=>Date.parse(m.at)>=Date.parse(w.start)&&Date.parse(m.at)<=Date.parse(w.end)),clips=w.clips.filter(c=>Date.parse(c.created_at)>=Date.parse(w.start)&&Date.parse(c.created_at)<=Date.parse(w.end));const chat=bounded.map(m=>`[${m.at}] chatter ${m.user}: ${m.text}`).join('\n');const text=['Twitch chat participants report/react to an event; these are unverified chatter statements, not a streamer statement or video observation.',chat,...clips.map(c=>'Clip metadata title: '+c.title)].join('\n');return {id:w.id,platform:'twitch',sourceId:w.id,url:'https://www.twitch.tv/'+w.stream.user_login,author:w.stream.user_login,itemType:'comment',context:{subreddit:'',postId:w.stream.id,postTitle:w.stream.title+' | Declared stream tags: '+(w.stream.tags??[]).map(t=>t.replace(/gtaonline/gi,'GTA Online')).join(', '),postBody:'Official Twitch category: '+w.stream.game_name,parentId:w.stream.id,threadId:'twitch:channel:'+w.stream.user_id,discovery:['official Twitch metadata; reference only, not a streamer statement']},title:'GTA Twitch activity window: '+w.stream.title,text:text.slice(0,pilotLimits.maxTextBytes/4),timestamp:w.triggeredAt,ingestedAt:at,engagement:{score:0},independenceKey:'twitch:channel:'+w.stream.user_id,raw:{sourceType:'activity_window',stream:w.stream,window:{start:w.start,end:w.end,complete:w.complete,truncated:w.truncated||text.length>pilotLimits.maxTextBytes/4},signal:w.signal,excludedOutOfWindow:{messages:w.messages.length-bounded.length,clips:w.clips.length-clips.length},aggregate:{messageCount:bounded.length,uniqueParticipants:new Set(bounded.map(m=>m.user)).size,repeatedQuestions:summarizeChat(bounded,w.end,w.start).repeatedQuestions,urls:summarizeChat(bounded,w.end,w.start).urls},reasons:w.reasons,clips,observationOnly:true,noMediaObserved:true},pilotId:'twitch-v0'};}
export function metadataSource(stream:TwitchStream,type='stream_metadata',at=new Date().toISOString(),metadata:Record<string,unknown>={}):SourceItem{return {id:'twitch:'+type+':'+stream.id,platform:'twitch',sourceId:stream.id,url:'https://www.twitch.tv/'+stream.user_login,author:stream.user_login,title:stream.title,text:'Stream metadata only; no gameplay event observed.',timestamp:at,ingestedAt:at,engagement:{score:0},independenceKey:'twitch:channel:'+stream.user_id,raw:{sourceType:type,stream,...metadata},pilotId:'twitch-v0'};}
export class TwitchAdapter implements SourceAdapter,ScannableSource {
 name='twitch';id='twitch';platform='twitch';windows:ActivityWindow[];
 constructor(windows:ActivityWindow[]=[]){this.windows=windows;}
 async fetchItems(){return this.windows.filter(w=>w.complete).sort((a,b)=>b.priority-a.priority).slice(0,10).map(w=>windowSource(w,new Date().toISOString()));}
 async scan(request:ScanRequest){const at=request.context?.topic;const items=(await this.fetchItems()).filter(s=>!at||s.id===at);return {items:items.slice(0,Math.min(request.limit,10)),checkpoint:{state:{bounded:true}}};}
}
