import {createHash} from 'node:crypto';
import type {SourceItem,Claim} from './model.ts';
import type {SourceAdapter} from './adapters.ts';
export type WebHit={url:string;query:string;sourceType:string};
export interface WebDiscoveryProvider {name:string;discover(queries:string[]):Promise<WebHit[]>;costUSD:number|null}
export class SearchManifestProvider implements WebDiscoveryProvider {
 name='public-search-reviewed-manifest';costUSD:number|null=null;
 hits:WebHit[];constructor(hits:WebHit[]){this.hits=hits;}
 async discover(queries:string[]){return this.hits.filter(h=>queries.includes(h.query));}
}
export type AccessPolicy={domain:string;termsUrl:string;reviewedAt:string;decision:'allow'|'skip';reason:string;license?:string;excerptWords:number;delayMs:number};
export const webLimits={maxItems:50,maxCandidates:50,maxPerDomain:8,maxRequests:100,maxBytes:3000000};
const aiAgents=['vicewireresearch','chatgpt-user','oai-searchbot','gptbot'];
export function robotsDecision(text:string,path:string){
 const groups:{agents:string[];rules:{allow:boolean;path:string}[];delay:number}[]=[];let g:any=null;
 for(const raw of text.split(/\r?\n/)){const line=raw.split('#')[0].trim(),m=line.match(/^([^:]+):\s*(.*)$/);if(!m)continue;const key=m[1].trim().toLowerCase(),v=m[2].trim();if(key==='user-agent'){if(!g||g.rules.length||g.delay){g={agents:[],rules:[],delay:0};groups.push(g);}g.agents.push(v.toLowerCase());}else if(g&&(key==='allow'||key==='disallow')&&v)g.rules.push({allow:key==='allow',path:v});else if(g&&key==='crawl-delay')g.delay=Math.max(0,Number(v)*1000||0);}
 let delayMs=0;for(const agent of aiAgents){const specific=groups.filter(g=>g.agents.some(a=>a!=='*'&&agent.includes(a))),applicable=specific.length?specific:groups.filter(g=>g.agents.includes('*'));const rules=applicable.flatMap(g=>g.rules).filter(r=>{const pattern=r.path.replace(/[.+?^${}()|[\]\\]/g,'\\$&').replaceAll('*','.*');return new RegExp('^'+pattern).test(path);}).sort((a,b)=>b.path.replaceAll('*','').length-a.path.replaceAll('*','').length||Number(b.allow)-Number(a.allow));delayMs=Math.max(delayMs,...applicable.map(g=>g.delay));if(rules[0]&&!rules[0].allow)return {allowed:false,delayMs,reason:'robots restriction for '+agent};}
 return {allowed:true,delayMs,reason:'robots permits reviewed path'};
}
export function plain(html:string){return html.replace(/<script\b[\s\S]*?<\/script>/gi,'').replace(/<style\b[\s\S]*?<\/style>/gi,'').replace(/<!--[^]*?-->/g,'').replace(/<[^>]*>/g,' ').replace(/&#x([a-f\d]+);/gi,(_,n)=>String.fromCodePoint(parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&(?:apos|#39);/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();}
function articleRegion(html:string){const tags=/<\/?article\b[^>]*>/gi;let m,start=-1,depth=0;while((m=tags.exec(html))){if(!m[0].startsWith('</')){if(start<0)start=tags.lastIndex;depth++;}else if(--depth===0&&start>=0){const region=html.slice(start,m.index);if(/<h1\b/i.test(region))return region;start=-1;}}const main=html.match(/<main\b[^>]*>([^]*?)<\/main>/i);return main?.[1]??'';}
function jsonNodes(html:string){const nodes:any[]=[];const visit=(v:any)=>{if(Array.isArray(v))v.forEach(visit);else if(v&&typeof v==='object'){nodes.push(v);if(v['@graph'])visit(v['@graph']);}};for(const m of html.matchAll(/<script[^>]*type=["']application\/ld\+json["'][^>]*>([^]*?)<\/script>/gi))try{visit(JSON.parse(m[1]));}catch{}return nodes;}
function date(value:any,now:string){if(typeof value!=='string')return null;const ms=Date.parse(value);return Number.isFinite(ms)&&ms<=Date.parse(now)?new Date(ms).toISOString():null;}
export function parseWebPage(html:string,url:string,words:number,now=new Date().toISOString()){
 const nodes=jsonNodes(html),article=nodes.find(n=>/Article|Posting/.test(String(n['@type'])))??{},region=articleRegion(html).replace(/<(nav|aside)\b[^>]*>[^]*?<\/\1>/gi,'').replace(/<details\b[^>]*class=["'][^"']*(?:contents|toc)[^"']*["'][^>]*>[^]*?<\/details>/gi,'');
 const title=plain(article.headline??region.match(/<h1\b[^>]*>([^]*?)<\/h1>/i)?.[1]??html.match(/<title[^>]*>([^]*?)<\/title>/i)?.[1]??'');
 const meta=(name:string)=>{for(const m of html.matchAll(/<meta\b[^>]*>/gi))if(m[0].includes(name))return m[0].match(/content=["']([^"']*)/i)?.[1];};
 const publishedAt=date(article.datePublished??meta('article:published_time'),now),updatedAt=date(article.dateModified??meta('article:modified_time'),now);
 const authors=Array.isArray(article.author)?article.author:[article.author];const author=authors.map(a=>typeof a==='string'?a:a?.name).filter(Boolean).join(', ')||meta('name="author"')||null;
 const blocks=[...region.matchAll(/<(p|li|h[2-4]|tr)\b[^>]*>([^]*?)<\/\1>/gi)].map(m=>plain(m[2])).filter(t=>t.length>20&&!/^Image|Zoom image|Advertisement|Follow @|About the author|View profile/i.test(t));
 // Ordered contiguous excerpt, never a synthetic assembly of isolated claims.
 const substantive=blocks.join('\n');const tokens=substantive.split(/\s+/);const text=tokens.slice(0,words).join(' ');
 const links=[...region.matchAll(/href=["']([^"']+)["']/gi)].flatMap(m=>{try{const u=new URL(m[1],url);return u.protocol==='https:'?[u.href]:[];}catch{return [];}});
 return {title,author,publishedAt,updatedAt,text,substantiveWords:tokens.length,excerptTruncated:tokens.length>words,links:[...new Set(links)].slice(0,30),fullTextHash:createHash('sha256').update(substantive).digest('hex')};
}
export function webQuality(p:ReturnType<typeof parseWebPage>,type:string,now:string){let score=0;const positive:string[]=[],negative:string[]=[];const add=(n:number,s:string)=>{score+=n;(n>0?positive:negative).push(s);};if(type==='official')add(25,'official provenance; authority remains claim-dependent');if(p.author)add(8,'identifiable author');if(p.substantiveWords>=300)add(15,'substantive written content');else add(-20,'thin content');if(/gta|grand theft auto/i.test(p.title))add(8,'GTA-specific topic');if(/GTA\$|\d[\d,.]*\s*(?:million|minutes|hours|%|x)|\b(?:first|then|requires|upgrade|invite-only|cooldown)\b/i.test(p.text))add(12,'concrete quantities, conditions or steps');if(p.links.some(l=>/rockstargames|support\.rockstar/.test(l)))add(8,'source citations; not independent confirmation');const stamp=p.updatedAt??p.publishedAt;if(stamp){const days=(Date.parse(now)-Date.parse(stamp))/86400000;add(days<=30?15:days<=120?5:-15,days<=30?'recent stated date':days<=120?'dated within 120 days':'older date; currentness uncertain');}else add(-20,'undated; retrieval is not publication date');if(/best|secret|millions|only.*need/i.test(p.title)&&!p.text.match(/\d|requires|steps|because/i))add(-12,'headline unsupported by concrete excerpt');if(/buy gta.*money|buy.*account|sponsored|affiliate/i.test(p.text))add(-15,'promotion risk');if(/patched|no longer|outdated|predate|nerf/i.test(p.text))negative.push('patch/outdated language requires temporal review');return {score:Math.max(0,Math.min(100,score)),positive,negative};}
export function claimAuthority(item:SourceItem,claim:Claim){return item.raw.sourceType==='official'&&/patch|update|bonus|release|mode|event/.test(claim.predicate)&&!/best|fastest|optimal/.test(claim.claim)?'official for stated update/event; gate unchanged':'no automatic official authority for this proposition';}
export class WebSourceAdapter implements SourceAdapter {
 name='web-pilot';requests=0;skips:{url:string;reason:string}[]=[];private robots=new Map<string,string>();private last=new Map<string,number>();
 provider:WebDiscoveryProvider;queries:string[];policies:AccessPolicy[];limit:number;fetcher:typeof fetch;
 constructor(provider:WebDiscoveryProvider,queries:string[],policies:AccessPolicy[],limit=40,fetcher:typeof fetch=fetch){if(limit<1||limit>50)throw Error('Web pilot maximum 50 items');this.provider=provider;this.queries=queries;this.policies=policies;this.limit=limit;this.fetcher=fetcher;}
 private async request(url:string){if(++this.requests>webLimits.maxRequests)throw Error('Web request cap reached');const r=await this.fetcher(url,{redirect:'manual',signal:AbortSignal.timeout(15000),headers:{'User-Agent':'ViceWireResearch/0.1 (bounded internal AI-assisted research; respects AI robot restrictions)'}});if(!r.ok)throw Error('HTTP '+r.status+'; no redirect/auth/challenge bypass');if(/noai|noindex.*noai/i.test(r.headers.get('x-robots-tag')??''))throw Error('AI use opt-out');if(Number(r.headers.get('content-length')??0)>webLimits.maxBytes)throw Error('Response too large');const reader=r.body!.getReader();let total=0;const chunks:Uint8Array[]=[];while(true){const {done,value}=await reader.read();if(done)break;total+=value.length;if(total>webLimits.maxBytes){await reader.cancel();throw Error('Response too large');}chunks.push(value);}return Buffer.concat(chunks).toString('utf8');}
 async fetchItems(){const hits=(await this.provider.discover(this.queries)).slice(0,webLimits.maxCandidates),items:SourceItem[]=[],counts=new Map<string,number>(),seen=new Set<string>();for(const hit of hits){if(items.length>=this.limit)break;try{const u=new URL(hit.url);if(u.protocol!=='https:'||u.username||u.password||!this.policies.some(p=>p.domain===u.hostname))throw Error('URL outside reviewed HTTPS domains');u.hash='';const url=u.href;if(seen.has(url))continue;seen.add(url);const policy=this.policies.find(p=>p.domain===u.hostname)!;if(policy.decision!=='allow')throw Error(policy.reason);if((counts.get(u.hostname)??0)>=webLimits.maxPerDomain)throw Error('Per-domain item cap');if(!this.robots.has(u.origin))this.robots.set(u.origin,await this.request(u.origin+'/robots.txt'));const decision=robotsDecision(this.robots.get(u.origin)!,u.pathname+u.search);if(!decision.allowed)throw Error(decision.reason);const wait=Math.max(policy.delayMs,decision.delayMs)-(Date.now()-(this.last.get(u.hostname)??0));if(wait>0)await new Promise(r=>setTimeout(r,Math.min(wait,60000)));this.last.set(u.hostname,Date.now());const html=await this.request(url);if(/cf-chl-|verify you are human|captcha|just a moment/i.test(html.slice(0,15000)))throw Error('Anti-bot challenge; skipped');if(/<meta[^>]+(?:noai|noimageai)/i.test(html))throw Error('AI use opt-out');const now=new Date().toISOString(),page=parseWebPage(html,url,policy.excerptWords,now);if(!page.text||!page.title)throw Error('No clean server-rendered article text');const quality=webQuality(page,hit.sourceType,now),id='web:'+createHash('sha256').update(url).digest('hex').slice(0,24);const prior=items.find(s=>s.raw.fullTextHash===page.fullTextHash);const reference=page.links.find(l=>/rockstargames\.com\/.*newswire\/article/.test(l));items.push({id,platform:'web',sourceId:url,url,author:page.author,title:page.title,text:page.text,timestamp:page.updatedAt??page.publishedAt??'1970-01-01T00:00:00.000Z',engagement:{score:0},ingestedAt:now,independenceKey:reference?'web:upstream:'+reference:'web:domain:'+u.hostname.replace(/^www\./,''),copiedFrom:prior?.id,itemType:'post',pilotId:'web-v0',raw:{domain:u.hostname,sourceType:hit.sourceType,publishedAt:page.publishedAt,updatedAt:page.updatedAt,retrievedAt:now,discoveryQuery:hit.query,quality,license:policy.license??'all rights reserved; limited internal excerpt only',termsUrl:policy.termsUrl,excerptTruncated:page.excerptTruncated,excerptWords:page.text.split(/\s+/).length,fullTextHash:page.fullTextHash,citations:page.links,upstreamReference:reference??null,storage:'bounded excerpt only; full HTML transient; no media'}});counts.set(u.hostname,(counts.get(u.hostname)??0)+1);}catch(e){this.skips.push({url:hit.url,reason:e instanceof Error?e.message:'retrieval failed'});}}return items;}
}
